### ISSUE TITLE
Allow to configure either caching or enable/disable prefetching of consumer keys

### ISSUE THREAD

**Issue by mazubieta** [pantsel/konga#10]
We have a lot of consumers ... and unfortunately if too many users are playing with Konga you end up DOSing Kong a little bit, from all of the `GET /kong/consumers/{id}/credentials` calls.  Ideally I think these calls should be cached, but just having an option to configure Konga to disable this action would be enough to make this usable.

**Comment by pantsel** [comment]
@mazubieta 
This action is a leftover from a featurei decided to deprecate. It has already been removed (local repo) cause it adds nothing to the overall functionality. A new version without that action will be published in the upcoming days.

**Comment by pantsel** [comment]
@mazubieta 

Just pushed a new commit that removed consumer credentials prefetching.

**Comment by mazubieta** [comment]
Thanks!  I'll check it out.  I've got some more requests that I may type up
for you.  I'm hacking around what I need, but I think it should probably
end back upstream to you, but like I said before ... really not a
javascript dev so I'm just probing and prodding until I get the desired
outcome.  I'll submit those sometime this weekend or Monday.  Thanks again!

**Comment by pantsel** [comment]
Do your thing. As long as your hacking works, i will merge your PRs. When I find some spare time I will do a general refactoring if and where it is needed.

**Comment by pantsel** [comment]
Closing this issue since the debated feature no longer applies.
