### ISSUE TITLE
Error: kongadmin@0.8.4 start: `node --harmony app.js`

### ISSUE THREAD

**Issue by dragon28** [pantsel/konga#103]
Hello People,

For your information:

npm start

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kongadmin@0.8.4~prestart: kongadmin@0.8.4
6 silly lifecycle kongadmin@0.8.4~prestart: no script for prestart, continuing
7 info lifecycle kongadmin@0.8.4~start: kongadmin@0.8.4
8 verbose lifecycle kongadmin@0.8.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle kongadmin@0.8.4~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/dragon/konga/node_modules/.bin:/home/dragon/openresty/luarocks/bin:/home/dragon/openresty/bin:/home/dragon/openresty/nginx/sbin:/home/dragon/.luarocks/bin:/home/dragon/go/bin:/homr/dragon/.npm-packages/bin:/opt/lampp/bin:/home/dragon/openresty/luarocks/bin:/home/dragon/openresty/bin:/home/dragon/openresty/nginx/sbin:/home/dragon/bin:/home/dragon/.local/bin:/home/dragon/.luarocks/bin:/home/dragon/go/bin:/home/dragon/.npm-packages/bin:/opt/lampp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle kongadmin@0.8.4~start: CWD: /home/dragon/konga
11 silly lifecycle kongadmin@0.8.4~start: Args: [ '-c', 'node --harmony app.js' ]
12 silly lifecycle kongadmin@0.8.4~start: Returned: code: 1  signal: null
13 info lifecycle kongadmin@0.8.4~start: Failed to exec start script
14 verbose stack Error: kongadmin@0.8.4 start: `node --harmony app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid kongadmin@0.8.4
16 verbose cwd /home/dragon/konga
17 error Linux 4.10.0-33-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error kongadmin@0.8.4 start: `node --harmony app.js`
22 error Exit status 1
23 error Failed at the kongadmin@0.8.4 start script 'node --harmony app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the kongadmin package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node --harmony app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs kongadmin
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls kongadmin
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Please take a look at the mentioned issue.

Thanks

**Comment by pantsel** [comment]
Hi, @dragon28 ,
I just tried to reproduce this error but everything worked fine on my end on an Ubuntu VM.

<pre>
npm@3.10.10
node@6.11.3
</pre>

Try a couple of things:

1. Make sure another instance of Konga is not running.
2. Make sure nothing else is running on port 1337.
3. Delete the <code>node_modules</code> folder and run <code>npm install</code> again.

You could also try using the [official docker image](https://store.docker.com/community/images/pantsel/konga) instead of building from source.

**Comment by dragon28** [comment]
@pantsel 

Thank you for providing the solution.

It seems that I have edited the 'config/connections.js' without properly save the mentioned file.

Thanks :) +1:
