### ISSUE TITLE
Change configuration parameters inside Konga

### ISSUE THREAD

**Issue by Xanagandr** [pantsel/konga#105]
Would be useful if we could change Kong's configuration directly in Konga's  "Info" page.

**Comment by jeremyjpj0916** [comment]
How would that even be possible? Not exposed via Kong's Admin API? It would be possible if Kong extended Admin API's that updated environment variables and would do a kong restart automatically for people. Then this would totally be feasible.

**Comment by pantsel** [comment]
Yes, it's not possible via the api, but it is through an SSH connection.
But, even that way, i don't know if it's worth it.
After all, there's a reason why some things must stay difficult to configure.
