### ISSUE TITLE
API Key shown in plain text in communication between browser and konga server

### ISSUE THREAD

**Issue by marckhouzam** [pantsel/konga#107]
Related to issue #92, the API Key should be hidden to prevent users without explicit admin privileges to get them by using the api key.

Currently, the api key is sent in plain text from the browser to the konga server, so by inspecting that communication, any user can find the api key.

I don't know much about the konga implementation but here are my thoughts.
The konga server must already know about the details about the api key and kong url.  The browser could then simply send the name of the connection to be used and the server would fetch the url and api key.

That way, neither the api key nor even the url could be seen between the browser and the konga server.

**Comment by pantsel** [comment]
@marckhouzam , that is already on my todo list. I'll try to implement it with v0.8.6

**Comment by pantsel** [comment]
@marckhouzam , can you please point me to an action that Konga sends the ip and apiKey as plain text to the server? From what I can see that has been changed for some time now but still there's a probability that  i missed something the first time.

**Comment by marckhouzam** [comment]
I've spoken to the person that had seen this problem but with a newer Konga, they don't see it anymore.

Thanks for improving Konga in such fashion.
I'm closing this, and sorry for the wasted time.
