### ISSUE TITLE
cannot see targets in upstream

### ISSUE THREAD

**Issue by simonpie** [pantsel/konga#110]
In konga 0.8.301, when listing upstream targets, nothing shows up even though targets are defined and I can curl them on the kong server.

**Comment by pantsel** [comment]
@simonpie, check this out #89 .

This is a Kong issue https://github.com/Mashape/kong/issues/2840  , wich is fixed but not yet on an official release.

You could try using the 0.11.0rc2 kong image.

**Comment by simonpie** [comment]
Thanks.

I shall repull our docker image.
