### ISSUE TITLE
Disabling signup also prevents administrators from creating users

### ISSUE THREAD

**Issue by Permagate** [pantsel/konga#119]
### Background

I'd like to keep konga access internally, so I disable user signup:

![screen shot 2017-10-19 at 6 11 59 pm](https://user-images.githubusercontent.com/2970271/31768367-4e6ba3ba-b4f9-11e7-8e05-502e5163e256.png)

And the signup tab was correctly removed from the login page.

![screen shot 2017-10-19 at 6 15 06 pm](https://user-images.githubusercontent.com/2970271/31768477-bf51c4ba-b4f9-11e7-8eeb-8b021a4b8601.png)

### Problem

However, as an administrator, now I cannot create user at all. Whenever I tried to create a new user, I got 403 error:

![screen shot 2017-10-19 at 6 19 32 pm](https://user-images.githubusercontent.com/2970271/31768581-2274dcf8-b4fa-11e7-9672-32aa0d758fb2.png)

I can if I re-enable user signup.

### Expectation

When disabling user signup, I expected it to only disable signup feature by random people, not also preventing administrator to create users.

**Comment by pantsel** [comment]
@Permagate , just update Konga. Get version `0.8.9` or `:latest`.
The issue is fixed in commit https://github.com/pantsel/konga/commit/43a02f4363f968a98bcbdde8b06dff96e2d57585.

**Comment by Permagate** [comment]
Thank you, that works!

Closing this issue now.
