### ISSUE TITLE
Block non admin users from snapshots

### ISSUE THREAD

**Issue by gabrie30** [pantsel/konga#121]
Is there a way to block regular users from viewing the snapshots section? 

My understanding is if a user accidentally restored an older snapshot, or wanted to do something malicious by uploading a bad snapshot, they could cause a lot of damage.

Since this is a potential security issue I was hoping there would be a way to block non admin from access.

**Comment by pantsel** [comment]
@gabrie30 ,
right now there isn't. 

I will put it in the next release.

Originaly, Konga was not created for "non admin" users. I mean, why have access to a Gateway admin tool if not to configure it at the first place? :)

Aparently tho, people keep finding different use cases, so I'm kind of going with the flow.

👍

**Comment by gabrie30** [comment]
@pantsel Thanks for the quick reply. I appreciate you adding this to the next release.

Currently, Kong doesn't have a good way to view the route/plugin configuration in an easily consumable format. With Konga we can give some of our team the ability to be admins and other teammates the ability to securely view the route/plugin configuration, which makes their debugging process easier and faster.

This is by far the most thought out and well designed dashboard, so thanks for your hard work!

**Comment by gabrie30** [comment]
Awesome work thanks! This can be closed. 🥇
