### ISSUE TITLE
Question: Allows Konga schedule snapshot?

### ISSUE THREAD

**Issue by vicmonmena** [pantsel/konga#123]
Hi!

Any way to schedule snapshots to take them automatically?

Thank you!

**Comment by pantsel** [comment]
@vicmonmena , as of the latest commits, Konga allows you to schedule node snapshots. This is a feature that needs more testing tho, so it would be great if you could provide some feedback. 

Last but not least, don't try it on Kong 0.9 :) 
It may or may not work, but, either way the support for so old Kong versions will be discontinued.

Thanks for the feedback!
