### ISSUE TITLE
Uncaught ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by wsdflink** [pantsel/konga#124]
Hi, after i installed konga and start with 'npm start', it shows the following error in console:

Uncaught ReferenceError: angular is not defined.

**Comment by pantsel** [comment]
Hi @wsdflink ,

this is a duplicate of #117 , #84 , #79 , #53 .

The issue is also mentioned in the [FAQ](https://github.com/pantsel/konga#faq) section of README.md
