### ISSUE TITLE
Authenticating to admin through proxy loopback, apikey in body

### ISSUE THREAD

**Issue by gabrie30** [pantsel/konga#125]
Thanks for all your work on Konga. Currently running into an issue using the apikey via the admin loop-back, hoping this will be an easy fix.

When trying to create a connection from Konga to the kong proxy via an admin-loopback, Konga requires the apikey to be placed as a query string parameter. This exposes the key in the logs creating a security issue. To prevent this, Konga should allow the apikey to be sent as either a query string parameter or included in the request body since both are configurable options in the key-auth kong plugin. 

![image](https://user-images.githubusercontent.com/1512282/32199805-81d21fd2-bd8b-11e7-9f7c-9352736d4eb4.png)

**Comment by pantsel** [comment]
@gabrie30 , just pushed a commit in the master branch that refs this issue. Check it out if you want but the actual new version won't be out until later this week because I've made other mods as well and i need to properly test them.

**Comment by gabrie30** [comment]
Awesome thanks!
