### ISSUE TITLE
Enhancement: Konga Admin Loop-back support (Update: JWT as the TTL hash pass choice)

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#126]
Konga works great for apiKey based authorization. For the application to be fully baked for modern day security most companies like a time based expiry token for cross application API communication and access validation. I think If Konga adds a drop down for apiKey auth or OAuth against Kong's native Oauth client credentials pattern then all security bases will be covered:

mykonggateway.com/admin-api/oauth2/token?grant_type=client_credentials&client_id={client_id}&client_secret={client_secret}  to get the token.

Then apply the token like:
https://mykonggateway.com/admin-api?access_token={token_generated_from_prior_call}

Then Konga + Kong will be able to communicate in a much more secure manner where one transaction sniff does not grant unlimited access(apikey = Unlimited access).

So pretty much on the welcome page a drop down would occur for apikey OR Oauth2.0, In the event OAuth2.0 is selected user must provide into konga fill form a client_id and a client_secret as well as a expire time in seconds, so Konga waits up till 10 seconds(or whatever you think best) prior to the expire time before generating a fresh token and resetting its timer.  

-Jeremy

**Comment by jeremyjpj0916** [comment]
As an update on a side chat, pantsel informed me the JWT pattern was a much easier implementation, so we have agreed we will go with that with a short TTL (currently hard coded to 2 mins which seems fine to me). Will be testing JWT pattern here and updating with my findings on if its functioning.

**Comment by jeremyjpj0916** [comment]
Update, running 0.9.0 under the next branch and I am not currently seeing GUI functionality for the JWT Auth pattern. There are multiple ways JWT can be implemented from what I have read so if you can touch on the pattern you used I will help write up a blurb we can add to the Konga ReadME on it.

**Comment by pantsel** [comment]
@jeremyjpj0916 ,

compare your ui with the demo one at http://139.59.145.231:1337

Maybe there's some caching issues going on and you need to hard refresh the browser.

**Comment by jeremyjpj0916** [comment]
You were correct, I see it now. Will be testing it shortly :) ! Looks awesome man.

**Comment by jeremyjpj0916** [comment]
Following up after testing thus far, seems 100% working and incredible! It also worked with ACL plugin enabled so be sure to use that too on the API in the event you have other consumers with JWT tokens.

Jwt Applied to the Admin API Screenshot for use:
![apijwtplugin](https://user-images.githubusercontent.com/31913027/32687190-36549fbe-c685-11e7-8d9a-2083ee57b671.png)

My consumer jwt credentials:
![clientjwtcreds](https://user-images.githubusercontent.com/31913027/32687191-452e61f0-c685-11e7-82f6-f635aee7f025.png)

And then the Konga JWT entry to connect the endpoint:
![jwtentry](https://user-images.githubusercontent.com/31913027/32687196-5667905e-c685-11e7-931c-2dd9a48b1297.png)

I think we can mark this issue closed. Great work!
-Jeremy
