### ISSUE TITLE
Greeting never received SMTPConnection

### ISSUE THREAD

**Issue by wsdflink** [pantsel/konga#127]
Does konga configure SMTPConnection with SSL by default? I configured email notification in the setting module and found the following error:

[31merror: [39mHealth_checks:notify:error Error: Greeting never received
    at SMTPConnection._formatError (/home/admin/konga/node_modules/nodemailer/lib/smtp-connection/index.js:591:19)
    at SMTPConnection._onError (/home/admin/konga/node_modules/nodemailer/lib/smtp-connection/index.js:564:20)
    at Timeout._greetingTimeout.setTimeout (/home/admin/konga/node_modules/nodemailer/lib/smtp-connection/index.js:505:22)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by pantsel** [comment]
@wsdflink , just tried it with SMTP and no SSL and everything worked for me.
<pre>
Health_checks:notify:success { accepted: [ 'tselentispanagis@gmail.com' ],
  rejected: [],
  envelopeTime: 306,
  messageTime: 109,
  messageSize: 752,
  response: '250 2.0.0 Ok: queued as 3yRgzP404SzCjRJ',
  envelope: 
   { from: 'konga@konga.test',
     to: [ 'tselentispanagis@gmail.com' ] },
  messageId: '<fb96ae01-a575-1530-497c-1d26f8d02efc@konga.test>' }
</pre>

Are you sure your settings are correct?

Do you get this error with node or API health checks?

**Comment by wsdflink** [comment]
@pantsel Thanks. I got this error from API health checks. I tried my gmail address and modified gmail configuration to allow unsafe access from other clients. Then it worked. I think it's better to provide a switch on-off to configure that using SSL or not in SMTP setting. It seems not to support SSL for now. Thanks again.

**Comment by pantsel** [comment]
@wsdflink, will do that. Thanks for the input.

**Comment by qingmingzzz** [comment]
how to look smtp log？
