### ISSUE TITLE
Bug: Display when running Cassandra

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#128]
![image](https://user-images.githubusercontent.com/31913027/32307963-b8ee0808-bf59-11e7-9b4a-871c8c57815d.png)

When running Cassandra the tags do not entirely make sense and are incorrect on homepage display. I assume since you use postgresql in your environment you did not give much testing or thought to the display for when Cassandra is used. I suggest this for when the db type is set to Cassandra:

DBMS = Cassandra
Hosts = ${cassandra_contact_points} returned from the Admin API
Keyspace = kong
User = ${cassandra_username}  returned from the Admin API
Port = ${cassandra_port} returned from the Admin API

It's not a pressing bug so prioritize this as low after getting those awesome other features finished first ;) .

**Comment by pantsel** [comment]
Closing this as an easy fix, It didn't even had to go to a priorities list :),

**Comment by jeremyjpj0916** [comment]
Still a problem here:

For Cassandra config I still see a:

Database = kong on the display, this is not valid since the Keyspace is the db when it comes to Cassandra, can get rid of the database = ____ display for cassandra
