### ISSUE TITLE
Make it possible to add Kong nodes based on url

### ISSUE THREAD

**Issue by bakstad** [pantsel/konga#13]
We run kong on a cluster which sits behind a load balancer. The IP and port of the kong instances is not fixed and therefore it is difficult to use Konga.

It would be nice if we could specify new Kong nodes with the URL to our load balancer and based on the cluster info Konga could figure out the rest.

Summary: Instead of having to provide IP:port, i want to add new node based on a URL. Say `http://internal.mysite.com/kong-admin-endpoint/`.

**Comment by pantsel** [comment]
@bakstad ,

Sorry for the late response.

Just pushed an update based on your Fork. 

If you're satisfied on how your fork functions (Dockerfile and all), a pull request would be most welcome.

Cheers.

**Comment by pantsel** [comment]
Closing the issue.

Resolved in commit 95cd97ca0efac6a31d70986c9ec3e82e768e91e9 .
