### ISSUE TITLE
Invalid Request when trying to get list of consumers and apis

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [pantsel/konga#130]
Hello.

I have successfully deployed konga and connected it to my kong application. This dashboard able to create consumers and apis.

However, wehn I try to open their page in order to see them as list it shows nothing. In javascript console there is a giant error text:

    <div id="content">
            <p><b>Invalid Request</b> error was encountered while trying to process the request:</p>

            <blockquote id="data">
                <pre>GET /consumers?size=4294967295 HTTP/1.1
                          Content-Type: application/json
                          Host: 172.28.5.112:8001
                          Accept: application/json
                          Content-Length: 2
                         Connection: close
                </pre>
            </blockquote>

        <p>Some possible problems are:</p>
        <ul>
            <li id="missing-method">
                <p>Missing or unknown request method.</p>
            </li>
            <li id="missing-url">
                <p>Missing URL.</p>
            </li>
            <li id="missing-protocol">
                <p>Missing HTTP Identifier (HTTP/1.0).</p>
            </li>
            <li>
                <p>Request is too large.</p>
            </li>
            <li>
                <p>Content-Length missing for POST or PUT requests.</p>
            </li>
            <li>
                <p>Illegal character in hostname; underscores are not allowed.</p>
            </li>
            <li>
                <p>HTTP/1.1 <q>Expect:</q> feature is being asked from an HTTP/1.0 software.</p>
            </li>
        </ul>

        <br>
    </div>

But when I try to access to my consumers via `http://172.28.5.112:8001/consumers` it successfully shows my created consumers.

Is it bug?

**Comment by pantsel** [comment]
@SuperMasterBlasterLaser , that is not a response that Konga generates and I don;t think Kong responds with HTML. Are you behind some kind of firewall / proxy / load balancer? Maybe for some reason your request is being interupted and cut in the middle? Have you tried on a different browser?

I have never seen that response again :)

**Comment by SuperMasterBlasterLaser** [comment]
I have a proxy, but in my machine I have added `no_proxy=172.28.5.112` that is why when I make `curl http://172.28.5.112:80001/consumers` it works.

However, I think konga somehow ignores this env variable.
