### ISSUE TITLE
Error handling during seeding/upgrading fails

### ISSUE THREAD

**Issue by infoview-team** [pantsel/konga#133]
I was attempting to perform an update to the latest code and ran into an issue with the seeding/updating of the database.  
The problem I was having was a misconfiguration in our system but I think I found a bug in the error handling code in models.js
`        self.count().exec(function (err, count) {

            if(err) {
                sails.log.error("Failed to seed " + modelName, error);
                return callback();
            }`

Should this be the following instead?
`        self.count().exec(function (err, count) {

            if(err) {
                sails.log.error("Failed to seed " + modelName, err);
                return callback();
            }`

**Comment by pantsel** [comment]
Yes man! Thanks for the notice! Cheers!

**Comment by infoview-team** [comment]
Message Title 
     
     
         
             
             
                 
                     
                         
                              
                             
                             pantsel/konga created an issue 
                             
                         
                     
                 
             
             
                 
                     
                         
                             
                            
                                 
                             
                         
                         
                             
                                 
                                     
                                         Infoview Helpdesk /  DESK-93808 
                                         
                                     
                                     
                                          Re: [pantsel/konga] Error handling during seeding/upgrading fails (#133)  
                                         
                                     
                                 
                             
                         
                         
                             
                                 
                                     
                                        
                                            Issue Type:
                                         
                                          Request 
                                         
                                     
                                     
                                        
                                            Assignee:
                                         
                                        
                                             Unassigned 
                                         
                                     
                                     
                                        
                                            Created:
                                         
                                        
                                             16-Nov-2017 2:58 PM 
                                         
                                     
                                     
                                        
                                            Reporter:
                                         
                                         pantsel/konga 
                                         
                                     
                                 
                             
                         
                         
                             
                                 
                                     
                                         
                                            Yes man! Thanks for the notice! Cheers! 
                                            — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or mute the thread .  
                                         
                                     
                                 
                             
                         
                         
                             
                             
                         
                         
                         
                            
                                 
                             
                         
                     
                 
             
             
                 
                     
                         
                             
                                 
                                     
                                         
                                             
                                                 
                                                     
                                                         
                                                             Helpdesk Contacts 
                                                             
                                                         
                                                         
                                                            
                                                                 Phone: 
                                                             
                                                             07 3014 2222 
                                                             
                                                         
                                                         
                                                            
                                                                 Fax: 
                                                             
                                                             07 3014 2200 
                                                             
                                                         
                                                         
                                                            
                                                                 Website: 
                                                             
                                                             http://infoview.com.au 
                                                             
                                                         
                                                     
                                                 
                                             
                                         
                                     
                                 
                             
                         
                     
                 
             
             
                 
                     
                         
                             
                                This is an automatic notification from Infoview Central. If you wish to contact the helpdesk regarding this request please reply to this email. Please do not edit or remove the email subject. 
                                The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer. Any views or opinions expressed in this email are solely those of the author and do not necessarily represent those of Infoview Technologies Pty Ltd.

**Comment by infoview-team** [comment]
Message Title 
     
     
         
             
             
                 
                     
                         
                              
                             
                             pantsel/konga created an issue 
                             
                         
                     
                 
             
             
                 
                     
                         
                             
                            
                                 
                             
                         
                         
                             
                                 
                                     
                                         Infoview Helpdesk /  DESK-93811 
                                         
                                     
                                     
                                          Re: [pantsel/konga] Error handling during seeding/upgrading fails (#133)  
                                         
                                     
                                 
                             
                         
                         
                             
                                 
                                     
                                        
                                            Issue Type:
                                         
                                          Request 
                                         
                                     
                                     
                                        
                                            Assignee:
                                         
                                        
                                             Unassigned 
                                         
                                     
                                     
                                        
                                            Created:
                                         
                                        
                                             16-Nov-2017 4:40 PM 
                                         
                                     
                                     
                                        
                                            Reporter:
                                         
                                         pantsel/konga 
                                         
                                     
                                 
                             
                         
                         
                             
                                 
                                     
                                         
                                            Closed #133 . 
                                            — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or mute the thread .  
                                         
                                     
                                 
                             
                         
                         
                             
                             
                         
                         
                         
                            
                                 
                             
                         
                     
                 
             
             
                 
                     
                         
                             
                                 
                                     
                                         
                                             
                                                 
                                                     
                                                         
                                                             Helpdesk Contacts 
                                                             
                                                         
                                                         
                                                            
                                                                 Phone: 
                                                             
                                                             07 3014 2222 
                                                             
                                                         
                                                         
                                                            
                                                                 Fax: 
                                                             
                                                             07 3014 2200 
                                                             
                                                         
                                                         
                                                            
                                                                 Website: 
                                                             
                                                             http://infoview.com.au 
                                                             
                                                         
                                                     
                                                 
                                             
                                         
                                     
                                 
                             
                         
                     
                 
             
             
                 
                     
                         
                             
                                This is an automatic notification from Infoview Central. If you wish to contact the helpdesk regarding this request please reply to this email. Please do not edit or remove the email subject. 
                                The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer. Any views or opinions expressed in this email are solely those of the author and do not necessarily represent those of Infoview Technologies Pty Ltd.

**Comment by infoview-team** [comment]
Glad to help, always nice to try and contribute... also I have turned off notifications from our helpdesk system so it doesn't reply to this (I hope)
