### ISSUE TITLE
Error with multiple instances of Konga (Allow horizontal scaling by adding environment variables for redis backed websockets)

### ISSUE THREAD

**Issue by mlehner616** [pantsel/konga#137]
I believe I'm receiving websocket connection errors when running more than one instance of konga because the sails adapter is configured for `memory` instead of using a redis backend. ([sockets.js Line 38](https://github.com/pantsel/konga/blob/915104f77f45994af577a60fffe0d277cef82f29/config/sockets.js#L38)).  This config setting should be exposed in an environment variable so it can easily be set on the docker container.

This _only_ occurs when running multiple instances of Konga.

Copy of endless error until Chrome tab crashes:
```
Failed to load resource: the server responded with a status of 400 ()
sails.io.js:438  Failed to connect socket (possibly due to failed `beforeConnect` on server) Error: Error: xhr post error
    at e.d.onError (sails.io.js:14)
    at f.<anonymous> (sails.io.js:14)
    at f.d.emit (sails.io.js:14)
    at f.onError (sails.io.js:14)
    at sails.io.js:14
sails.io.js:438  ====================================
sails.io.js:438  Socket was disconnected from Sails.
sails.io.js:438  Usually, this is due to one of the following reasons:
 -> the server https://konga-test.realdomain.net was taken down
 -> your browser lost internet connectivity
```

**Comment by pantsel** [comment]
@mlehner616 , nice one. 
Something that is indeed needed and very easy to implement. 

A PR would be awesome if you really need the scaling part done fast (i reckon you're familiar with sailsjs).

If you need help on how to implement it, let me now and I'll be happy to point you to the right direction.

This is a low priority for me atm, cause when I get some time, I need to address more importand usability issues.

Cheers.
