### ISSUE TITLE
Improvement: Konga Oauth lacks private key info in any form

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#142]
Opinion: Konga as an Administration portal should really give full insight to the consumers and their payloads without need to invoke the Admin API directly. 

With Oauth we are lacking visibility into the client secret (by design? I can understand why in a way but its a pain point). I propose a solution that I think best so you don't display it out in the open:

![kongaoauth2](https://user-images.githubusercontent.com/31913027/33306820-0a3efcde-d3e2-11e7-8710-110e95161446.png)

So how about here we have an eyeball option in the table similar to API display that shows the raw Json (which would include the private key as a popup so in the event Admin does need to provide clients with their private key for some odd circumstance, they can do so without having to Curl the admin api and look at the json payload themselves. 

Thanks!
-Jeremy

**Comment by pantsel** [comment]
@jeremyjpj0916 , valid point.

Fixed on the latest commit.

**Comment by jeremyjpj0916** [comment]
Updated my code and can confirm the change works and looks great! Fast update, thanks mate.
