### ISSUE TITLE
Settings API without authentification

### ISSUE THREAD

**Issue by YoannMa** [pantsel/konga#144]
Hi, 

I found out that the `api/settings` endpoint isn't protected by authentication, so everyone can access to the slack endpoint.

Is this normal ?

Thanks

**Comment by pantsel** [comment]
Hi @YoannMa ,

thanks for the notice.

Theese settings started out as public, containing stuff like wether user signup should be enabled. The issue you posted was raised with the later integration of slack. And it is valid. I will need to either put slack settings in their own logic or somehow separate public from private settings.

This is a Todo.

**Comment by pantsel** [comment]
@YoannMa , this is fixed starting with Konga 0.11
