### ISSUE TITLE
Small Bug: API Version on Connections page does not change when Kong is upgraded.

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#146]
The auto detected connections kong version is static, so while you may upgrade your kong connection version, this page will not detect that and leaves it at the original version the detection code must have seen originally. Needs to do a quick-check when that page loads to get the latest version and compare to current and update it if needed.

**Comment by jeremyjpj0916** [comment]
To update this, it actually will auto update the number is you switch one admin api endpoint active from starred one back to it, aka unstar and then star it again. So it sort of auto updates? Just not in the context of doing the check without user intervention I suppose haha.

**Comment by pantsel** [comment]
@jeremyjpj0916 ,
As a temp workaround, the node version is updated if you disable-reenable it from the connections page.

**Comment by jeremyjpj0916** [comment]
Right yeah I had noticed that behavior, not too shabby :).

**Comment by pantsel** [comment]
@jeremyjpj0916 ,

this issue is addressed at [v0.10.2](https://github.com/pantsel/konga/releases/tag/0.10.2).

Feel free to reopen if things are not working as expected.

**Comment by jeremyjpj0916** [comment]
Glad to see you back in action bud!
