### ISSUE TITLE
strip_uri setting ignored when creating new API

### ISSUE THREAD

**Issue by marckhouzam** [pantsel/konga#147]
Using Konga 0.8.6

- go to API section
- press + ADD NEW API
- fill
    name: test
    Uris: /test
    Upstream URL: http://example.com
    --> Set Strip uri option to NO
    Click Submit API

The strip_uri setting is still set to YES. 
When I look at the network traffic sent after pressing "Submit API", I don't see any field for strip_uri in the message payload.

So, I have to disable stri_uri by hand in the main API page.

**Comment by pantsel** [comment]
Try updating konga to the latest version

**Comment by marckhouzam** [comment]
It works with 9.0.  Sorry for not noticing, I hadn't updated my docker image.

Thanks!
