### ISSUE TITLE
pantsel/konga:0.8.9 says it runs version 0.8.8

### ISSUE THREAD

**Issue by marckhouzam** [pantsel/konga#148]
Doing:
docker pull pantsel/konga:0.8.9 
docker run -p 1337:1337 pantsel/konga:0.8.9 

When connecting to localhost:1337, the GUI says it is running 0.8.8.

I don't know if it is the docker image that is wrong, or if Konga 0.8.9 actually has its version set to 0.8.8

If it's the docker image, maybe it should be replaced.

Thanks

**Comment by pantsel** [comment]
Wether thats the case or not, the current konga version is far ahead and theres no point of meddling with the past. You just need to upgrade.
