### ISSUE TITLE
database not created

### ISSUE THREAD

**Issue by classofoutcasts** [pantsel/konga#151]
I needed to create the konga_database manually in PostgreSQL before running `npm start` for the first time. Otherwise it spawns a heap of errors that 'konga_database' doesn't exist.
Unbuntu 16.04 LTS
PostgreSQL 9.5
NodeJS version 8.9.3
NPM version 5.6.0
Is this the intended way to install Konga or should the database be created automatically?

**Comment by lsalman** [comment]
Hi, 

First, you need to create a database for Konga and then run `npm start` in development mode to create tables and stuff.

> Note :

In case of MySQL, PostgresSQL or SQL Server adapters, you will need to start the app in development mode the first time.

npm start

Then kill the process and start Konga as you would in production mode. Konga will not create the database or tables in production mode.

local.js
`models: {
    connection: process.env.DB_ADAPTER || 'postgres',
  },
`
connections.js
`postgres: {
    adapter: 'sails-postgresql',
    host: process.env.DB_HOST || '10.10.10.10',
    user:  process.env.DB_USER || 'konga',
    password: process.env.DB_PASSWORD || 'passowrd,
    port: process.env.DB_PORT || 5432,
    database: process.env.DB_DATABASE ||'konga',
    //poolSize: process.env.DB_POOLSIZE || 10,
    ssl: process.env.DB_SSL ? true : false // If set, assume it's true
},`

**Comment by pantsel** [comment]
@classofoutcasts , Konga will create a PG database automatically when you start the app in development mode.

**Comment by classofoutcasts** [comment]
@pantsel In my case it doesn't.

**Comment by jeremyjpj0916** [comment]
I just tested DB creation when it does not exist(running latest version of konga). It works for me, I do not use DB_POOLSIZE param or DB_SSL though. I also was testing it on a mysql server, wonder if it might be Postgres specific.
