### ISSUE TITLE
[Highly Requested Feature] Api Lookup to yeild consumers who have access to it.

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#155]
Hey Pantsel,

I know we previously worked out a cool way to do Consumer -> API Lookup to tell what API's a given consumer has access too.

I have found a HUGE number of our API Providers would like a way in the API section to see all current consumers who have access to a given API (matching ACL group + Auth pattern). 
API -> Consumer lookup

So basically a reverse pattern of what we had before exposed under Consumer accounts but in Konga API section. Any way you could get some time to cook up magic like that on the API's page? Maybe another column with an eyeball and the raw json has every consumer name and id that is tied to it with the Column header saying Authorized Consumers on the APIs page? 

As always best wishes,
-Jeremy

**Comment by pantsel** [comment]
@jeremyjpj0916 , closing this for housekeeping. I think this is outdated due to the latest changes. Cheers.

**Comment by jeremyjpj0916** [comment]
yep you knocked this one out 👍 , thx.
