### ISSUE TITLE
Upstream targets are not appearing in Konga

### ISSUE THREAD

**Issue by DeanHyde** [pantsel/konga#161]
When adding an upstream target through Konga's UI, I'm getting 2 notifications, an unsuccessful "Method not allowed" and a successful "Target added".

When requesting the upstream's target through the Kong API, I can see that the target was added, however Konga does not list the newly added target.

**Comment by ermazi** [comment]
konga now not support 0.12.x. plz confirm your kong version

**Comment by infoloft** [comment]
@DeanHyde , what version of Kong are you using?

**Comment by DeanHyde** [comment]
My mistake, it's version 0.12.x. Almost everything else works fine so I assumed it supported 0.12.x.
