### ISSUE TITLE
Failed to add plugins for a specific api (without consumer)

### ISSUE THREAD

**Issue by thucnc** [pantsel/konga#164]
I'm using Kong Docker 0.9 and unable to add ip-restriction plugin to a specific api (with the same settings in this example https://getkong.org/plugins/ip-restriction/); but I made it work by calling the kong api directly by below script:
`curl -X POST http://kong:8001/apis/{api}/plugins \
    --data "name=ip-restriction" \
    --data "config.whitelist=54.13.21.1, 143.1.0.0/24"`

**Comment by pantsel** [comment]
@thucnc , Kong 0.9.0 is a very old version of Kong and may have lots of inconsistencies with the current version of Konga.

I would suggest to update Kong to 0.12.x.

As i'm stating on README.md :

Upgrade your Kong installations to v0.11.x so you can use Konga to it's full capacity. Support for older versions of Kong will be discontinued.
