### ISSUE TITLE
callback bug

### ISSUE THREAD

**Issue by Jackong** [pantsel/konga#178]
https://github.com/pantsel/konga/blob/58387e4bd4aaca661050ad6975d7a14eb2c0fa9e/api/hooks/load-db.js#L51

```js
// ...
else {
  return _cb();
}
```
it will cause:
> error: Error: The hook `load-db` is taking too long to load.*

**Comment by pantsel** [comment]
@Jackong ,
thanks for the notice. 

I'll fix it asap
