### ISSUE TITLE
Konga on Docker

### ISSUE THREAD

**Issue by sulthonzh** [pantsel/konga#185]
Hi, I got an error 

> Failed to connect to kong_test.
Make sure your active connection is valid and Kong is up and running.

I got an error after docker-compose down then "docker-compose up" again 

> version: '2.2'
> 
> services:
> 
>   kong-database:
>     image: postgres:9.4-alpine
>     container_name: kong-database
>     environment:
>       - POSTGRES_USER=kong
>       - POSTGRES_DB=kong
>     healthcheck:
>       test: "pg_isready -U kong && psql -d kong -U kong -c \"SELECT 1=1\""
>       interval: 10s
>       timeout: 5s
>       retries: 5
>   
>   kong-migration:
>     image: kong
>     container_name: kong-migration
>     depends_on:
>       kong-database:
>         condition: service_healthy
>     environment:
>       - KONG_DATABASE=postgres
>       - KONG_PG_HOST=kong-database
>     command: sh -c "kong migrations up && touch migrations_run && sleep 30"
>     healthcheck:
>       test: "if [[ -f migrations_run ]] ; then exit 0; else exit 1; fi"
>       interval: 10s
>       timeout: 5s
>       retries: 5
> 
>   kong:
>     image: kong
>     container_name: kong
>     depends_on:
>       kong-migration:
>         condition: service_healthy
>     healthcheck:
>       test: "curl localhost:8001"
>       interval: 10s
>       timeout: 5s
>       retries: 5
>     environment:
>       - KONG_DATABASE=postgres
>       - KONG_PG_HOST=kong-database
>       - KONG_ADMIN_LISTEN=0.0.0.0:8001
>     ports:
>       - 8001:8001
>       - 8000:8000
> 
>   konga:
>     image: pantsel/konga
>     container_name: konga
>     ports:
>       - 1337:1337
>     environment:
>       - NODE_ENV=development
> 

after that cannot create new connection, 

different version when first create connection(0.12.x) on dashboard and /connections > new connection (0.10.x)

**Comment by pantsel** [comment]
@sulthonzh,
what version of Kong and Konga are using?

**Comment by sulthonzh** [comment]
@pantsel latest version from docker hub like docker compose, but (on first create at dashboard i see 0.2.x and when create from /connection (0.10.x))

**Comment by pantsel** [comment]
Are you sure the the Kongs Admin api is accessible from the machine Konga is running?

**Comment by tomkerkhove** [comment]
It's probably me but I have the same issue - Container can ping to kong:8001, but can't connect. Am I missing something?

**Comment by pantsel** [comment]
@tomkerkhove , can you curl from konga container to kong:8001? ]
What is the response?

**Comment by tomkerkhove** [comment]
@pantsel Can't use Curl nor apt-get since it's not in the image but you can ignore my comment. I'll just use the API directly. Thank you anyway!

**Comment by pantsel** [comment]
Closing this due to incactivity

**Comment by AlexandreLage** [comment]
I also suffered from this pain.

But I guess, I just needed to logout and login again on Konga.

Any thoughts on this?

Thank you for this nice dashboard.

**Comment by bytebybyte** [comment]
> I also suffered from this pain.
> 
> But I guess, I just needed to logout and login again on Konga.
> 
> Any thoughts on this?
> 
> Thank you for this nice dashboard.

Thanks @AlexandreLage. You're a life saver!
