### ISSUE TITLE
angular not defined.   

### ISSUE THREAD

**Issue by slimm609** [pantsel/konga#186]
production.min.js?r=0.10.2:1 Uncaught ReferenceError: angular is not defined
    at production.min.js?r=0.10.2:1
    at production.min.js?r=0.10.2:1
(anonymous) @ production.min.js?r=0.10.2:1
(anonymous) @ production.min.js?r=0.10.2:1
(index):128 Uncaught ReferenceError: angular is not defined
    at (index):128
(anonymous) @ (index):128
sails.io.js:438 

running the latest release in docker throws and error that angular is not defined.  (0.10.2)

The page is showing complete blank

angular is showing in the bower_components folder and there are no errors during npm install 

running node 8.9.4

**Comment by pantsel** [comment]
[https://github.com/pantsel/konga#faq](https://github.com/pantsel/konga#faq)

**Comment by slimm609** [comment]
`npm run bower-deps`

i added this after npm install in the docker build and tried running it by connecting to the running container and I am still getting the error

**Comment by pantsel** [comment]
This error is pretty standard. 

Do you have the ``assets/bower_components`` folder in your project?
If not, the bower dependencies are not installed.
Try a simple ``bower install`` and see what happens.

Are you are trying to build a docker image from source?

**Comment by slimm609** [comment]
building from the release because kong is on the same image so it has access to the admin api without exposing

**Comment by slimm609** [comment]
I have a /app bower_components folder but not an assets/bower_components

**Comment by pantsel** [comment]
do you have a .bowercc file? What are its contents?

**Comment by slimm609** [comment]
there is no .bowercc file

**Comment by pantsel** [comment]
Then your source code is not complete. Cross check it with Kongas source code from the repo

**Comment by slimm609** [comment]
testing now.   I was missing the `.` files

**Comment by pantsel** [comment]
@slimm609 ,

any news?

**Comment by slimm609** [comment]
still running into an issue but comparing to make sure that all the code is there.

**Comment by slimm609** [comment]
Its resolved.   Thanks for your help!

**Comment by trungdt705** [comment]
<img width="643" alt="Screen Shot 2019-07-30 at 6 30 58 PM" src="https://user-images.githubusercontent.com/34698474/62125748-3574ee80-b2f8-11e9-8d98-3067512a4353.png">
i have assets/bower_components folder in your project but i still get errors in above image.

**Comment by dougstefe** [comment]
Hi friends!
My problem was solved using: `bower install --allow-root`
For installing as root
