### ISSUE TITLE
need upstream passive health check

### ISSUE THREAD

**Issue by ermazi** [pantsel/konga#187]
now konga 10.2 doesnt support passive health check configuration.

**Comment by pantsel** [comment]
[v0.10.3](https://github.com/pantsel/konga/releases/tag/0.10.3) is just released and addresses this issue.

Please, do check it out and see if everything now works as expected.

Thanks for the contribution.

**Comment by ermazi** [comment]
ty.

**Comment by ermazi** [comment]
@pantsel hi, i have git pull the lastest code with version 0.10.3 but i cannot find passive health check entry.

**Comment by pantsel** [comment]
@ermazi ,
try hard refreshing (CTRL+F5) the page in case the browser cache has not refreshed.

The passive hc inputs are in place.

![https://ibb.co/bBJqHn](https://image.ibb.co/mMsviS/screencapture_localhost_1337_1520490157273.png)

**Comment by ermazi** [comment]
git pull && npm i
is there anything else i need do?

**Comment by pantsel** [comment]
1. Open Konga in your browser
2. Make sure that the version on the lower left side of the screen says 0.10.3
3. Hard refresh the page (press CTRL+F5 if you're on windows or cmd + shift +F5 if you're on mac). Alternatively, clear your browser's cache and refresh the page. 
4. Try to create an upstream. You should see the fields depicted above added in the form.

**Comment by ermazi** [comment]
![tim 20180308152921](https://user-images.githubusercontent.com/23275699/37138579-8d8329a6-22e5-11e8-969e-a2b5c510a1b5.png)

i was pull code directly, not download package that you pre-release

**Comment by pantsel** [comment]
The passive health checks should be at the bottom of the form.

Can you clear your browsers cache and post an image again scrolling all the way down to the bottom of the form?.

**Comment by Ligenmt** [comment]
I met the same thing... 
I‘ve updated to 0.10.3 and cannot use passive configurations...  
![image](https://user-images.githubusercontent.com/11540527/37139041-55fda13a-22e7-11e8-83b7-7a967635f113.png)

**Comment by pantsel** [comment]
Guys, this is a caching issue.

I just made some modifications so it is more automatic.

Pull the new version [0.10.4](https://github.com/pantsel/konga/releases/tag/0.10.4).

Waiting for feedback.

**Comment by ermazi** [comment]
**Now Success**

Ive test it.

i. if i just pull in place, version changed but passive hc items cannot show up
ii. if i reinstall konga completely from head, passive hc show up.

i dont know why.

thanks for your help.

**Comment by ermazi** [comment]
em, now i cannot see passive health status code or unhealth status code configuration..
for example, default unheath status code is 429,500,503, but 404, 502, 504 or some custom status code also need to failover.

**Comment by pantsel** [comment]
Will check it out

**Comment by pantsel** [comment]
@ermazi ,

Pull again and check it out man.
There was lots of stuff missing from that PR.

It should be v0.10.15

**Comment by ermazi** [comment]
thanks.

**Comment by ermazi** [comment]
i have no question, close it. thanks again.

**Comment by Ligenmt** [comment]
nice 👍
