### ISSUE TITLE
Support new API routing 

### ISSUE THREAD

**Issue by pouledodue** [pantsel/konga#19]
Kong 0.10rc1 has new API routing features
Konga is currently unusable 

https://github.com/Mashape/kong/pull/1970

https://github.com/Mashape/kong/releases/tag/0.10.0rc1

**Comment by pantsel** [comment]
The  0.10.x compatibility is underway but i cannot guarantee a release date.

There are a number of changes that need to be made in order to maintain backwards compatibility for Konga.

**Comment by suclogger** [comment]
@pantsel 
Maybe we can give up backwards compatibility, just release a new version to adapt kong 0.10?

**Comment by pantsel** [comment]
After the new release https://github.com/pantsel/konga/releases/tag/v0.5.0, this is my next priority.

**Comment by pantsel** [comment]
A release compatible to Kong 0.10.x API routing is published
