### ISSUE TITLE
Konga Dashboard on SSL

### ISSUE THREAD

**Issue by sanketgandhi** [pantsel/konga#190]
Konga dashboard support SSL? On console, it shows http://localhost:1338.
If I want to run this on https then is there any way to do it?
Or am I missing documentation?
Thanks

**Comment by pantsel** [comment]
@sanketgandhi , even thought sailsjs, the framework Konga is build upon, supports direct SSL configuration ([https://stackoverflow.com/questions/21612738/sails-js-http-https#34337373](https://stackoverflow.com/questions/21612738/sails-js-http-https#34337373)), Konga does not expose this configuration via env vars for the time being.

If you want to use SSL, you can simply put Konga behind any web server (nginx, apache ...), handle the creds there and proxy the requests to Konga internally. This is the advised way.

If you wan to use Konga as a standalone web server, you will need to configure it yourself and build from source, as stated at the above link.

**Comment by sanketgandhi** [comment]
Thanks for the information @pantsel 
Using NGINX reverse proxy it will surely work. But I was looking for the standalone web server. Are there any chances that we will have configuration on Konga itself?

Thanks

**Comment by sanketgandhi** [comment]
Thanks. I look forward to it.
