### ISSUE TITLE
v10.5 cannot add upstreams for kong version 0.11.x

### ISSUE THREAD

**Issue by ermazi** [pantsel/konga#191]
v10.5 cannot add upstreams for kong version 0.11.x

when i click submit upstream button, no response.

**Comment by Ligenmt** [comment]
met the same problem... = = i cant create new upstreams

**Comment by pantsel** [comment]
regression issue. 
Check the new commit. 0.10.6

**Comment by ermazi** [comment]
angular.js?r=0.10.6:14199 AddUpstreamModalController:created upstream error Object
(anonymous) @ angular.js?r=0.10.6:14199

**Comment by pantsel** [comment]
can you  expand the data obj so we can see what it?

**Comment by ermazi** [comment]
"hash_on is an unknown field"

**Comment by pantsel** [comment]
yes, it makes sense.
`hash_on` as a field is not introduced in kong 0.11.x

i will have to check the version there.

I'll fix it and keep you notified.

**Comment by ermazi** [comment]
i have no idea how to upgrade several kong nodes from 0.11.x to 0.12.x meanwhile.
i need a lot of time to test kong verison upgrade.

**Comment by pantsel** [comment]
pull the latest commit and see what happens.

(I'm making these changes on the fly so i cannot properly test them)

**Comment by ermazi** [comment]
ok, i will test it later.

**Comment by ermazi** [comment]
it works.
thanks
