### ISSUE TITLE
Hi,when could konga support kong version 0.13

### ISSUE THREAD

**Issue by ermazi** [pantsel/konga#197]
expecting for that ：D

**Comment by PauloGDPeixoto** [comment]
I'm using the "latest" docker image and it's connecting well to my 0.13 clusters.

**Comment by pantsel** [comment]
Konga is working with no probs with Kong 0.13.x.

But, it doesn't support Kong's new cool features like `services` & `routes` .

Still working with `apis`.

Support for  `services` & `routes` is underway, but I can't give you a strict deadline.

**Comment by grillorafael** [comment]
Great to hear that @pantsel 

If I can help with anything please let me know

**Comment by jeremyjpj0916** [comment]
Looking forward to services and routes logic added as well, the flow would be interesting, maybe a page where you create a service, and then from the list of services you click into one of them and then you can view existing routes on that service or add plugins to service or add routes to service? Doing it through curl right now is brutalllll, need me some Konga 💯 !

**Comment by gradasso** [comment]
news?

**Comment by GabrielAraujo** [comment]
Hey @pantsel is there a branch with the current development for supporting latest Kong? We could help =D

**Comment by jeremyjpj0916** [comment]
https://github.com/pantsel/konga/tree/next (initial services/routes support!)

**Comment by pantsel** [comment]
Starting from v0.11+, Konga supports services and routes. 
Closing this issue due to housekeeping.
Feel free to reopen if needed.
