### ISSUE TITLE
Docker image - error A hook (`orm`) failed to load!

### ISSUE THREAD

**Issue by augustoferronato** [pantsel/konga#201]
Hello,
I'm trying to up a konga in a docker container (i already have in my homolog enviroment), now i'm creating a new enviroment, i receive this error:

I already check the env config

i try the images
latest
next
0.10.4

All have the same error.

> 18/04/2018 15:38:39A hook (`orm`) failed to load!
> 18/04/2018 15:38:39RangeError: "port" option should be >= 0 and < 65536: NaN
> 18/04/2018 15:38:39    at lookupAndConnect (net.js:964:13)
> 18/04/2018 15:38:39    at Socket.connect (net.js:939:5)
> 18/04/2018 15:38:39    at Connection.connect (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:42:17)
> 18/04/2018 15:38:39    at Client.connect (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:47:9)
> 18/04/2018 15:38:39    at Object.create (/app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:30:18)
> 18/04/2018 15:38:39    at createResource (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:261:13)
> 18/04/2018 15:38:39    at dispense (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:253:9)
> 18/04/2018 15:38:39    at Object.me.acquire (/app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:319:5)
> 18/04/2018 15:38:39    at Object.pool.connect (/app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:78:14)
> 18/04/2018 15:38:39    at PG.connect (/app/node_modules/sails-postgresql/node_modules/pg/lib/index.js:49:8)
> 18/04/2018 15:38:39    at spawnConnection (/app/node_modules/sails-postgresql/lib/adapter.js:1180:8)
> 18/04/2018 15:38:39    at Object.describe (/app/node_modules/sails-postgresql/lib/adapter.js:155:7)
> 18/04/2018 15:38:39    at /app/node_modules/sails-postgresql/lib/adapter.js:117:14
> 18/04/2018 15:38:39    at /app/node_modules/sails-postgresql/node_modules/async/lib/async.js:356:13
> 18/04/2018 15:38:39    at async.forEachOf.async.eachOf (/app/node_modules/sails-postgresql/node_modules/async/lib/async.js:233:13)
> 18/04/2018 15:38:39    at _asyncMap (/app/node_modules/sails-postgresql/node_modules/async/lib/async.js:355:9)
> 18/04/2018 15:38:39    at Object.map (/app/node_modules/sails-postgresql/node_modules/async/lib/async.js:337:20)
> 18/04/2018 15:38:39    at Object.registerConnection (/app/node_modules/sails-postgresql/lib/adapter.js:116:13)
> 18/04/2018 15:38:39    at /app/node_modules/waterline/lib/waterline.js:216:29
> 18/04/2018 15:38:39    at /app/node_modules/waterline/node_modules/async/lib/async.js:181:20
> 18/04/2018 15:38:39    at Object.async.forEachOf.async.eachOf (/app/node_modules/waterline/node_modules/async/lib/async.js:233:13)
> 18/04/2018 15:38:39    at Object.async.forEach.async.each (/app/node_modules/waterline/node_modules/async/lib/async.js:209:22)
> 18/04/2018 15:38:39    at Array.async.auto.registerConnections (/app/node_modules/waterline/lib/waterline.js:189:13)
> 18/04/2018 15:38:39    at /app/node_modules/waterline/node_modules/async/lib/async.js:596:38
> 18/04/2018 15:38:39    at _arrayEach (/app/node_modules/waterline/node_modules/async/lib/async.js:85:13)
> 18/04/2018 15:38:39    at Object.async.auto (/app/node_modules/waterline/node_modules/async/lib/async.js:554:9)
> 18/04/2018 15:38:39    at Waterline.initialize (/app/node_modules/waterline/lib/waterline.js:136:9)
> 18/04/2018 15:38:39    at buildWaterlineOntology (/app/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:45:19)
> 18/04/2018 15:38:39    at Array.async.auto._buildOntology (/app/node_modules/sails-hook-orm/lib/initialize.js:388:7)
> 18/04/2018 15:38:39    at listener (/app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:605:42)
> 18/04/2018 15:38:39    at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
> 18/04/2018 15:38:39    at _arrayEach (/app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
> 18/04/2018 15:38:39    at Immediate.taskComplete (/app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
> 18/04/2018 15:38:39    at tryOnImmediate (timers.js:645:5)

Thanks for your help

**Comment by pantsel** [comment]
Hello @augustoferronato ,
try setting the env variable `KONGA_HOOK_TIMEOUT ` to 120000.
In some cases deoending on the machine etc the sails hooks may take longer to load.

**Comment by raphaelLacerda** [comment]
i'm still having this error when deploying konga on Kubernetes

Any help?


`
A hook (`orm`) failed to load!
RangeError: "port" option should be >= 0 and < 65536: NaN
`
`
containers:
      - env:
        - name: KONGA_HOOK_TIMEOUT
          value: "120000"
`
