### ISSUE TITLE
upstreams health checks config update failed

### ISSUE THREAD

**Issue by ms2008** [pantsel/konga#202]
healthy http status should be encode as `[]int` this form, but KONGA encode as `[]string`

![figure](https://user-images.githubusercontent.com/3797918/39292374-8f0705f0-4968-11e8-9f2c-d352faec0d94.png)
![figure1](https://user-images.githubusercontent.com/3797918/39292375-911130f0-4968-11e8-8000-b48a20c5777f.png)

**Comment by ms2008** [comment]
I just have few knowledge about frontend programming, and have no the level to fix this issue yet. :-(

**Comment by pantsel** [comment]
No probs, i will fix it on the next release

**Comment by pantsel** [comment]
@ms2008, the issue is fixed on the `next` branch and will be available on the next release
