### ISSUE TITLE
Konga not able to connect to MongoDB

### ISSUE THREAD

**Issue by hamid2013** [pantsel/konga#203]
Hello ,

We have a hosted solution for the MongoDB, when i try to provide the all the info. Konga is not able to connect to MongoDB.

Can you share an example of it.

**Comment by hamid2013** [comment]
Thanks @pantsel for the response.

I have tried that, but that was not working.

The error message says the Database is not up, which is not the case. 

I am using the hosted MongoDB solution. so instead of passing DB_HOST can we pass DB_HOST_URI.

**Comment by pantsel** [comment]
As of Konga 0.11+ , you can only pass DB_URI.
