### ISSUE TITLE
After a while, Konga often crash！！！

### ISSUE THREAD

**Issue by taotao2014** [pantsel/konga#206]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:109:13)
    at Socket.<anonymous> (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:102:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

help !!!!!!!!!!!

**Comment by alxndr13** [comment]
I am also experiencing this. Using the docker image on a Kubernetes cluster it does crash around 200 times a day.

**Comment by pantsel** [comment]
@taotao2014 , the error says that the mysql server forcefully closed the connection. I cannot see how Konga could be responsible for that. 

@alexforever86 . The exit code 137 doesn't say anything by itself. 
Some extra information other than the approximate times/day you're facing the issue could be helpful.

For example, what's your setup? 
Is Konga integrated with an external database? 
Have you tried running Konga without an external db integration? The problem persists?
Are you sure there's not something on your setup that's killing the process?

**Comment by taotao2014** [comment]
@pantsel ,thank you, resolved, the need to change the environment into production, can not be used to develop, if you use development, it will be a period of time crash (in docker, database is mysql)

**Comment by alexforever86** [comment]
@alxndr13 They tagged me instead of tagging you.

**Comment by alxndr13** [comment]
@alexforever86 thanks 😄 @taotao2014 I will try your approach, thanks for the info @pantsel I only can test that next week, I'll keep you updated.

**Comment by alxndr13** [comment]
@pantsel Sorry for the late reply, i just tested it. Now im facing issue #151 using Postgresql.

**Comment by pantsel** [comment]
@alxndr13 , have you tried to create the `konga_database ` manually and then start Konga in dev mode?

How are you running Konga? From the docker image or from source?

In case of docker image, can you post the `docker run` command you're using?

In case your trying to install Konga from source. what is your configuration in `/config/local.js`?

The server logs would also be helpful.

**Comment by pantsel** [comment]
Closing this due to innactivity. Feel free to reopen if needed,

**Comment by alxndr13** [comment]
Sorry for the late reply, the trick using develop env only for the first start and then a restart with the prod environment fixed it. 😊  Maybe this is useful for some googler later on. 👍
