### ISSUE TITLE
Deprecated /API endpoint. Now requires "Services" and "Routes" 

### ISSUE THREAD

**Issue by btwq** [pantsel/konga#207]
As of 0.13.x, the "/api" endpoint is deprecated. Kong now uses "Services" and "Routes" 

Any plans to support these? They are currently not available to view or setup on left side menu in Konga admin. 

<img width="1191" alt="screen shot 2018-05-13 at 5 56 32 pm" src="https://user-images.githubusercontent.com/14045909/39965144-101c6768-56d7-11e8-853f-016c4e913cdd.png">

**Comment by rantonana** [comment]
+1

**Comment by thegreatanon** [comment]
I would also like this.
See also #197

**Comment by rcapraro** [comment]
+1

**Comment by ILoveYouDrZaius** [comment]
+1.
Waiting feature.

**Comment by jeremyjpj0916** [comment]
https://github.com/pantsel/konga/tree/next (initial services/routes support!)

**Comment by pantsel** [comment]
Konga 0.11+ is here and offers that functionallity.
