### ISSUE TITLE
Not able to update Request Transformer 

### ISSUE THREAD

**Issue by btwq** [pantsel/konga#208]
* Able to create a Request Transformer in Consumer > APIs > Add Plugins > Request Transformer.
* Failed to assign values to "replace", "remove", "add", "rename". See screenshots below. After click on Submit Changes, these values remain blank. 

<img width="936" alt="screen shot 2018-05-13 at 5 57 45 pm" src="https://user-images.githubusercontent.com/14045909/39965160-440d87c8-56d7-11e8-805f-11fce70f13e7.png">

<img width="647" alt="screen shot 2018-05-13 at 5 57 53 pm" src="https://user-images.githubusercontent.com/14045909/39965161-443b0bb2-56d7-11e8-8a1c-de300b1cb4e7.png">

**Comment by tenyo** [comment]
I've run into the same issue in Konga 0.10.6

**Comment by Niradnik** [comment]
Actually You have to write your thing then press enter and then hit the save button.
As written here https://github.com/pantsel/konga/issues/85

**Comment by pantsel** [comment]
Closing this as it seems to be resolved
