### ISSUE TITLE
Support for mongo replicaset

### ISSUE THREAD

**Issue by michaelkrog** [pantsel/konga#212]
It is not possible to connect to multiple hosts in a replicaset.

As I understand it shoud be as simple as allowing to set the mongo url directly.
http://sailsit.com/2017/11/sails-mongodb-replicaset-configuration/

**Comment by pantsel** [comment]
@michaelkrog , starting with Konga 0.11+. You now can use the <code>DB_URI</code> env var.
https://github.com/pantsel/konga#running-konga
