### ISSUE TITLE
The API Entity is deprecated since Kong 0.13.0.

### ISSUE THREAD

**Issue by WanZhaoJun** [pantsel/konga#214]

**Comment by PauloGDPeixoto** [comment]
#207

**Comment by jeremyjpj0916** [comment]
https://github.com/pantsel/konga/tree/next (initial services/routes support!)

**Comment by pantsel** [comment]
Konga 0.11+ introduces services and routes support.

Cheers.

**Comment by grillorafael** [comment]
@pantsel any plan on releasing a new docker image?

**Comment by PauloGDPeixoto** [comment]
pantsel/konga:next is already updated and working well!

**Comment by pantsel** [comment]
@grillorafael Pantsel/konga:next has all the new features as well as pantsel/konga:latest.
Im using next as we speak. I just want to give it a day or 2 just in case an issue iccurs so i can include the fix on the release.

**Comment by grillorafael** [comment]
@pantsel :+1: I'll give it a try ton `next`
