### ISSUE TITLE
kong_admin_url with '/' at the finish

### ISSUE THREAD

**Issue by ILoveYouDrZaius** [pantsel/konga#215]
Konga doesn't connect witch Kong when you write the kong_admin_url at the connection between Kong and Konga with a finish slash (http://localhost:8000/admin-api/), but it does when you write the same kong_admin_url without slash (http://localhost:8000/admin-api).

Regards.

**Comment by pantsel** [comment]
Problem solved then :)

**Comment by ILoveYouDrZaius** [comment]
Thank you and congratulations for the project!
