### ISSUE TITLE
create route reqest params missing. docker release tag: next

### ISSUE THREAD

**Issue by davidqhr** [pantsel/konga#216]
## What I do ?

Create a route for a service

## What's happened?
![image](https://user-images.githubusercontent.com/5846959/41191534-9fa2eb62-6c23-11e8-8288-7ef603f367ce.png)

## More info

params is missing in request payload

![image](https://user-images.githubusercontent.com/5846959/41191537-b49cba7a-6c23-11e8-8ef7-5ca43d675d20.png)

## Version
Docker tag: next

**Comment by pantsel** [comment]
@davidqhr, simply push enter after avery host, path, method or protocol you type. Since they are arrays,
they are handled by a chip component.

My bad, it's not properly documented. I will include it in the next update.

Cheers

**Comment by davidqhr** [comment]
Maybe we can commit the content in the input as a tag on blur event. :D

**Comment by pantsel** [comment]
Nice idea, i'll see what i can do.

**Comment by p0larbeer** [comment]
it still doesn't work
![screenshot from 2018-06-11 23-37-17](https://user-images.githubusercontent.com/1612422/41255816-79415f0e-6dd0-11e8-95af-ededb8862200.png)

**Comment by pantsel** [comment]
@p0larbeer , you havent pressed `enter` to register the value of your paths as stated on the blue box

**Comment by p0larbeer** [comment]
thanks! it works
