### ISSUE TITLE
Delete api should drop the alert automatically.

### ISSUE THREAD

**Issue by davidqhr** [pantsel/konga#217]
## What I Do

Created an api, and add hc alert for it. I can receive alert in slack channel when the api is down.Then I delete the api directly.

## What's happened?

I still receive the alert.

## What I expected?

The alert should be destroyed.

Thanks a lot!

**Comment by pantsel** [comment]
@davidqhr , this soundls like a bug. I'll investigate. In the meantime, the only thing you can do is to remove the healthcheck manually from konga's db.
