### ISSUE TITLE
Service Edit Failed Konga 0.11

### ISSUE THREAD

**Issue by jeremyjpj0916** [pantsel/konga#219]
Editing an existing Service (it has a route on it too, not sure if that matters) seems to fail. Maybe not using PATCH or something?

![image](https://user-images.githubusercontent.com/31913027/41317139-58815e44-6e62-11e8-9ab7-be1978ece70b.png)

**Comment by pantsel** [comment]
That's strange,
![screencapture-139-59-145-231-1337-2018-06-13-00_08_14](https://user-images.githubusercontent.com/5519873/41317455-eb5cf990-6e9d-11e8-8569-fcedf0987b23.png)

it's working for me

**Comment by jeremyjpj0916** [comment]
Upgraded to latest master and still facing issues. let me see if I can export my routes/services data in non-prod and give you a sample to import THEN try to edit that in konga 👍  . Not sure what else to do. We are running same Kong version.

**Comment by jeremyjpj0916** [comment]
Just to update this issue to speed its due to different underlying Kong DB's.

**Comment by jkumar-roambee** [comment]
+1

**Comment by pantsel** [comment]
A temporary fix is up on the `next` branch. You can use that branch with no probs,  while waiting an update from Kong's team.

**Comment by pantsel** [comment]
Closing this. For now, Konga works with the monkey patch.  
Kong fixed it on this commit https://github.com/Kong/kong/pull/3559.
