### ISSUE TITLE
DataModel.load() failed - status: 500

### ISSUE THREAD

**Issue by scbsoccer** [pantsel/konga#225]
I use kong, konga, docker and Cassandra database in my project. First, in keyspace kong, I insert 8 records into table kong.apis using INSERT queries. Next, I access http://localhost:1337/#!/apis, and see a list of apis successfully because the table kong.apis contain only 8 records. ![initial_table_with_8_rows_inserted_using_insert_queries](https://user-images.githubusercontent.com/20588942/41697789-b0644ade-7544-11e8-8585-b8e71380bdfa.png) After that, I insert extra 1 record into kong.apis also using insert query, and then I access http://localhost:1337/#!/apis again but I see no apis. 
![extra_1_rows_inserted_using_insert_query](https://user-images.githubusercontent.com/20588942/41697787-b033e5ec-7544-11e8-9cf3-b3a1cde29852.png)
[error_with_9_rows_inserted.txt](https://github.com/pantsel/konga/files/2121995/error_with_9_rows_inserted.txt)
If I add a new api through clicking on "ADD NEW API" button on http://localhost:1337/#!/apis, it is successful.
In general, once there are more than 8 records added into kong.apis using INSERT query, and reload the page, error happens and no api display.

**Comment by pantsel** [comment]
@scbsoccer , that is strange. What happens if you try to fetch the apis directly from Kongs admin API via postman or any other REST client?

**Comment by pantsel** [comment]
Closing as outdated. Feel free to reopen if needed.
