### ISSUE TITLE
Cannot import Services and Routes from snapshot

### ISSUE THREAD

**Issue by minhpq331** [pantsel/konga#229]
After taking snapshot include services and routes, I can't restore it using KongA. Importing services and routes (introduced in kong 0.13.1) may not be implemented.
Kong version: 0.13.1
KongA version: 0.11.2 (latest tag)

**Comment by minhpq331** [comment]
Update: I can import services now but the following error showed up when importing routes:
```js
{ fields: { service: { id: 'a0e72b4a-5c51-4618-a62e-e7484bedc9ec' } },
  name: 'foreign key violation',
  code: 4,
  message: 'the foreign key \'{id="a0e72b4a-5c51-4618-a62e-e7484bedc9ec"}\' does not reference an existing \'services\' entity.' }
```
Also check for SnapshotController.js:79, the current orderedEntities object is missing `services` and `routes`.

**Comment by pantsel** [comment]
@minhpq331 , are you using Cassandra with Kong?

**Comment by minhpq331** [comment]
@pantsel I'm using PostgreSQL with Kong. Can't wait to see the fix. 
Thank you very much :dancing_men:

**Comment by pantsel** [comment]
@minhpq331 , I've done some work on the  next branch regarding services and routes importing
https://github.com/pantsel/konga/tree/next

If you want, you could test it out and give me some feedback.

Cheers.

**Comment by minhpq331** [comment]
Wonderful! It works well for me. 
Thank you.

**Comment by pantsel** [comment]
Neat, I will publish a new version on the master branch the coming days.

Feel free to reopen if you stumble across a glitch.

**Comment by xkr47** [comment]
FYI it might help to break down the import into multiple stages, for example first import everything except routes and services, then import again, this time only select routes and services.
