### ISSUE TITLE
When changing kong nodes / adding new onces consumers are not listed

### ISSUE THREAD

**Issue by bakstad** [pantsel/konga#23]
All consumers are listed after first addition of kong nodes, but when I add another one or change between multiple nearly every consumer is missing.

**Comment by pantsel** [comment]
If all Kong nodes are viewing the same db, you will need to sync the consumers for each node from Konga.
Konga queries the consumers from it's own db where they're saved in relation to the node they where created.

This will change in the future but for now this is how things work.

If each Kong node is a separate instance with its own db, then  another node's consumers are not supposed to be shown.

**Comment by bakstad** [comment]
Oh ok. That I don't want. I want Kong to be the owner of the consumers.

So if I sync I will loose my consumers because I have none in Konga except the default ones?

**Comment by pantsel** [comment]
Syncing only affects consumers on Kongas db. You will not loose any consumers in Kongs db.

Kong's consumers that don't exists in Konga's database will be imported
while Konga's consumers that don't exist in Kong's database will be removed (from Konga's db)

**Comment by bakstad** [comment]
Hm ok. Syncing did not help. In the log from Konga i see all my consumers, but only a few shows up in the GUI.

**Comment by pantsel** [comment]
Can you maybe post a screenshot of the GUI and logs so i can understand what's going on? It seems to be working on my end.

**Comment by pantsel** [comment]
Hi @bakstad ,
check out the new release and please report back if this issue has been fixed so we can close it.
Thnx.

**Comment by bakstad** [comment]
Hi,

Great job on the 0.5.x! This seems to be fixed now, Thanks.
