### ISSUE TITLE
Feature Request: LDAP Integration

### ISSUE THREAD

**Issue by ammmze** [pantsel/konga#230]
Would love to see support for integrating with LDAP for authentication. Any major technical hurdles that would prevent being able to do that?

**Comment by pantsel** [comment]
@ammmze , I know for fact the guys from spotx have implemented LDAP in this fork
https://github.com/spotx/konga

You can check it out.

No  technical hurdles at all.

It's in my plans to do it as well at some point but I cannot guarantee an exact timeframe.
