### ISSUE TITLE
Can't create routes

### ISSUE THREAD

**Issue by guyuecode** [pantsel/konga#235]
When I create a route, It pops up a hint .
![konga_bug](https://user-images.githubusercontent.com/16371078/42619338-5d8266e6-85ea-11e8-88f6-a98850e81b8d.png)

Thinks.

**Comment by pantsel** [comment]
@guyuecode ,
do what it says on the blue box in your screenshot.

Cheers

**Comment by guyuecode** [comment]
Thanks.
I made a stupid mistake
