### ISSUE TITLE
Strip Path Enabled on creation of Route

### ISSUE THREAD

**Issue by rnoons** [pantsel/konga#236]
When creating a new route in Konga 11.2 if you toggle the 'Strip Path' to NO, upon submitting changes the 'Strip Path' setting will be submitted as YES (Default). If  you then modify the existing route and set the toggle back to NO the settings save correctly. There does not appear to be a problem with the "Preserve Host" toggle just below it.

**Comment by pantsel** [comment]
@rnoons , thanks for the heads up.

Will be fixed in the upcoming version
