### ISSUE TITLE
Is konga compatible with Kong 0.14.0?

### ISSUE THREAD

**Issue by TFarla** [pantsel/konga#239]
Kong 0.14.0 has been released and it introduced a couple [changes in the admin api](https://github.com/Kong/kong/blob/master/UPGRADE.md#admin-api).

Upgrade path: https://github.com/Kong/kong/blob/master/UPGRADE.md#upgrade-to-014x

**Comment by pantsel** [comment]
@TFarla , the [next](https://github.com/pantsel/konga/tree/next) branch, which holds Konga 0.12.0-rc2 is fully compatible with Kong 0.14x and also introduces some new cool features.

If you're using docker, pull it via `pantsel/konga:next`.

I'm still testing it and so far everything seems to be working fine. I'll be moving it to the `master` branch soon.
