### ISSUE TITLE
New Install konga from 0.11 to 0.12

### ISSUE THREAD

**Issue by kakarooky** [pantsel/konga#244]
Hi.
Kong Version: 0.14.0
Previous Konga version : 0.11.x
New Install konga version: 0.12

I used Konga ver 0.11.x however i read that "Konga 0.12+ is fully compatible with Kong 0.14+"

so I installed to konga0.12 version however I couldn't see nothing about admin GUI

$ cd ~/konga/; npm start
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.12.14            |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/root/konga`
info: To see your app, visit http://localhost:1338
info: To shut down Sails, press <CTRL> + C at any time.

debug: -------------------------------------------------------
debug: :: Mon Jul 23 2018 18:26:07 GMT+0900 (KST)

debug: Environment : development
debug: Port        : 1338
-----------------------------------
Chrome : http://ip:1338/#!/login  ==> but result is all white

-----------------------------
~/konga/config/local.js ==> ver 0.11.x and ver 0.12 are same local.js

module.exports = {
  /**
   * The default fallback URL to Kong's admin API.
   */
  kong_admin_url : process.env.KONG_ADMIN_URL || 'http://127.0.0.1:8001',
  connections: {
  },
  models: {
    connection: process.env.DB_ADAPTER || 'localDiskDb',
  },
  session: {
    secret: '' // Add your own SECRET string here
  },
  port: 1338,
  environment: 'development',
  log: {
    level: 'info'
  }
};

Any Idea?

**Comment by pantsel** [comment]
@kakarooky . Open your javascript console on the browser. Do you see any errors? If yes please post then here.

**Comment by kakarooky** [comment]
Dear pantsel

$ cd ~/konga; npm run bower-deps
and Updated konga.db 

Run very well.
I'll wish your luck.
 
Thank you

**Comment by pantsel** [comment]
Cheers man! Glad to be of help.
