### ISSUE TITLE
SSL support 

### ISSUE THREAD

**Issue by frannnnk** [pantsel/konga#245]
Is there a way to let Konga support SSL? say https://www.konga.url:1337/

**Comment by pantsel** [comment]
@frannnnk, This can be easily achieved by using a load balancer or a proxy in front of konga.

For example if you use nginx as a reverse proxy, the external SSL connections and certs can be handled by nginx itself.

Now, if you need to use SSL in your internal network of services,  sails.js, the framework Konga is build upon, supports that with some extra configuration.

Check out this post
https://stackoverflow.com/questions/17755916/how-to-configure-https-in-sails-js#29150716

**Comment by pantsel** [comment]
This feature is supported since https://github.com/pantsel/konga/releases/tag/0.12.1
