### ISSUE TITLE
Not able to connect to ssl kong admin from konga

### ISSUE THREAD

**Issue by ayan1207** [pantsel/konga#247]
Dear team,

We have setup kong admin over ssl (self signed certificate) and admin is running fine. But when are giving https://localhost:8001 url in konga getting below issue. Please help to close the issue.
We have installed konga in docker, also mounted client cert/keys in /etc/ssl/certs path of the container. 
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' } }
debug: Policy:dynamicNode `connection-id` is defined.
debug: KongProxyController:req.method GET
debug: KongProxyController:req.url ?connection_id=5
debug: KongProxyController:entity null
error: KongProxyController request error undefined
error: Sending 500 ("Server Error") response:
 { error: { Error: self signed certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' } }

Regards,
Ayan

**Comment by pantsel** [comment]
Hi ayan, at what port does kong admin api expects ssl connections? By default its 8444, not 8001. Whats your kong config?

**Comment by ayan1207** [comment]
@pantsel its my bad, typo mistake. We are using only ssl , we configured kong admin over ssl in  port  31334(https://xx.xx.xx.xx:31334) not 8001. Using the same kong admin url we are trying to connect from konga. Getting above mentioned error. Though it is working fine when kong admin is non ssl.

Regards

**Comment by pantsel** [comment]
Try setting
NODE_TLS_REJECT_UNAUTHORIZED = "0" 
As env variable when running konga

**Comment by ayan1207** [comment]
@pantsel , connection is success but none of our created api/plugins/service are showing after clicking on plugings or any of the tab . we are getting below error.

error: KongProxyController request error { message: 'Not found' }
debug: KongProxyController:req.method GET
debug: KongProxyController:req.url /plugins?size=4294967295
debug: KongProxyController:entity plugins
error: KongProxyController request error { message: 'Not found' }


For example we have the plugings created in KONG. **output from browser**
https://xx.xx.xx.xx:31334/plugins

{"total":1,"data":[{"created_at":1532677725000,"config":{"key_in_body":false,"run_on_preflight":true,"anonymous":"","hide_credentials":false,"key_names":["apikey"]},"id":"db4a4bab-c956-46db-b019-7c4fb9c319b9","name":"key-auth","api_id":"48a230d6-02a1-4cff-9f6b-86f3ecf72abc","enabled":true}]}

But in konga we are getting **"Not Found"** error. 

Regards,

**Comment by pantsel** [comment]
Do you have a trailing / on your connection url?

**Comment by ayan1207** [comment]
@pantsel Yes it was one "/" trailing in URL. After removing it is working fine. One questing i have here , after unmounted certs from konga container still is connecting to kong admin over https using the env provided by you , which should not  happen. 

  1.  is konga validating certs of kong admin?
  2.  is kong admin properly setup using SSL. Because without certs no one should connect.

Thanks..

**Comment by pantsel** [comment]
I lost you here. What do Kong's certs have to do with Konga and why should it matter that you unmounted the certs from Kongas container? Why have you mounted them to Konga's container in the first place?

If I understand correctly those are Kong's certs used to provide TLS for the admin API.

**Comment by ayan1207** [comment]
@pantsel , Thanks for your prompt response/resolution. We have installed all the component in kubernetes platform and we make kong-admin as clusterip type, that matches our security requirment with kong and konga integration.
