### ISSUE TITLE
Delete All User from Dashboard 

### ISSUE THREAD

**Issue by paroshdey** [pantsel/konga#248]
Hi ,
i  faced an issue where i was able to delete all the users using the dashboard (admin users as well as regular users ), this should be disallowed and one admin users should be there for whom the delete button should be disabled . As deleting all users can be destructive . 

Thanks .

**Comment by pantsel** [comment]
Its not really destructive cause if you restart the app the default users will be seeded so you will still be able to login with the default admin and go on from there.
