### ISSUE TITLE
The "Service" does not show consumers, in the "Eligible Consumers" section

### ISSUE THREAD

**Issue by pabduran** [pantsel/konga#251]
![image](https://user-images.githubusercontent.com/6096314/43407292-528bc24a-93ec-11e8-83e9-814d61d36266.png)

The "Service - httpin3" have a ACL plugin active and the consumer is in the same group.
My version is 0.12.0 and Kong is 0.14.

However, this problem does not occur with the "Routes".

Regards.

**Comment by pantsel** [comment]
Since the servise has no acls or auth plugins attached, It means all consumers are eligible.

No point of showing them.
