### ISSUE TITLE
konga v0.12.0  Accessible Services icon disappear  wrong 

### ISSUE THREAD

**Issue by neocy** [pantsel/konga#252]
![image](https://user-images.githubusercontent.com/9332187/43625610-803069a8-9720-11e8-9b8e-df5aa0f25572.png)

I install konga via docker ,
version v0.12.0
when I open Accessible Services under a consumer,
the icon disappear wrong .
I inspect from chrome but  no resources load error there.

do you have any idea about this ?

**Comment by jeremyjpj0916** [comment]
This also holds true as well for Accessible Routes, seems all these pages are broken up through and including Kong 0.14 as well. The new beta feature for showing consumers tied to a service/route works great though 💯 !

**Comment by pantsel** [comment]
The Accessible routes page is not yet implemented. It will be available on the next release.

**Comment by qiuhefeng** [comment]
Whether The Accessible routes page is implemented ?
