### ISSUE TITLE
select specific consumer for specific service when plugin is "Authentication"

### ISSUE THREAD

**Issue by ayan1207** [pantsel/konga#253]
We are not able to assign a specific consumer to a specific service when we are selecting authentication plugin in kong 0.14 CE. This will help to configure multiple kong proxy consumer to a specific service. Please suggest. Thanks !!

**Comment by pantsel** [comment]
@ayan1207 , what exactly are you trying to do? How would you approach this using the plain REST API?

The way it works is:
You assign an auth plugin to a service.
Then go to the consumer and create the respective credential.

Unless if i didn't understand correctly.

**Comment by ayan1207** [comment]
@pantsel, for example you have two consumers test1, test2, having credential based authentication set for test1, test 2 respectively, now you have created one service and added simple authentication plugin for the same service. Now if you access same service from kong proxy using test1/test2 consumer credential it will be accessible . But here if we want to assign that only test1 consumer can access the service, not test2 ,how we can achieve that.
Is it feasible please suggest.

**Comment by ayan1207** [comment]
Thanks @pantsel , Yes we have achieve our requirement what you had suggested.
