### ISSUE TITLE
getting {"message":"Invalid authentication credentials"} when plugin is LDAP

### ISSUE THREAD

**Issue by ayan1207** [pantsel/konga#255]
@pantsel , We have created one LDAP plugin for one router. We are getting {"message":"Invalid authentication credentials"} in client application while calling that service via kong proxy. There is no error log in kong pod.

Below are the plugin details which we set up our end.

curl -X POST http://localhost:8001/routes/6ee75341-cb22-4a8b-a980-c9d39bb91516/plugins \
    --data "name=ldap-auth"  \
    --data "config.hide_credentials=true" \
    --data "config.ldap_host=xx.xx.xx" \
    --data "config.ldap_port=3268" \
    --data "config.start_tls=false" \
    --data "config.base_dn=OU=SERVICE ACCT,dc=in,dc=mycom,dc=com" \
    --data "config.verify_ldap_host=false" \
    --data "config.attribute=cn" \
    --data "config.cache_ttl=60" \
    --data "config.header_type=ldap"

Client application is sending "**Authorization**" parameter in http-header like below
**credentials := ldap base64(encrypted user:encrypted pwd)**

Can you please help to get this resolve?

Thanks in advance !!

**Comment by pantsel** [comment]
@ayan1207 , this issue seems to be outside of Konga's scope. 
Check out https://konghq.com/plugins/ for how to use the LDAP plugin.

**Comment by 13233032535** [comment]
I also encountered the same problem, I look forward to your reply as soon as possible

**Comment by 13233032535** [comment]
I also encountered the same problem, I look forward to your reply as soon as possible.
@pantsel @ayan1207 @balexandre @piersharding

**Comment by balexandre** [comment]
@13233032535 I've stopped working with Kong a long time ago in prol of other systems
