### ISSUE TITLE
Cannot update the certs

### ISSUE THREAD

**Issue by xiejiangzhi** [pantsel/konga#256]
Hi guys, I got a problem.

Once create a Certificates, I cannot update it. 
I click "Details" => change the cert text => 'OK' => reload this page, the cert was recovered.

I use `pantsel/konga:0.12.0` with docker.

**Comment by pantsel** [comment]
@xiejiangzhi , thanks for the heads up. The issue is fixed and will be available on the next release. Meanwhile, you can use the [next](https://github.com/pantsel/konga/tree/next) branch or the docker image `pantsel/konga:next` to get the latest changes and bug fixes.

Cheers!

**Comment by xiejiangzhi** [comment]
@pantsel, thanks, it is very quick :+1:
