### ISSUE TITLE
Question about Plugin Description 

### ISSUE THREAD

**Issue by kakarooky** [pantsel/konga#257]
Dear Konga team
This is great UI for Kong and I love it.

I extended request-transformer plugin and It works very well.
However, I want to add description in prepath filed but I couldn't find it where i can set the description.

Please see the attached image.

![konga_plugin](https://user-images.githubusercontent.com/19172100/44067971-e18f319e-9fb2-11e8-9c91-2523dd85652a.png)

Thank you.

**Comment by pantsel** [comment]
@kakarooky , thanks for the notice. I will document it. Meanwhile you can check the plugin docs at https://docs.konghq.com/plugins/request-transformer/ so that you know what's what.

**Comment by kakarooky** [comment]
@pantsel, Thank you for your reply.

My question is that I want to add my own description in Konga (UI).
![image](https://user-images.githubusercontent.com/19172100/44201907-690d4600-a185-11e8-9322-8d394ce68d5d.png)

**Comment by pantsel** [comment]
Ok, now I get it. 

No you cannot do that unless you mess with the source code.

Here is the place you can mess with:

https://github.com/pantsel/konga/blob/853518f0675623db61067db93a6d4396a0f98628/assets/js/app/core/services/KongPluginsService.js#L826

**Comment by kakarooky** [comment]
@pantsel 
Thank you ^^
