### ISSUE TITLE
services submit changes got error

### ISSUE THREAD

**Issue by MichelLiu** [pantsel/konga#260]
When I clicked 'submit changes' button from services tab, I got an error "strategy: 'mysql', message: 'schema violation (created_at: expected an integer)'"

**Comment by pantsel** [comment]
@MichelLiu , I cannot reproduce the issue. I will need more details.
Kong version?
Konga version?
You're obviously using the MYSQL adapter, right?
Can you reproduce the issue? Please write down the exact steps to do so.

**Comment by MichelLiu** [comment]
Thanks for your reply, I had already resolved the problem. I am now trying to satisfy kong with Mysql.
The differences between mysql and postgress may cause a lot of sql syntax problems, such as RETURNING(mysql not supported and I have to query after update or insert).
