### ISSUE TITLE
The kong_admin_url default connection seed data should be set to process.env.KONG_ADMIN_URL

### ISSUE THREAD

**Issue by dandua98** [pantsel/konga#261]
https://github.com/pantsel/konga/blob/853518f0675623db61067db93a6d4396a0f98628/api/models/KongNode.js#L121

The kong_admin_url if set to something other than `http://kong:8001` via the KONG_ADMIN_URL environment variable in a docker container or just left to http://localhost:8001 (the default) can be a bit confusing since konga shows `http://kong:8001` as the connection while it's connected to some other URL. I can send a PR to fix this if you agree

**Comment by pantsel** [comment]
@dandua98 , submit a PR on the [next](https://github.com/pantsel/konga/tree/next) branch.
