### ISSUE TITLE
Route not creating with konga 0.14.0 via service 

### ISSUE THREAD

**Issue by anupam4881** [pantsel/konga#263]
Hi Team,

kong : 0.14.0 - up & running with posgres
node install at : /opt/node-v8.11.4-linux-x64/bin
[root@psld-ggn-233 bin]# node --version
v8.11.4
Konga with localDB version 0.12.0
First i create one Upstream and than service, after that when i am trying to create routes everytime it is giving me below error although i entered all values

debug: KongProxyController:entity routes
error: KongProxyController request error { fields: 
   { '@entity': 
      [ 'at least one of these fields must be non-empty: \'methods\', \'hosts\', \'paths\'' ] },
  name: 'schema violation',
  code: 2,
  message: 'schema violation (at least one of these fields must be non-empty: \'methods\', \'hosts\', \'paths\')' }

Regards
Anupam

**Comment by pantsel** [comment]
Press enter after every method host or path u type.

**Comment by anupam4881** [comment]
Yes, It was mention in blue. Thanks a lot.

Regards
Anupam
