### ISSUE TITLE
Error Konga - New Version

### ISSUE THREAD

**Issue by augustoferronato** [pantsel/konga#267]
Hello,
When i use the Kong 0.13.1 and Konga 0.12.0 i receive the error:

> 23/08/2018 22:07:17    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
> 23/08/2018 22:07:17    at emitOne (events.js:116:13)
> 23/08/2018 22:07:17    at Socket.emit (events.js:211:7)
> 23/08/2018 22:07:17    at addChunk (_stream_readable.js:263:12)
> 23/08/2018 22:07:17    at readableAddChunk (_stream_readable.js:250:11)
> 23/08/2018 22:07:17    at Socket.Readable.push (_stream_readable.js:208:10)
> 23/08/2018 22:07:17    at TCP.onread (net.js:597:20)
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Details:  error: column __node.netdata_url does not exist
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Sending 500 ("Server Error") response:
> 23/08/2018 22:07:17 Error (E_UNKNOWN) :: Encountered an unexpected error
> 23/08/2018 22:07:17error: column __node.netdata_url does not exist
> 23/08/2018 22:07:17    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
> 23/08/2018 22:07:17    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
> 23/08/2018 22:07:17    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
> 23/08/2018 22:07:17    at emitOne (events.js:116:13)
> 23/08/2018 22:07:17    at Socket.emit (events.js:211:7)
> 23/08/2018 22:07:17    at addChunk (_stream_readable.js:263:12)
> 23/08/2018 22:07:17    at readableAddChunk (_stream_readable.js:250:11)
> 23/08/2018 22:07:17    at Socket.Readable.push (_stream_readable.js:208:10)
> 23/08/2018 22:07:17    at TCP.onread (net.js:597:20)
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Details:  error: column __node.netdata_url does not exist
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Sending 500 ("Server Error") response:
> 23/08/2018 22:07:17 Error (E_UNKNOWN) :: Encountered an unexpected error
> 23/08/2018 22:07:17error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:17    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
> 23/08/2018 22:07:17    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
> 23/08/2018 22:07:17    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
> 23/08/2018 22:07:17    at emitOne (events.js:116:13)
> 23/08/2018 22:07:17    at Socket.emit (events.js:211:7)
> 23/08/2018 22:07:17    at addChunk (_stream_readable.js:263:12)
> 23/08/2018 22:07:17    at readableAddChunk (_stream_readable.js:250:11)
> 23/08/2018 22:07:17    at Socket.Readable.push (_stream_readable.js:208:10)
> 23/08/2018 22:07:17    at TCP.onread (net.js:597:20)
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Details:  error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Sending 500 ("Server Error") response:
> 23/08/2018 22:07:17 Error (E_UNKNOWN) :: Encountered an unexpected error
> 23/08/2018 22:07:17error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:17    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
> 23/08/2018 22:07:17    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
> 23/08/2018 22:07:17    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
> 23/08/2018 22:07:17    at emitOne (events.js:116:13)
> 23/08/2018 22:07:17    at Socket.emit (events.js:211:7)
> 23/08/2018 22:07:17    at addChunk (_stream_readable.js:263:12)
> 23/08/2018 22:07:17    at readableAddChunk (_stream_readable.js:250:11)
> 23/08/2018 22:07:17    at Socket.Readable.push (_stream_readable.js:208:10)
> 23/08/2018 22:07:17    at TCP.onread (net.js:597:20)
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Details:  error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Sending 500 ("Server Error") response:
> 23/08/2018 22:07:17 Error (E_UNKNOWN) :: Encountered an unexpected error
> 23/08/2018 22:07:17error: column __node.netdata_url does not exist
> 23/08/2018 22:07:17    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
> 23/08/2018 22:07:17    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
> 23/08/2018 22:07:17    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
> 23/08/2018 22:07:17    at emitOne (events.js:116:13)
> 23/08/2018 22:07:17    at Socket.emit (events.js:211:7)
> 23/08/2018 22:07:17    at addChunk (_stream_readable.js:263:12)
> 23/08/2018 22:07:17    at readableAddChunk (_stream_readable.js:250:11)
> 23/08/2018 22:07:17    at Socket.Readable.push (_stream_readable.js:208:10)
> 23/08/2018 22:07:17    at TCP.onread (net.js:597:20)
> 23/08/2018 22:07:17
> 23/08/2018 22:07:17Details:  error: column __node.netdata_url does not exist
> 23/08/2018 22:07:17
> 23/08/2018 22:07:18Sending 500 ("Server Error") response:
> 23/08/2018 22:07:18 Error (E_UNKNOWN) :: Encountered an unexpected error
> 23/08/2018 22:07:18error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:18    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
> 23/08/2018 22:07:18    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
> 23/08/2018 22:07:18    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
> 23/08/2018 22:07:18    at emitOne (events.js:116:13)
> 23/08/2018 22:07:18    at Socket.emit (events.js:211:7)
> 23/08/2018 22:07:18    at addChunk (_stream_readable.js:263:12)
> 23/08/2018 22:07:18    at readableAddChunk (_stream_readable.js:250:11)
> 23/08/2018 22:07:18    at Socket.Readable.push (_stream_readable.js:208:10)
> 23/08/2018 22:07:18    at TCP.onread (net.js:597:20)
> 23/08/2018 22:07:18
> 23/08/2018 22:07:18Details:  error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:18
> 23/08/2018 22:07:18Sending 500 ("Server Error") response:
> 23/08/2018 22:07:18 Error (E_UNKNOWN) :: Encountered an unexpected error
> 23/08/2018 22:07:18error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:18    at Connection.parseE (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
> 23/08/2018 22:07:18    at Connection.parseMessage (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
> 23/08/2018 22:07:18    at Socket.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
> 23/08/2018 22:07:18    at emitOne (events.js:116:13)
> 23/08/2018 22:07:18    at Socket.emit (events.js:211:7)
> 23/08/2018 22:07:18    at addChunk (_stream_readable.js:263:12)
> 23/08/2018 22:07:18    at readableAddChunk (_stream_readable.js:250:11)
> 23/08/2018 22:07:18    at Socket.Readable.push (_stream_readable.js:208:10)
> 23/08/2018 22:07:18    at TCP.onread (net.js:597:20)
> 23/08/2018 22:07:18
> 23/08/2018 22:07:18Details:  error: column konga_kong_nodes.netdata_url does not exist
> 23/08/2018 22:07:18

When i use the konga 0.10.4 works without problem.

I have another enviroment, where i have kong 0.12.3 and konga 0.12.0 and everything works fine.

Have some reason for that?

Thanks

**Comment by pantsel** [comment]
It seems like your db is not seeded properly.

Found any solution yet?
