### ISSUE TITLE
Delete a Connection

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [pantsel/konga#271]
I cannot figure out how to delete/remove a connection from the list of connections.

am i missing something really simple? or is there no delete button?

**Comment by pantsel** [comment]
If you're logged in with a user instead of an admin account you may not have permission to do so.

**Comment by jgrammen-agilitypr** [comment]
I am logged in with a admin account

**Comment by pantsel** [comment]
Can u please post a screenshot of the connections list?

**Comment by jgrammen-agilitypr** [comment]
![kongaconnections](https://user-images.githubusercontent.com/22965146/45564797-8e8e7d80-b81f-11e8-8ba8-a8ac1ff3d642.png)

**Comment by pantsel** [comment]
Just scroll the table to the right using the grey scrollbar on the bottom of it. Apparently your screen res doesnt fit all of it.

**Comment by jgrammen-agilitypr** [comment]
thank you very much, I apologize for the seemingly dumb question

**Comment by pantsel** [comment]
Nps man. Glad to help.
