### ISSUE TITLE
Konga LDAP admin users do not have admin flag set

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [pantsel/konga#272]
When a user who is authenticating against AD/LDAP logs in, if they are a member of the group defined in KONGA_ADMIN_GROUP_REG, they appears to be an administrator (they see the settings tab in the menu) but the admin switch in their user profile is not set to admin.

The user will be able to toggle it themselves (they can make themselves an admin) which to me indicates that they are an admin, but something isn't setting the admin flag to true.

My konga ldap settings in .env
```
KONGA_AUTH_PROVIDER=ldap
KONGA_LDAP_HOST=ldap://domain.com:389
KONGA_LDAP_BIND_DN=CN=ServiceAccount Konga,OU=Service Accounts,DC=domain,DC=com
KONGA_LDAP_BIND_PASSWORD=password
KONGA_LDAP_USER_SEARCH_BASE=OU=Users,OU=CORP,DC=domain,DC=com
KONGA_LDAP_USER_SEARCH_FILTER=(&(sAMAccountName={{username}})(|(memberOf:1.2.840.113556.1.4.1941:=CN=konga-admins,OU=Access,OU=Groups,OU=CORP,DC=domain,DC=com)(memberOf:1.2.840.113556.1.4.1941:=CN=konga-users,OU=Access,OU=Groups,OU=CORP,DC=domain,DC=com)))
KONGA_LDAP_USER_ATTRS=sAMAccountName,givenName,sn,mail,dn
KONGA_LDAP_GROUP_SEARCH_BASE=OU=Access,OU=Groups,OU=CORP,DC=domain,DC=com
KONGA_LDAP_GROUP_SEARCH_FILTER=(member={{dn}})
KONGA_LDAP_GROUP_ATTRS=member,cn,dn
KONGA_ADMIN_GROUP_REG=^(konga-admins)$
KONGA_LDAP_ATTR_USERNAME=sAMAccountName
KONGA_LDAP_ATTR_FIRSTNAME=givenName
KONGA_LDAP_ATTR_LASTNAME=sn
KONGA_LDAP_ATTR_EMAIL=mail
```

**Comment by pantsel** [comment]
Ldap integration is still a work in progress. PRs are welcome

**Comment by hosein33** [comment]
hi
i add env KONGA_ADMIN_GROUP_REG: ^(admin|konga)$
but i recived this error 
ERROR: Invalid interpolation format for "environment" option in service "konga":  ^(admin|konga)$
