### ISSUE TITLE
Session Cookie Does Not Contain the "Secure" Attribute

### ISSUE THREAD

**Issue by RoBuerger** [pantsel/konga#273]
THREAT:
The secure cookie flag is an option that can be set by the application server when sending a new cookie to the user within an HTTP
Response. The purpose of the secure flag is to prevent cookies from being observed by unauthorized parties due to the transmission of a
the cookie in clear text. By setting the secure flag, the browser will prevent the transmission of a cookie over an unencrypted channel.
A cookie with the secure attribute was not detected in the scan.
QID Detection Logic:
This unauthenticated QID checks for the existence of the "secure" cookie flag.

IMPACT:
Session cookies sent via HTTP expose users to sniffing attacks that could lead to user impersonation or account compromise.

SOLUTION:
Apply the "secure" attribute to session cookies to ensure that they are sent via HTTPS only. More information about this flag can be
found here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie.

**Comment by pantsel** [comment]
@RoBuerger , Konga doesn't use sessions. It's stateless and uses JWT auth instead.
