### ISSUE TITLE
Unable to add route to service (Kong 0.14)

### ISSUE THREAD

**Issue by PichayuthK** [pantsel/konga#275]
I can add new services with Konga web,
but when I try to add routes providing paths = / 
It shown me the error 

`Submission failed. schema violation (at least one of these fields must be non-empty: 'method'. 'hosts', 'paths')`

![screen shot 2561-09-20 at 18 00 22 2](https://user-images.githubusercontent.com/8033513/45814507-049f5280-bd00-11e8-9504-a8f85c2bd04d.png)

**Comment by pantsel** [comment]
https://github.com/pantsel/konga/issues/263

**Comment by ahidnaeimi** [comment]
*For hosts, paths, methods and protocols, press enter to apply every value you type
After

**After filling in the fields hosts, paths, methods and protocols, press enter**

**Comment by pheuberger** [comment]
Oh my, that's not a great UX if I may say so. Even with that explanation, it didn't make sense to me.

**Comment by andrequeiroz2** [comment]
ooooooo, the tool is good, i'm adapting.
