### ISSUE TITLE
Grunt is using lot of cpu

### ISSUE THREAD

**Issue by jlastuni** [pantsel/konga#276]
Hi,
for some reason grunt is always using lot of CPU ~30% though almost nothing is happening in Kong or Konga.

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 1349 root      20   0 1268180 156116  27424 S 31.2  7.6   1363:26 grunt

How to troubleshoot this?

**Comment by pantsel** [comment]
That is normal if you a running Konga  on development mode.
There are background tasks like filewatchers etc in place that cause higher mem usage.

Try running Konga on production mode instead

**Comment by jlastuni** [comment]
Yes, that did it. Thank you!

 

-Juha
