### ISSUE TITLE
Unable to login with docker instance

### ISSUE THREAD

**Issue by thucnc** [pantsel/konga#28]
I used docker by cmd `docker run -p -d 3000:3000 -p 1338:1338 -e KONGA_BACKEND_URL=127.0.0.1:8001 --link kong:kong --name konga pantsel/konga` but unable to login by admin - adminadminadmin at the login page. Is there any clue ? Thanks

**Comment by thucnc** [comment]
@bakstad do you have any idea as I found you have another konga image ?

**Comment by chris-fung** [comment]
Why there is no docker image for backend ? I can't quite understand why backend should deploy seperately.

**Comment by pantsel** [comment]
@thucnc ,
<pre>KONGA_BACKEND_URL</pre> is not Kong's admin API URL. It is the URL Konga's backend is lifted.

If Konga runs on localhost, it should be <pre>KONGA_BACKEND_URL=127.0.01:1338</pre>

@chris-fung ,
The backend is not deployed separately. It is bundled in the same docker image as the frontend, But it can be deployed separately from source. Backend and frontend are loosely coupled so they can meet more than one deployment strategies. 

For example, I only have the backend running on my live server with Kong, and use the frontend from my local machine,

**Comment by aaae** [comment]
<img width="1279" alt="qq20170308-141647 2x" src="https://cloud.githubusercontent.com/assets/3000843/23692479/f1a02afc-0409-11e7-9361-60a58d20c32d.png">

```
docker run -d -p 5000:3000 -p 1338:1338 -e KONGA_BACKEND_URL=127.0.0.1:1338 --name konga pantsel/konga
```

konga still unable to login by admin - adminadminadmin at the login page... 
where is the log print?
Thanks

**Comment by pantsel** [comment]
Try using the server's actual ip instead of 127.0.0.1.
Open chrome's dev console and check the login request response on the network tab. Post a screenshot if you are still not able to login.

**Comment by chris-fung** [comment]
I'm using docker swarm mode to deploy konga, after changing KONGA_BACKEND_URL from any address you mentioned above, I still can't login.
![11](https://cloud.githubusercontent.com/assets/6920145/23694896/681aff2e-0417-11e7-97dd-bb3b1fa08308.png)

**Comment by driagongit** [comment]
¿Does anyone solved this? I have the same problem, I have tried by using the actual ip and changing the ports but it still doesn't work.

**Comment by pantsel** [comment]
Is this happening only on the docker image or when running Konga from source as well?

**Comment by driagongit** [comment]
I just tried with the docker image, I didn't test the source.

**Comment by pantsel** [comment]
Ok. I'm gonna push some scheduled updates this weekend and I'll fix that as well. Please bare with me.

**Comment by driagongit** [comment]
Ok, I'll be watching this repo for the update

**Comment by driagongit** [comment]
Ok, I'll be watching this repo for the update.

**Comment by pantsel** [comment]
A new version has been released with a new docker instance, Check the new  README.md and release info https://github.com/pantsel/konga/releases/tag/v0.5.0

**Comment by aaae** [comment]
@pantsel   done  it's works. tks
