### ISSUE TITLE
The plugins is not working 

### ISSUE THREAD

**Issue by qiuhefeng** [pantsel/konga#282]
First , I  add `key-auth` plugin by konga.  
then , I find it's not working .
so i use the kong admin api to add `key-auth`, then , it is working .
i don't kown why the konga is not working .

i use konga like this:
![image](https://user-images.githubusercontent.com/37201542/46204183-e6b09e00-c34e-11e8-9bd6-ecf472cd6513.png)

![image](https://user-images.githubusercontent.com/37201542/46204170-ddbfcc80-c34e-11e8-9189-c552bb0f217f.png)
 
the consumers 
![image](https://user-images.githubusercontent.com/37201542/46204213-ff20b880-c34e-11e8-8864-8052c41e3763.png)

when i set `key-auth` `enable=true` by konga , like this:
![image](https://user-images.githubusercontent.com/37201542/46204314-5cb50500-c34f-11e8-845f-8c6891527275.png)
i get by kong admin api `curl -X GET http://xxxxx:8001/plugins/ --data "name=key-auth"`, it return 
```js
{"total":1,"data":[{"created_at":1538159108000,"config":{"key_in_body":false,"key_names":["apikey"],"anonymous":"","hide_credentials":false,"run_on_preflight":true},"id":"4b0531ce-264d-491c-ada9-63ef47e936b1","name":"key-auth","enabled":true}]}
```
so it means the change is working . but my application request api , it also not needs `apikey`

so i don't what's happend.

the docker image of kong version: 0.14.1-alpine
the docker image of konga version: 0.12.2
the db : postgresql

**Comment by pantsel** [comment]
@qiuhefeng, I don't know if i understand your question fully.

You have enabled the key-auth plugin **globally**. 

That means that an apikey is required in order to consume **every single** service-route or api.

**Comment by qiuhefeng** [comment]
I have enabled the key-auth plugin globally By Konga. But , it did not work .
Then , i enabled it by kong admin api, then , it work .
so , i don't know what happend by konga

**Comment by pantsel** [comment]
I cannot reproduce the issue. It seems to be working fine on my end.

What version of Kong and Konga are you using?

**Comment by qiuhefeng** [comment]
**The Version:**
the docker image of kong version: 0.14.1-alpine
the docker image of konga version: 0.12.2
the db : postgresql

we deploy them on k8s. 
I don't confirm if it is a problem with k8s.
I will check the problem with other colleagues tomorrow.
I will reply again tomorrow.

Thank you very much for your reply.

**Comment by qiuhefeng** [comment]
Now we have confirmed that it is not a problem with konga.

I start konga not by K8s.  Konga everything works fine.
Although we are not sure what happened to k8s, but we sure it is not a problem with konga.
