### ISSUE TITLE
Consumers mistakenly delete errors

### ISSUE THREAD

**Issue by yueyuan4** [pantsel/konga#283]
When I delete a consumer under my service, I delete the global consumer. Consumers under "service/Routes/Eliglble consumers" are consumers of "/Consumers", which can mislead people who are just learning kong and using Konga, and can have serious consequences.
<img width="943" alt="konga" src="https://user-images.githubusercontent.com/42060944/46254323-1f23b980-c4c0-11e8-8e05-9662de68b282.png">

**Comment by pantsel** [comment]
I don't fully understand your point. A consumer is a consumer. Theres no global or non global. When you delete a consumer, thats it. No matter from what page you do so. How is that confusing?

**Comment by yueyuan4** [comment]
First of All,"A consumer is a consumer. Theres no global or non global."I agree with it now.But before I delete,I find the other consumers which not belong to me under my service,so I think that I should delete what I don't what.I mean that it will mislead the beginner like me.

**Comment by pantsel** [comment]
What do you suggest it would be a bettet approach?

**Comment by yueyuan4** [comment]
I don't know why you design a consumer that can be viewed and deleted on two pages. I think managing consumers at the outermost layer is enough, but you may have other considerations.

**Comment by pantsel** [comment]
The consumers you see under the services or routes are not always the same as the consumers you see on the consumers page. The "eligible" consumers you see on the services and routes are only the ones that have access the specific resourse based on assigned plugins and acls. That way you can easily see what consumers can access what

**Comment by yueyuan4** [comment]
Well, I know it now. Thank you for your help.
