### ISSUE TITLE
demo password is invalid

### ISSUE THREAD

**Issue by hepyu** [pantsel/konga#290]
RT, demo password is invalid. Can't login. It maybe changed.
![image](https://user-images.githubusercontent.com/3917749/47554496-0500be00-d93c-11e8-8e30-9be804deaddb.png)

**Comment by jsdmultisys** [comment]
@pantsel Is the demo not available in public anymore?

**Comment by pantsel** [comment]
Check it out again guys

**Comment by hepyu** [comment]
works now~ 3Q~~

**Comment by jsdmultisys** [comment]
I think it should have cron job that reset the credentials everyday? Some unruly users are changing credentials. :(

**Comment by hepyu** [comment]
yeah, so how about forbid the changing password function in the demo.

**Comment by pantsel** [comment]
That's not in the business logic. 
The logged in user can change his/hers password. 
Not going to include a separate case just for the demo.

Plus, OK, Konga is a free app. You can download it and test it locally in no time.
