### ISSUE TITLE
version 0.13.0 cannot save changes on certificate

### ISSUE THREAD

**Issue by lurongkai** [pantsel/konga#294]
kong: 0.14.0
konga: 0.13.0

running both in docker.

we have a certificate saved by konga long time ago, and now certificate is going to expired. so we have to update it with new issued cert. when open certificate detail and replaced with new certificate content, seems everything is fine after click ok button.

after that, open certificate detail again, it still shows old certificate and nothing changed.

we pretty sure that kong admin api support update certificate and we finally update certificate through /certificates/{id} [api](https://docs.konghq.com/0.14.x/admin-api/#update-or-create-certificate). so we suppose this to be a bug.

hopes this can be fixed in future version.

**Comment by pantsel** [comment]
This is fixed in newer versions. Feel free to reopen if needed.
