### ISSUE TITLE
Show Kong Plugin ID 

### ISSUE THREAD

**Issue by ntloi95** [pantsel/konga#298]
I need to Turn On, Turn Off Kong Plugin by API from a third-party app. 
But KONGA doesn't show Kong Plugin ID:
![image](https://user-images.githubusercontent.com/9493402/48477153-6b8a4500-e833-11e8-8571-80fca5fe39a7.png)

**Comment by pantsel** [comment]
If you click on the `eye` icon, you can see the full details of the plugin in json format including it's id.
![screencapture-139-59-145-231-1337-2018-11-14-12_43_07](https://user-images.githubusercontent.com/5519873/48477715-fa369c00-e80a-11e8-8614-341628b0a42b.png)

**Comment by ntloi95** [comment]
Thank you very much.
