### ISSUE TITLE
Why the default kong_admin_url feature is disabled in all project?

### ISSUE THREAD

**Issue by protheantom** [pantsel/konga#299]
Hello Konga guys,

First of all thanks for your work, this looks a great project, very useful to manage Kong, and I think is better than other alternatives.

I think having an ENV VAR to define a default Kong admin url is very useful for fast docker installations

The combination of the users seed feature and a default kong admin url allows to have a ready out-of-the box Konga. Why has been disabled in the source code? Some examples:

https://github.com/pantsel/konga/blob/0bbccc8b68fd19c942897b0ea94fc20c9ffc1531/api/models/KongNode.js#L118

or

https://github.com/pantsel/konga/blob/master/config/env/production.js#L24

Thanks!

**Comment by protheantom** [comment]
I think would be great a "kong-nodes" seed feature

**Comment by b-ggs** [comment]
Bumping this. Would love to see this as a feature in a future release. I had to fork Konga to re-enable this functionality: https://github.com/b-ggs/konga/commit/b0cc22f58c7b16c66786b0c1b2fe2fb38c69f4c7

**Comment by pantsel** [comment]
@b-ggs 's , addition will be available in the upcoming 0.14.4 version. For now, everyone that needs to use this functionality, can switch to the [next](https://github.com/pantsel/konga/tree/next) branch or use `pantsel:konga/next` from docker hub.

Thanks a lot for the contribution.
