### ISSUE TITLE
infinite errors reported after changing admin user settings

### ISSUE THREAD

**Issue by tumluliu** [pantsel/konga#30]
I just deployed v0.5.1. At first, it worked just fine. But after I changed the admin user's profile, I can not switch back to the main page. I was stuck on the admin user's settings page wherever I clicked. If I refresh the page, I got infinite following two errors reported in the browser's console. And the mem is being eaten up. And the exact same thing happened even if I switched to production mode. I am not sure if the error info is enough because I am not very familiar with frontend dev. I would like to provide more info if necessary. thanks! 

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:17874)
    at Scope.$apply (angular.js:18102)
    at angular.js:19950
    at completeOutstandingRequest (angular.js:6045)
    at angular.js:6324
(anonymous) @ angular.js:14199
(anonymous) @ angular.js:10707
$apply @ angular.js:18104
(anonymous) @ angular.js:19950
completeOutstandingRequest @ angular.js:6045
(anonymous) @ angular.js:6324
angular.js:68 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:17874)
    at Scope.$apply (angular.js:18102)
    at angular.js:19950
    at completeOutstandingRequest (angular.js:6045)
    at angular.js:6324
```

**Comment by pantsel** [comment]
@tumluliu , It should be ok now.

**Comment by tumluliu** [comment]
yeah @pantsel, this version works without that problem. thanks a lot!

Closing this issue
