### ISSUE TITLE
konga service register parameter path can not be null(use the default value)

### ISSUE THREAD

**Issue by dtflyfy** [pantsel/konga#310]
when registe the service to the konga,the parameter path is needed.but when we do not fill the path,it will remind us the path is must and must start with /, but via the curl http request to kong services api by --data 'path=' , the path set to null,and the route working well .

**Comment by pantsel** [comment]
@dtflyfy, Konga needs the path to be set.

**Comment by dtflyfy** [comment]
i need to integrated the consul,so i can't set the path. if i set the path,i can not use the api by route. i think you should compatible both.

**Comment by pantsel** [comment]
For now, it works that way, but I'll see what I can do in a future release.

**Comment by dtflyfy** [comment]
OK,thank you for answering my question. konga is wonderful,if fix that,it will be more perfect.hoping for you next release to fix it.

**Comment by pantsel** [comment]
@dtflyfy , I wrote it on my toDos. When i find some time for the next release I'll let you know.

Cheers!
