### ISSUE TITLE
Upstream healthcheck -Notifications to Slack

### ISSUE THREAD

**Issue by Edwards80** [pantsel/konga#311]
It would be excellent if the upstream healthchecks could send slack notifications in the same way that node/api healthchecks do.

**Comment by pantsel** [comment]
@Edwards1stStop, investigating this a bit more, it ends up that it is indeed possible.
I'll dive into it as soon as the integration with Kong 1.x is finalized.

Cheers.

**Comment by pantsel** [comment]
@Edwards80 , the feature is available staring from [Konga 0.14.1](https://github.com/pantsel/konga/releases/tag/0.14.1).

**Comment by Edwards80** [comment]
Great news. Many thanks!
