### ISSUE TITLE
Add trustProxy setting

### ISSUE THREAD

**Issue by minhpq331** [pantsel/konga#312]
Deploy konga behind a proxy with SSL termination causes this error
![image](https://user-images.githubusercontent.com/16734662/49504422-30b48380-f8ac-11e8-8711-479f6a4495e1.png)

Reason: konga does not set `trustProxy` config so `base` tag is in incorrect (`http` scheme instead of `https`
Possible fix: edit `config/http.js` file and add `trustProxy: true`.

**Comment by pantsel** [comment]
@minhpq331 , a PR would be greatly appreciated if you can verify that the fix works

**Comment by minhpq331** [comment]
@pantsel oh sorry, my bad, the culprit is the nginx proxy, not konga.
Thanks for your response. (y)
