### ISSUE TITLE
Encountered an unexpected error TypeError: Cannot read property 'getPKField' of undefined

### ISSUE THREAD

**Issue by ximbal** [pantsel/konga#324]
Really wierd behavior that Konga started to exhibit, I thought it was something corrupted on the DB, I've tried with version 0.13 and 0.12 against Kong 0.14.1

None of our configurations in Kong are showing through Konga, we have a bunch of defined API's

I've made a screen capture to show the behavior, it was working before without any significant changes on our environment, is it something particular to this machine? I am running konga locally.

![kapture 2019-01-16 at 8 53 28](https://user-images.githubusercontent.com/19576367/51254108-49658e00-196e-11e9-9a24-82b05549e43c.gif)

After clicking the connections button on the console it starts looping with this message:

> debug: KongNode:afterUpdate:called()
> debug: KongNode:afterUpdate:health_checks false
> debug: KongNode:afterUpdate:emit health_checks.stop
> debug: KongNode:afterUpdate:called()
> debug: KongNode:afterUpdate:health_checks false
> debug: KongNode:afterUpdate:emit health_checks.stop
> debug: { node:
>    { name: 'default',
>      kong_admin_url: 'http://localhost:8001',
>      active: true,
>      type: 'default',
>      kong_api_key: '',
>      jwt_algorithm: 'HS256',
>      kong_version: '0-10-x',
>      health_checks: false,
>      createdAt: '2019-01-16T14:02:20.541Z',
>      updatedAt: '2019-01-16T14:05:25.999Z',
>      id: 1,
>      createdUser: null,
>      updatedUser: 1 },
>   updatedUser: '1' }
> debug: KongProxyHooks:afterEntityFetch called() null
> debug: KongNode:afterUpdate:called()
> debug: KongNode:afterUpdate:health_checks false
> debug: KongNode:afterUpdate:emit health_checks.stop
> debug: KongProxyController:req.method GET
> debug: KongProxyController:req.url
> debug: KongProxyController:entity null
> debug: Kong admin url => http://localhost:8001
> debug: { node:
>    { name: 'default',
>      kong_admin_url: 'http://localhost:8001',
>      active: true,
>      type: 'default',
>      kong_api_key: '',
>      jwt_algorithm: 'HS256',
>      kong_version: '0-10-x',
>      health_checks: false,
>      createdAt: '2019-01-16T14:02:20.541Z',
>      updatedAt: '2019-01-16T14:05:26.000Z',
>      id: 1,
>      createdUser: null,
>      updatedUser: 1 },
>   updatedUser: '1' }

Finally after terminating the process, I get:

Encountered an unexpected error TypeError: Cannot read property 'getPKField' of undefined

Any Ideas?

Regards and thank you

**Comment by ximbal** [comment]
I had to reboot the whole thing, wierdest thing ever. Thanks for the help, and Thanks for the efforts for this great Product!!!, cheers.

**Comment by pantsel** [comment]
I'll try to investigate further and reproduce it. In the meantime I'm closing this due to housekeeping. Feel free to reopen if necessary.
