### ISSUE TITLE
When add oauth2 plugging to service uuid error

### ISSUE THREAD

**Issue by lilan123** [pantsel/konga#326]
Hi Team, 

When I try to assign oauth2 plugging to the service by proving below information, I received error message "schema violation (consumer.id: expected a valid UUID)". 

1. consumer : consumer_001
2. scope : id 
3. mandatory scope : yes 
4. enable authorization code: yes 

Please help me to resolve this.

**Comment by lilan123** [comment]
this is the value given for consumer id.

**Comment by pantsel** [comment]
That is probably the custom_id not the actual consumer id. On the consumers list click on the eye icon. In there you will see the actusl id.

**Comment by lilan123** [comment]
when i click on the eye icon and it shows uuid "e5b15ed5-7beb-4edb-a129-7024e6d83edd". but when I gave this uuid as consumer, I received error "schema violation (consumer: value must be null)"

**Comment by lilan123** [comment]
it seems like consumer should be null when assign new plugging to service.

**Comment by pantsel** [comment]
There are some plugins that cannot be set for a specific consumer. The easiest way to add a plugin to a consumers is from the consumers page. There, only the plugins that can be assigned to a consumer are shown.
