### ISSUE TITLE
Your Demo user and password wrong. 

### ISSUE THREAD

**Issue by demirizZz** [pantsel/konga#327]

**Comment by pantsel** [comment]
I don't understand what you're trying to say.

**Comment by demirizZz** [comment]
Demo user and password wrong in your web site.
You write this but its not working.
username: demo
password: demodemodemo

Pelase check it.

**Comment by pantsel** [comment]
OK, Check again.

You can always download Konga and test it.
It's free, open source and easy to install locally.

The demo site, is a subject of changes. 

People log in and change things in there all the time.

Some times it's down as well.

I would advise to download the app and test it locally with full permissions and features.
