### ISSUE TITLE
version 0.14.1 hook `orm` error

### ISSUE THREAD

**Issue by vietwow** [pantsel/konga#331]
Hi,

I'm try to deploy kong 1.0.3 and then konga 0.14.1 on k8s (v1.11.6) and then get the error from konga pod as follow :

`# kubectl -n platform logs -f konga-6f9b445db5-6rmt7`

> Error: The hook `orm` is taking too long to load.
> Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 60000)
>     at Timeout.tooLong [as _onTimeout] (/app/node_modules/sails/lib/app/private/loadHooks.js:85:21)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
> 
> Error creating a connection to Postgresql using the following settings:
>  postgres://konga:kong4Pwd@konga-postgresql:5432/konga_database?host=konga-postgresql&port=5432&schema=true&ssl=false&adapter=sails-postgresql&user=konga&password=kong4Pwd&database=konga_database&poolSize=10&identity=postgres
> 
> * * *
> Complete error details:
>  { Error: connect ETIMEDOUT 100.66.32.186:5432
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
>   errno: 'ETIMEDOUT',
>   code: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '100.66.32.186',
>   port: 5432 }
> 
> 
> Troubleshooting tips:
> 
>  -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in `config/connections.js`, or wherever your environment-specific database configuration is set.
> 
>  -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.
> 
>  -> Do you have multiple Sails instances sharing the same Postgresql database? Each Sails instance may use up to the configured `poolSize` # of connections. Assuming all of the Sails instances are just copies of one another (a reasonable best practice) we can calculate the actual # of Postgresql connections used (C) by multiplying the configured `poolSize` (P) by the number of Sails instances (N). If the actual number of connections (C) exceeds the total # of **AVAILABLE** connections to your Postgresql database (V), then you have problems.  If this applies to you, try reducing your `poolSize` configuration. A reasonable `poolSize` setting would be V/N.
> 
>  -> Are you using an SSL-enabled Postgresql host like Heroku? Make sure to set `ssl` to `true` (see http://stackoverflow.com/a/22177218/486547)
> 
> 
> A hook (`orm`) failed to load!
> /app/node_modules/async/lib/async.js:43
>             if (fn === null) throw new Error("Callback was already called.");
>                              ^
> 
> Error: Callback was already called.
>     at /app/node_modules/async/lib/async.js:43:36
>     at /app/node_modules/sails/lib/app/private/loadHooks.js:99:18
>     at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:52:16
>     at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:570:21
>     at /app/node_modules/sails-hook-orm/node_modules/async/lib/async.js:167:37
>     at /app/node_modules/sails-hook-orm/lib/initialize.js:389:27
>     at _afterInitializingWaterline (/app/node_modules/sails-hook-orm/lib/build-waterline-ontology.js:99:25)
>     at /app/node_modules/waterline/lib/waterline.js:224:21
>     at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
>     at /app/node_modules/waterline/node_modules/async/lib/async.js:570:21
>     at /app/node_modules/waterline/node_modules/async/lib/async.js:167:37
>     at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
>     at done (/app/node_modules/waterline/node_modules/async/lib/async.js:241:17)
>     at /app/node_modules/waterline/node_modules/async/lib/async.js:44:16
>     at /app/node_modules/waterline/lib/waterline.js:217:27
>     at /app/node_modules/sails-postgresql/node_modules/async/lib/async.js:52:16
>     at /app/node_modules/sails-postgresql/node_modules/async/lib/async.js:361:13
>     at /app/node_modules/sails-postgresql/node_modules/async/lib/async.js:52:16
>     at done (/app/node_modules/sails-postgresql/node_modules/async/lib/async.js:241:17)
>     at /app/node_modules/sails-postgresql/node_modules/async/lib/async.js:44:16
>     at /app/node_modules/sails-postgresql/node_modules/async/lib/async.js:358:17
>     at after (/app/node_modules/sails-postgresql/lib/adapter.js:1289:16)
>     at /app/node_modules/sails-postgresql/lib/adapter.js:1181:7
>     at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:82:27
>     at /app/node_modules/sails-postgresql/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:274:11
>     at /app/node_modules/sails-postgresql/node_modules/pg/lib/pool.js:31:28
>     at Connection.<anonymous> (/app/node_modules/sails-postgresql/node_modules/pg/lib/client.js:176:5)
>     at emitOne (events.js:116:13)

Hope anyone could take a look this issue. Thanks.

Best Regards,
VietNC

**Comment by pantsel** [comment]
@vietwow , check out the FAQ section of README.md
https://github.com/pantsel/konga#faq

**Comment by vietwow** [comment]
It works like a charm. Thank you so much.
