### ISSUE TITLE
Move loader.js and other dependencies to local static file

### ISSUE THREAD

**Issue by flexd** [pantsel/konga#338]
See https://github.com/pantsel/konga/blob/master/views/layout.ejs#L100

I use Konga on a system that does not (and cannot) have access to the internet. 
`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>` makes loading Konga take 10+ seconds for the DNS resolve to timeout every time. It would be great if that file could be pulled into the repo and be served like the other JS assets.

Looks like it is related to Google Charts

**Comment by zengcul** [comment]
I start konga with docker and host in no access to the internet.

I solve the problem in this way:
```
docker exec -it konga bash
vi /app/views/layout.ejs
delete 100 row
```

**Comment by pantsel** [comment]
@zengcul , that is exactly what commit https://github.com/pantsel/konga/commit/8018eb6897c781d971343fbcc3555a66bb3e9637 is doing.

It will be available on the upcoming version.
