### ISSUE TITLE
Doesn't work properly with 1.1.0rc1

### ISSUE THREAD

**Issue by eshepelyuk** [pantsel/konga#346]
Konga doesn't display service and route details popup with 1.1.0rc1

https://discuss.konghq.com/t/kong-1-1-0rc1-available-for-testing/2873

When running KONG without DB in _declarative config_ the popups are not displayed.

**Comment by pantsel** [comment]
@eshepelyuk , haven't had the chance to test with 1.0.1 yet but,
it seems to me that when you run Kong without a db with predefined declarative configuration, the API is useless to start with. So it seems to me, Konga has no place in that setup.

Again, I haven't tested it yet. Will do and post an update.

**Comment by eshepelyuk** [comment]
Hello @pantsel 

>  haven't had the chance to test with 1.0.1 yet 

I think there's a typo - version is `1.1.0`, currently RC1

> It seems to me that Konga has no place in that particular setup except maybe to visualize your configuration?.

I could agree with you on this point, but visualization should at least work.
Moreover, I assume `Kong` in future may support a mixed mode, when predefined config can be modified in memory via API, so `Konga` will be extremely handy in that case too.

**Comment by pantsel** [comment]
@eshepelyuk ,
Just tested Konga with Kong 1.1.0rc1.
It seems that everything is working fine when running KONG without DB in declarative config.

The only thing ofc is that you can't update/delete anything.

What popups are not displayed on your end?

When for example I'm on the services list page and click on a service, I get directed to the service details page and everyhting is displaying correctly.

**Comment by eshepelyuk** [comment]
When I'm on service (routes, plugins etc) page and click on any element to see details - I observe 404 in browser.

**Comment by pantsel** [comment]
@eshepelyuk , what version of Konga are you using?

**Comment by eshepelyuk** [comment]
@pantsel `0.14.1`
And additionally - services are run in `Docker Swarm`

**Comment by pantsel** [comment]
@eshepelyuk , Im afraid I can't reproduce it with Konga 0.14.3.

Can you try and see if it works with `konga:latest`?
 
Check [Konga's demo instance](http://139.59.145.231:1337).
I temporarily made it use the db-less configuration.

Kong 1.1.0rc1
Konga 0.14.3

username: demo
pass: demodemodemo

Kong entity details pages are working with no probs

**Comment by eshepelyuk** [comment]
@pantsel  Tried 0.14.3 - the same issue.

**Comment by pantsel** [comment]
Have you checked the demo instance?

**Comment by eshepelyuk** [comment]
Sure

**Comment by pantsel** [comment]
It's working there. 
So the problem must be something else.

What happens if you try to get `/services/7e19ff91-a43e-449a-88ce-1105e57b74cc` directly from Kong?

**Comment by eshepelyuk** [comment]
Ok I see the issue in `Konga` 
In the list of displayed services, UUIDs are not mathced to UUIDs of actual services. ( I checked by directly calling Kong)
I just can't understand where those UUIDs are taken from.
So obviously - when clicking on the service - I receive 404.

**Comment by pantsel** [comment]
Also try listing the services and check if the UUIDs  match, directly from Kong's API.

**Comment by eshepelyuk** [comment]
@pantsel I got the reason. 

We have KONG in scaled mode, so there's a several kong instances.
Since there's no central DB - UUID of the same service is different on each of Kong instance.

So basically the bug is 
1. When displaying list of services - the 1st (for exmaple) instance of Kong is contacted (via round robin LB)
2. when clicking on particular service - 2nd instance is contacted (because of RR LB)

I have a suggestion for this 
1. if `name` is declared fro a service/route etc - use the name for creating a details link, if `name` not declared - use UI
2. provide a new setting that will switch on / off this behaviour.

What do you think ?

**Comment by pantsel** [comment]
@eshepelyuk , if you are scaling Kong, wouldn't you need to have a shared fs as well with your declarative configuration?. Same as having a db. All instances must share the same storage/declarative config.

Apart from that, what happens with the Entities like `certificates` that do not have a `name` attribute?

> PS: it also could be good for Konga to detect read-only mode and hide button plus provide corresponding announcement to the users. But this may be a separate task.

That is true, and I'm working on implementing the new Kong 1.1.0rc1 features as we speak.

**Comment by eshepelyuk** [comment]
@pantsel unfortunately we didn't yet implemented shared FS / docker volume. Instances are configured separately :(

OK, it seems the issue is just specific to our setup, so I would close it. 

Agree ?

**Comment by pantsel** [comment]
@eshepelyuk , It's up to you.

For now, I'll play around with the new Kong features while implementing the needed changes in Konga. I'll also try to replace the UUID  with the name when available and see what happens in different setups.

Will keep you posted.

**Comment by eshepelyuk** [comment]
@pantsel Thanks for your help and patience.
