### ISSUE TITLE
does konga support cassandra or can we integrate cassandra

### ISSUE THREAD

**Issue by adarshcr1** [pantsel/konga#349]
hey ,
i am new to this kong environment.
i  was trying to bought up kong and  postgresql  in ubuntu machine.
both are running now
i installed latest npm ,nodejs and sailsjs .
i tried to install konga by cloning but there are some deprecation errors
and do we need to install  bower  and  gulp  as both are installing in deprecated errors.

once konga is up .   i need to replace postgresql to cassandra. as we are working on cassandra and kong.

Thank you

adarsh

**Comment by pantsel** [comment]
Nope, Konga does not support Cassandra at this point. 
Maybe on a future release - generation that feature will be added.

The deprecation errors have no impact on Konga. And are something that we will have to do with for now.
