### ISSUE TITLE
npm start  ???  .env . ???

### ISSUE THREAD

**Issue by YJdevops** [pantsel/konga#354]
npm ERR! Linux 3.10.0-693.2.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! kongadmin@0.13.0 start: `node --harmony app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kongadmin@0.13.0 start script 'node --harmony app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kongadmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kongadmin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kongadmin
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/konga-0.13.0/npm-debug.log

**Comment by pantsel** [comment]
Try running npm install first

**Comment by YJdevops** [comment]
> 首先尝试运行npm install

ok，I do  now

**Comment by YJdevops** [comment]
> Try running npm install first

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.

 -> Do you have multiple Sails instances sharing the same Postgresql database? Each Sails instance may use up to the configured `poolSize` # of connections. Assuming all of the Sails instances are just copies of one another (a reasonable best practice) we can calculate the actual # of Postgresql connections used (C) by multiplying the configured `poolSize` (P) by the number of Sails instances (N). If the actual number of connections (C) exceeds the total # of **AVAILABLE** connections to your Postgresql database (V), then you have problems.  If this applies to you, try reducing your `poolSize` configuration. A reasonable `poolSize` setting would be V/N.

 -> Are you using an SSL-enabled Postgresql host like Heroku? Make sure to set `ssl` to `true` (see http://stackoverflow.com/a/22177218/486547)



Error creating a connection to Postgresql using the following settings:
 postgresql://localhost:5432/konga?host=10.100.1.116&port=5432&schema=true&ssl=false&adapter=sails-postgresql&user=kong&password=kong&database=kong&poolSize=10&identity=postgres

* * *
Complete error details:
 { error: password authentication failed for user "root"
    at Connection.parseE (/usr/local/konga-0.13.0/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/usr/local/konga-0.13.0/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/usr/local/konga-0.13.0/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 93,
  severity: 'FATAL',
  code: '28P01',

**Comment by YJdevops** [comment]
> Try running npm install first

I'm done, and then under / Konga NPM start... Error.

**Comment by YJdevops** [comment]
> Try running npm install first

I installed Konga from clone on GitHub in NPM mode. Do you know the specific operation after clone is finished?

**Comment by pantsel** [comment]
Man, the error speaks for itself. You also need to provide a password for the user 'root' in order to connect to the db

**Comment by pantsel** [comment]
It's all in the README.md.

**Comment by YJdevops** [comment]
> It's all in the README.md.

I didn't configure anything for root. I go directly to git clone to Konga and how do I operate it? Can you elaborate? The operation below CentOS 7.4. Do not know the specific steps? With detailed installation documentation, you can send email or wechat

**Comment by YJdevops** [comment]
> It's all in the README.md.

cp   .env_example   .env

vim .env

 PORT=1337
NODE_ENV=production
KONGA_HOOK_TIMEOUT=120000
DB_ADAPTER=postgres
DB_URI=postgresql://localhost:5432/konga
KONGA_LOG_LEVEL=warn
TOKEN_SECRET=some_secret_token

**Comment by pantsel** [comment]
https://github.com/pantsel/konga/blob/master/README.md#installation check it out.

**Comment by pantsel** [comment]
Ok so you run npm install and then npm start and you get that databasw error you posted before?

**Comment by YJdevops** [comment]
I'll talk about my installation steps. I'll go straight to git clone Konga and then CD Konga NPM install. Do I need to copy and modify the default env file under that directory? What parameters need to be changed? It feels so hard.

**Comment by YJdevops** [comment]
> Ok so you run npm install and then npm start and you get that databasw error you posted before?

I'll talk about my installation steps. I'll go straight to git clone Konga and then CD Konga NPM install. Do I need to copy and modify the default env file under that directory? What parameters need to be changed? It feels so hard.

**Comment by YJdevops** [comment]
> 好的，你运行npm install然后npm start，你得到之前发布的数据库错误？

yeah yeah ,     npm start    so      echo  error

**Comment by YJdevops** [comment]
> Ok so you run npm install and then npm start and you get that databasw error you posted before?

I Kong is version 0.13.1. Which version should I choose if I pull konga? Today, I picked up version 0.13 of Konga this morning, but I found the startup error.

**Comment by pantsel** [comment]
Man, creating a .env file is optional. Try deleting the .env file and running npm start again. Will Konga start without a db? Also i recommend using the official docker container if installing from source feels hard. Dockert pull pantsel/konga

**Comment by pantsel** [comment]
If youre using Kong 0.13.1 version 0.13 is the correct version. I'll try to reproduce the errors youre getting and get back to you.

**Comment by YJdevops** [comment]
> Man, creating a .env file is optional. Try deleting the .env file and running npm start again. Will Konga start without a db? Also i recommend using the official docker container if installing from source feels hard. Dockert pull pantsel/konga

Do you copy the default env file or create an empty env file? Direct CP. env_example. env? Or? Docker can also be used, but some people will not use it for later maintenance of docker, so they did not choose to install it in the way of docker. All of our databases use postgrsql 9.5.

**Comment by YJdevops** [comment]
kong-community-edition-0.13.1.el7.noarch.rpm

> 如果您使用Kong 0.13.1版本0.13是正确的版本。我会尝试重现你得到的错误并回复你。


kong-community-edition-0.13.1.el7.noarch.rpm
konga-0.13.0.zip
postgresql 9.5 
node -v 8.11

**Comment by YJdevops** [comment]
> If youre using Kong 0.13.1 version 0.13 is the correct version. I'll try to reproduce the errors youre getting and get back to you.

Do you have a Wechat? If there is any, I can add you, so that communication problems can be faster, I have been here and installed for two days without success. Do not know why?

**Comment by pantsel** [comment]
Im not on mobile right now. When i get to a PC ill let you know

**Comment by YJdevops** [comment]
> Im not on mobile right now. When i get to a PC ill let you know

ok 。I first contacted konga, through GitHub you all document, just know the general idea, but the specific operation method is still not. I don't know what to change, what to copy and how to operate it.

**Comment by pantsel** [comment]
OK, I cannot get to Wechat right now but lets get the things from the start.

1. You have a Kong instance up and running (0.13.1)
2. You cloned Konga from the [legacy](https://github.com/pantsel/konga/tree/legacy) branch

Forget about the .env file for now

```
$ git clone https://github.com/pantsel/konga/tree/legacy
$ cd konga
$ npm i
$ npm run bower-deps (just to be sure)
$ npm start
```

What happens?

**Comment by YJdevops** [comment]
> OK, I cannot get to Wechat right now but lets get the things from the start.
> 
> 1. You have a Kong instance up and running (0.13.1)
> 2. You cloned Konga from the [legacy](https://github.com/pantsel/konga/tree/legacy) branch
> 
> Forget about the .env file for now
> 
> ```
> $ git clone https://github.com/pantsel/konga/tree/legacy
> $ cd konga
> $ npm i
> $ npm run bower-deps (just to be sure)
> $ npm start
> ```
> What happens?

I bought the ECS mainframe on Aliyun platform in China and installed Kong with version 0.13.1, which started successfully. Through Yum install-y nodejs nodejs-npm, I installed nodejs and npm, and then I can access Kong normally. Then I pulled Konga CD Konga in Git hub git clone. What configuration file do I need to change after cd? When I installed kong, the name of the account password database was kong. What should I do next?

**Comment by YJdevops** [comment]
CD Konga does not need to change any configuration files in the future?

**Comment by pantsel** [comment]
Lets make sure that it is working first.
For now, don't change anything.

Is it working?

**Comment by YJdevops** [comment]
> 让我们确保它首先工作。
> 现在，不要改变任何东西。
> 
> 它有效吗？

Kong is working properly now and I'm going to do it again in your way.

**Comment by YJdevops** [comment]
> > 让我们确保它首先工作。
> > 现在，不要改变任何东西。
> > 它有效吗？
> 
> Kong现在正在正常工作，我会按照你的方式再做一次。

omg！！！！ very nice       thank  you     thank  you   thank  you

**Comment by pantsel** [comment]
Ok lets move to the .env file now.

If I'm not mistaken you want to use the  postgres you use for Kong as Konga's database as well, right?

**Comment by YJdevops** [comment]
Thank you so much. Because I used to use 0.13 version without. env environment variable, this problem has been bothering me for 2 days, I actually wasted 2 days. Now it's settled. Thank you very much.

**Comment by YJdevops** [comment]
> 好的，我们现在转移到.env文件。
> 
> 如果我没弄错的话你想使用你用作Konga数据库的postgres，对吗？

是都我希望 kong +konga 配合数据库使用

**Comment by YJdevops** [comment]
> Ok lets move to the .env file now.
> 
> If I'm not mistaken you want to use the postgres you use for Kong as Konga's database as well, right?

Yes, I want to use Konga to call my kongdu database.

**Comment by pantsel** [comment]
Listen, It's not mandatory that you use a database for konga as long as the `kongadata` folder is persistant. Konga only stores its own stuff in the database and has nothing to do with Kong whatsoever.

It will still be working this way.

A rule of thumb would be to create a .env file with at least these env vars tho. 

```
NODE_ENV=production
KONGA_HOOK_TIMEOUT=120000
KONGA_LOG_LEVEL=warn
TOKEN_SECRET=some_secret_token // This should be a secret random string
```

Now, if for some reason you really want to use postgress as Konga's DB as well, in your case,
add these lines to your .env file as well

```
DB_ADAPTER=postgres
DB_URI=postgresql://<your-postgres-db-host>:<your-postgres-db-port>/konga?user=<your-db-user>&password=<your-db-pass>
```
Based on the error you posted before, your db user and pass is kong / kong.

**Comment by YJdevops** [comment]
> 听，只要`kongadata`文件夹是持久的，就不一定要为konga使用数据库。Konga只在数据库中存储自己的东西，与Kong无关。
> 
> 它仍将以这种方式工作。
> 
> 一个经验法则是创建一个至少包含这些env vars的.env文件。
> 
> ```
> NODE_ENV=production
> KONGA_HOOK_TIMEOUT=120000
> KONGA_LOG_LEVEL=warn
> TOKEN_SECRET=some_secret_token // This should be a secret random string
> ```
> 现在，如果由于某种原因你真的想将postgress用作Konga的DB，在你的情况下，
> 也要将这些行添加到你的.env文件中
> 
> ```
> DB_ADAPTER=postgres
> DB_URI=postgresql://<your-postgres-db-host>:<your-postgres-db-port>/konga?user=<your-db-user>&password=<your-db-pass>
> ```
> 根据您之前发布的错误，您的db用户和pass是kong / kong。

I just follow your installation visit, but it hasn't changed. env, can I use it now?

**Comment by YJdevops** [comment]
DB_ADAPTER=postgres
DB_URI=postgresql://localhost:5432/konga?user=kong&password=kong       

> > 听，只要`kongadata`文件夹是持久的，就不一定要为konga使用数据库。Konga只在数据库中存储自己的东西，与Kong无关。
> > 它仍将以这种方式工作。
> > 一个经验法则是创建一个至少包含这些env vars的.env文件。
> > ```
> > NODE_ENV=production
> > KONGA_HOOK_TIMEOUT=120000
> > KONGA_LOG_LEVEL=warn
> > TOKEN_SECRET=some_secret_token // This should be a secret random string
> > ```
> > 现在，如果由于某种原因你真的想将postgress用作Konga的DB，在你的情况下，
> > 也要将这些行添加到你的.env文件中
> > ```
> > DB_ADAPTER=postgres
> > DB_URI=postgresql://<your-postgres-db-host>:<your-postgres-db-port>/konga?user=<your-db-user>&password=<your-db-pass>
> > ```
> > 根据您之前发布的错误，您的db用户和pass是kong / kong。
> 
> I just follow your installation visit, but it hasn't changed. env, can I use it now?

DB_ADAPTER=postgres
DB_URI=postgresql://localhost:5432/konga?user=kong&password=kong 

are  you    right ?

**Comment by pantsel** [comment]
yes, try that

**Comment by YJdevops** [comment]
![image](https://user-images.githubusercontent.com/37797820/54416840-7b5f5a80-473b-11e9-8253-1625de2341d1.png)
I added one. Why can't I find this data in the library? Which table is it in?

**Comment by pantsel** [comment]
What do you mean? I don't undestand.

**Comment by YJdevops** [comment]
![image](https://user-images.githubusercontent.com/37797820/54417134-41428880-473c-11e9-9850-cdbac94d648f.png)
Another question I want to ask is that I now have a production environment Konga access ip: port, prompt me this question. Error "Neat! Your account is activated." I went through NPM run bower-deps and restarted it to no avail.

> 你什么意思？我不明白。

That is, I added a piece of data, which could not be found in my database.

**Comment by pantsel** [comment]
Have you changed Konga's port to 1338 from the .env file?

**Comment by YJdevops** [comment]
This Konga is a file I installed before, No. env or default. env....

**Comment by YJdevops** [comment]
![image](https://user-images.githubusercontent.com/37797820/54418052-bd3dd000-473e-11e9-8a71-c7b84346425c.png)

**Comment by pantsel** [comment]
It seems that you're missing files. Plus the bower deps are not installed.
Also, why port 1338 and not 1337?

**Comment by YJdevops** [comment]
> 看来你丢失了文件。另外没有安装凉亭设备。
> 另外，为什么端口1338而不是1337？

I'm not sure. Now both my database and Kong are running ing in the production environment. Would it affect the normal operation of my database and Kong if we deal with the problem of this web interface display now?

**Comment by pantsel** [comment]
No, Konga doesn't affect Kong that way.

**Comment by YJdevops** [comment]
> 不，Konga不会影响Kong。
So now I'm going to fix the problem of this visit. How do I fix it? Start git clone again?

**Comment by pantsel** [comment]
Yes, try doing everything from scratch and see what happens....

**Comment by YJdevops** [comment]
And the question just now, how can I start from the background with NPM start? Can it be started by PM2 start app. js?

**Comment by YJdevops** [comment]
> 是的，尝试从头开始做一切，看看会发生什么......

And the question just now, how can I start from the background with NPM start? Can it be started by PM2 start app. js?

**Comment by pantsel** [comment]
yes, you can use PM2

**Comment by YJdevops** [comment]
Find the file ecosystem. config. JS in the directory. Start ecosystem. config. JS directly. All processes including services are started?

> 是的，你可以使用PM2。
> 
> `ecosystem.config.js`如果您熟悉PM2，也可以使用该文件。

Find the file ecosystem. config. JS in the directory. Start ecosystem. config. JS directly. All processes including services are started?

**Comment by pantsel** [comment]
logically

**Comment by YJdevops** [comment]
> logically

what  ？  yes  run ？  or   no    not run ？

**Comment by YJdevops** [comment]
![image](https://user-images.githubusercontent.com/37797820/54420108-19efb980-4744-11e9-81b6-5037149f931e.png)

**Comment by YJdevops** [comment]
> logically

**Comment by pantsel** [comment]
The error says what's the problem

**Comment by YJdevops** [comment]
> 错误说明问题是什么

node 8.0 +++ ??

**Comment by YJdevops** [comment]
![image](https://user-images.githubusercontent.com/37797820/54420581-51ab3100-4745-11e9-96de-ab7942e10d69.png)
![image](https://user-images.githubusercontent.com/37797820/54420597-62f43d80-4745-11e9-84bb-8d7a71b713fb.png)

**Comment by pantsel** [comment]
yes.
Also, you are using Konga 0.14.3 which is NOT compatible with Kong < 1.
If your Kong is 0.13.1 you will need to use the [legacy](https://github.com/pantsel/konga/tree/legacy) branch as we said before.

**Comment by pantsel** [comment]
open the js console and post the errors. Propably the bower deps didnt got installed.

**Comment by YJdevops** [comment]
![image](https://user-images.githubusercontent.com/37797820/54420726-c3837a80-4745-11e9-95b9-14a93dbb10ed.png)
![image](https://user-images.githubusercontent.com/37797820/54420742-cb431f00-4745-11e9-91ba-21eb2d0329a2.png)

**Comment by YJdevops** [comment]
![image](https://user-images.githubusercontent.com/37797820/54420783-eada4780-4745-11e9-83fe-6165d01fdb63.png)

**Comment by YJdevops** [comment]
> 错误说明问题是什么

**Comment by pantsel** [comment]
have you run npm install in konga's folder?

**Comment by YJdevops** [comment]
yeah

**Comment by YJdevops** [comment]
> 你在konga的文件夹中运行npm install吗？


yes

**Comment by pantsel** [comment]
try running npm rebuild node-sass
and then starting the project again

**Comment by YJdevops** [comment]
> 尝试运行`npm rebuild node-sass`以构建当前环境的绑定（因为您更改了节点版本）
> ，然后再次启动项目

![image](https://user-images.githubusercontent.com/37797820/54421483-83bd9280-4747-11e9-9f2f-b9e457fad230.png)
very good    hahahahha  thank you  Thank you very much for your help. I will keep an eye on your github.

**Comment by pantsel** [comment]
Glad to be of help man.

One last thing, this is Konga 0.14.3 you have installed.

Remember, it's only compatible with Kong > 1.

**Comment by YJdevops** [comment]
ok，thank you  bye

**Comment by dplbiz** [comment]
When I follow you steps and I get these errors: 
../../nan/nan.h:2337:3: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>)’
   recv->Set(name, GetFunction(tpl).ToLocalChecked());
   ^
In file included from /home/ubuntu/.node-gyp/13.0.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/binding.cpp:1:
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3416:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3416:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3419:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/home/ubuntu/.node-gyp/13.0.1/include/node/v8.h:3419:37: note:   candidate expects 3 arguments, 2 provided
binding.target.mk:129: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/ubuntu/homecca/konga/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/homecca/konga/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-1092-aws
gyp ERR! command "/usr/bin/node" "/home/ubuntu/homecca/konga/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/ubuntu/homecca/konga/node_modules/node-sass
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-11-16T02_04_04_828Z-debug.log

**Comment by infoloft** [comment]
Try nodejs max version 10.x.x

**Comment by allenjol** [comment]
hello, @pantsel ！ when i use konga:0.14.9 and try to install konga in kubernetes，when i use initContainers ,there have something wrong about:
```
-> Is your Postgresql configuration correct? Maybe your poolSize configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your poolSize set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default poolSize is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in config/connections.js, or wherever your environment-specific database configuration is set.

-> Maybe your poolSize configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your poolSize set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default poolSize is 10.

-> Do you have multiple Sails instances sharing the same Postgresql database? Each Sails instance may use up to the configured poolSize # of connections. Assuming all of the Sails instances are just copies of one another (a reasonable best practice) we can calculate the actual # of Postgresql connections used (C) by multiplying the configured poolSize (P) by the number of Sails instances (N). If the actual number of connections (C) exceeds the total # of AVAILABLE connections to your Postgresql database (V), then you have problems. If this applies to you, try reducing your poolSize configuration. A reasonable poolSize setting would be V/N.

-> Are you using an SSL-enabled Postgresql host like Heroku? Make sure to set ssl to true (see http://stackoverflow.com/a/22177218/486547)
```

May I ask how this is going on and how to solve it？thank you！

**Comment by allenjol** [comment]
my kubernetes manifests initContainers is:
```
      initContainers:
        - name: init-konga
          image: pantsel/konga:0.14.9
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/bin/konga.js
            - -c
            - prepare
            - -a
            - postgres
            - -u
            - postgres://kong:my_kong_password@my_ipaddress:5432/konga
```
