### ISSUE TITLE
MySQL adapter not working

### ISSUE THREAD

**Issue by coagent** [pantsel/konga#36]
2017/3/30 下午4:35:28User had models, so no seed needed
2017/3/30 下午4:35:28A hook (`load-db`) failed to load!
2017/3/30 下午4:35:28Error (E_UNKNOWN) :: Encountered an unexpected error
2017/3/30 下午4:35:28: ER_NO_SUCH_TABLE: Table 'konga.konga_users' doesn't exist
2017/3/30 下午4:35:28    at Query.Sequence._packetToError (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
2017/3/30 下午4:35:28    at Query.ErrorPacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
2017/3/30 下午4:35:28    at Protocol._parsePacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
2017/3/30 下午4:35:28    at Parser.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
2017/3/30 下午4:35:28    at Protocol.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2017/3/30 下午4:35:28    at Socket.<anonymous> (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
2017/3/30 下午4:35:28    at emitOne (events.js:96:13)
2017/3/30 下午4:35:28    at Socket.emit (events.js:191:7)
2017/3/30 下午4:35:28    at readableAddChunk (_stream_readable.js:176:18)
2017/3/30 下午4:35:28    at Socket.Readable.push (_stream_readable.js:134:10)
2017/3/30 下午4:35:28    at TCP.onread (net.js:563:20)
2017/3/30 下午4:35:28    --------------------
2017/3/30 下午4:35:28    at Protocol._enqueue (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
2017/3/30 下午4:35:28    at PoolConnection.query (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
2017/3/30 下午4:35:28    at __FIND__ (/app/node_modules/sails-mysql/lib/adapter.js:838:20)
2017/3/30 下午4:35:28    at afterwards (/app/node_modules/sails-mysql/lib/connections/spawn.js:84:5)
2017/3/30 下午4:35:28    at /app/node_modules/sails-mysql/lib/connections/spawn.js:40:7
2017/3/30 下午4:35:28    at Ping.onOperationComplete [as _callback] (/app/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:99:5)
2017/3/30 下午4:35:28    at Ping.Sequence.end (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
2017/3/30 下午4:35:28    at Ping.Sequence.OkPacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
2017/3/30 下午4:35:28    at Protocol._parsePacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
2017/3/30 下午4:35:28    at Parser.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
2017/3/30 下午4:35:28    at Protocol.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2017/3/30 下午4:35:28    at Socket.<anonymous> (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
2017/3/30 下午4:35:28    at emitOne (events.js:96:13)
2017/3/30 下午4:35:28    at Socket.emit (events.js:191:7)
2017/3/30 下午4:35:28    at readableAddChunk (_stream_readable.js:176:18)
2017/3/30 下午4:35:28    at Socket.Readable.push (_stream_readable.js:134:10)
2017/3/30 下午4:35:28    at TCP.onread (net.js:563:20)
2017/3/30 下午4:35:28
2017/3/30 下午4:35:28Details:  Error: ER_NO_SUCH_TABLE: Table 'konga.konga_users' doesn't exist

**Comment by pantsel** [comment]
Hi @coagent,
You need to create the mysql table manually the first time.

**Comment by coagent** [comment]
@pantsel Thank you for your response, how to do that? can you share the sql script?

**Comment by pantsel** [comment]
Don't you have a db managing tool like phpMyAdmin or HeidiSQL for example? 
It can make your life easier.

If you don't : 

<code> CREATE DATABASE konga </code>

**Comment by coagent** [comment]
@pantsel I have created the konga database and db user, and set the environment variables for mysql adapter, ie DB_HOST, DB_PORT, DB_PORT, DB_PASSWORD, DB_DATABASE.

**Comment by pantsel** [comment]
Can you try deleting the database and restarting Konga with the same env variables?

**Comment by pantsel** [comment]
I have just tested it on my pc and it seems to work,,,

**Comment by coagent** [comment]
I delete the database and restart konga, the error messages as below:

2017/3/30 下午5:21:47User had models, so no seed needed
2017/3/30 下午5:21:47A hook (`load-db`) failed to load!
2017/3/30 下午5:21:47Error (E_UNKNOWN) :: Encountered an unexpected error
2017/3/30 下午5:21:47: Could not connect to MySQL:
2017/3/30 下午5:21:47Error: ER_BAD_DB_ERROR: Unknown database 'konga'
2017/3/30 下午5:21:47    at afterwards (/app/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
2017/3/30 下午5:21:47    at /app/node_modules/sails-mysql/lib/connections/spawn.js:40:7
2017/3/30 下午5:21:47    at Handshake.onConnect [as _callback] (/app/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:54:9)
2017/3/30 下午5:21:47    at Handshake.Sequence.end (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
2017/3/30 下午5:21:47    at Handshake.ErrorPacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
2017/3/30 下午5:21:47    at Protocol._parsePacket (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
2017/3/30 下午5:21:47    at Parser.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
2017/3/30 下午5:21:47    at Protocol.write (/app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2017/3/30 下午5:21:47    at Socket.<anonymous> (/app/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
2017/3/30 下午5:21:47    at emitOne (events.js:96:13)
2017/3/30 下午5:21:47    at Socket.emit (events.js:191:7)
2017/3/30 下午5:21:47    at readableAddChunk (_stream_readable.js:176:18)
2017/3/30 下午5:21:47    at Socket.Readable.push (_stream_readable.js:134:10)
2017/3/30 下午5:21:47    at TCP.onread (net.js:563:20)
2017/3/30 下午5:21:47
2017/3/30 下午5:21:47Details:  Error: Could not connect to MySQL:
2017/3/30 下午5:21:47Error: ER_BAD_DB_ERROR: Unknown database 'konga'

and then, I create the database in MySQL and restarting Konga, I will get same error message:

Error: ER_NO_SUCH_TABLE: Table 'konga.konga_users' doesn't exist

**Comment by pantsel** [comment]
<code>Error: ER_BAD_DB_ERROR: Unknown database 'konga'</code> = The database doesn't exist

Sorry, i wasn't clear.

What I meant was delete the database, recreate it manually and restart Konga,

Sorry again...

**Comment by coagent** [comment]
It works now. I made following operation:

1. on another server, install npm..., git pull konga code, npm install ...etc.
2. run npm start, and then stop it. 【It will create three tables: konga_kong_nodes, konga_passports, konga_users】
3. restart konga container
4. done!

Thanks again, @pantsel .

**Comment by pantsel** [comment]
@coagent,
Thanks for the feedback. This issue is explained with more details at #40 for future reference.
