### ISSUE TITLE
Kong 1.1 Compatibility

### ISSUE THREAD

**Issue by MichelinMan** [pantsel/konga#362]
Hi,

I have upgraded Kong to version 1.1.0 and running Konga from the vastest commit in master and I am getting these type of errors:

Nothing else has changed apart from upgrading Kong from 1.0 -> 1.1 which makes me wonder if that breaks Konga.

Thank you,
Ioannis

    error: Sending 500 ("Server Error") response: 
     { error:
       { Error: socket hang up
           at createHangUpError (_http_client.js:330:15)
           at Socket.socketOnEnd (_http_client.js:431:23)
           at Socket.emit (events.js:198:15)
           at Socket.EventEmitter.emit (domain.js:481:20)
           at endReadableNT (_stream_readable.js:1142:12)
           at processTicksAndRejections (internal/process/task_queues.js:81:17) code: 'ECONNRESET' } }

**Comment by pantsel** [comment]
@MichelinMan , Konga is fully compatible with Kong 1.1.0.
At what point are you getting this error?
As far as I can tel, it has something to do with server connections `ECONNRESET`.
Are you sure that Kong's admin API is accepting connections normally?

Can you hit it via a `curl` or postman with the same connection url as you've used in Konga?

**Comment by MichelinMan** [comment]
I am so sorry, I should have checked the admin API with curl before rushing to open an issue. Yup, I get a `http: error: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing GET request to URL: http://localhost:8001/
` so its my environment. I am closing down this issue. Apologies again for the noise, Ioannis
