### ISSUE TITLE
cannot add custom plugin for all apis as global plugin

### ISSUE THREAD

**Issue by CarlZhu93** [pantsel/konga#38]
![image](https://cloud.githubusercontent.com/assets/23279571/24540597/7cc66f00-1626-11e7-90f3-cf0b9005af45.png)

I try to add these custom plugin as global plugin, but the konga do not have entry for that.
By the way, I can do this with the origin kong admin plugins api. 
is there any solution for it?

**Comment by pantsel** [comment]
Hi @CarlZhu93,

As I see in your screenshot the plugins are marked blue, therefore already added.

If I understood correctly, you mean that they are not shown in the plugins list?

Are those plugins listed on the dashboard, inside the plugins panel?

**Comment by CarlZhu93** [comment]
Hi @pantsel ,

Actually, there are two kinds of blue. As you can see, the RequestId Allocation plugin is lighter. What is the different ?

I have used the Plugins Admin api (POST :8001/plugins) to add RequestId Allocation plugins as 
global plugin, so in the screenshot, it is global plugin already. 

By the way, the plus sign did not appeal throughout for those custom plugins when I try to add them as global plugin, but did appeal when I try to add them for single api. 

![image](https://cloud.githubusercontent.com/assets/23279571/24573773/ab7bac90-16ba-11e7-9cd9-3c80872c5270.png)

yes, they are inside the plugins panel.

![image](https://cloud.githubusercontent.com/assets/23279571/24573869/9ada3da0-16bc-11e7-84f9-6b272cef3e53.png)

**Comment by pantsel** [comment]
Hi @CarlZhu93 and sorry for the late response. It seems that the plugins are already added globally. The difference between the blues is that the Request Allocation plugin is not activated while the Signature plugin is.
