### ISSUE TITLE
Snapshot file location

### ISSUE THREAD

**Issue by bheller198** [pantsel/konga#388]
Hi what is the default folder directory where snapshots are being stored? I would like store the snapshots in a percested volume with docker volumes. or what would be awesome to have a feature to automatically email the snapshots with a scheduled task!

Thanks so much. Konga is a huge lifesaver!

**Comment by bheller198** [comment]
Or I guess any pointers on how konga stores scheduled snapshots?

**Comment by pantsel** [comment]
@bheller198 , sorry for the late response. The snapshots are stored in Konga's database in the `konga_kong_snapshots` table/collection

**Comment by bheller198** [comment]
Perfect! Thank you
