### ISSUE TITLE
Is there a way to take back up of API's configured on Konga?

### ISSUE THREAD

**Issue by ksachdeva11** [pantsel/konga#39]
Can we take the back up API's configured? So that we can directly apply the back up on some other system and no need to add the API's again..

**Comment by pantsel** [comment]
Hi @ksachdeva11 ,

right now there is no way you can do that from the GUI. You can backup Kong's database instead and get the API's from there.

Nevertheless, this sounds like a nice feature. I'll give it some thought and see if and how it could be implemented.

Thanks for the feedback.

**Comment by ksachdeva11** [comment]
Thanks @pantsel !

**Comment by pantsel** [comment]
@ksachdeva11 ,

check out the new release https://github.com/pantsel/konga/releases/tag/0.6.3
