### ISSUE TITLE
i meet a problem when i login konga

### ISSUE THREAD

**Issue by bruse-peng** [pantsel/konga#390]
i meet a problem when i click some meue  it show "size must be an integer between 1 and 1000"  how i shoul resolve it. i install konga on k8s

below is the error information
![image](https://user-images.githubusercontent.com/47881861/58856071-2f85d700-86d4-11e9-9d75-d3eac7ec6c7b.png)

**Comment by bruse-peng** [comment]
[root@k8s-master-240-16 kong-dist-kubernetes]# kubectl logs konga-5bb944ffb9-xrptb
Using postgres DB Adapter.
Database exists. Continue...
debug: Hook:api_health_checks:process() called
debug: Hook:health_checks:process() called
debug: Hook:start-scheduled-snapshots:process() called
debug: Hook:user_events_hook:process() called
debug: User had models, so no seed needed
debug: No data avaliable to seed Kongnode
debug: Emailtransport seeds updated
debug: -------------------------------------------------------
debug: :: Tue Jun 04 2019 14:20:24 GMT+0000 (UTC)
debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
debug: KongProxyController:req.method GET
debug: KongProxyController:req.url 
debug: KongProxyController:entity null
debug: Kong admin url => http://kong-admin:8001
debug: KongProxyController:req.method GET
debug: KongProxyController:req.url /consumers?size=4294967295
debug: KongProxyController:entity consumers
debug: Kong admin url => http://kong-admin:8001
error: KongProxyController request error { name: 'invalid size',
  message: 'size must be an integer between 1 and 1000',
  code: 9 }
debug: KongProxyHooks:afterEntityFetch called() null
debug: KongProxyController:req.method GET
debug: KongProxyController:req.url /plugins?size=4294967295
debug: KongProxyController:entity plugins
debug: Kong admin url => http://kong-admin:8001
error: KongProxyController request error { name: 'invalid size',
  message: 'size must be an integer between 1 and 1000',
  code: 9 }
debug: KongProxyController:req.method GET
debug: KongProxyController:req.url /apis?size=4294967295
debug: KongProxyController:entity apis
debug: Kong admin url => http://kong-admin:8001
error: KongProxyController request error { message: 'Not found' }
[root@k8s-master-240-16 kong-dist-kubernetes]#

**Comment by pantsel** [comment]
@bruse-peng , you need to update Konga to the latest version. What version are you using right now?

**Comment by bruse-peng** [comment]
my version is pantsel/konga:0.13.0

**Comment by bruse-peng** [comment]
@pantsel my version is pantsel/konga:0.13.0

from ShenZhen China

**Comment by pantsel** [comment]
Update to `0.14.3`

**Comment by bruse-peng** [comment]
@pantsel  thank i will try it

谢谢，我试下

**Comment by bruse-peng** [comment]
@pantsel 
no tag of 0.14.3
[root@iZbp10dbm0ldlbjwi3nbc4Z ~]# docker pull pantsel/konga:0.14.3
Trying to pull repository docker.io/pantsel/konga ... 
manifest for docker.io/pantsel/konga:0.14.3 not found
[root@iZbp10dbm0ldlbjwi3nbc4Z ~]#

**Comment by bruse-peng** [comment]
@pantsel  thanks a lot for your advice i update to 0.14.1,it works fine.thanks again

**Comment by bruse-peng** [comment]
@pantsel  hi,pantsel,does kong have some same function with istio.as i find the plugins kubernetes-sidecar-injector, can you offer me the user guide of konga
![image](https://user-images.githubusercontent.com/47881861/59237369-9bb08f80-8c2c-11e9-9ff4-6bc08662f6fe.png)

**Comment by timduhenchanter** [comment]
@pantsel I have seen multiple references to releases above 0.14.1 however both GitHub and DockerHub the latest release is 0.14.1.  Would love to utilize the features referenced in the changelog for 0.14.4 on the branch `next`.  Is `konga:next` ready?

**Comment by pantsel** [comment]
@timduhenchanter , yes. 
An official release will be out in the next couple of days.

In the meantime, you can use `pantsel/konga:next` from Dockerhub with no probs if you need the features.
