### ISSUE TITLE
Unable to create Route

### ISSUE THREAD

**Issue by TylorS** [pantsel/konga#406]
Hello, thanks for such an awesome project. It seems there may be an issue with creating routes. When attempting to create a route from a server, even though I've put values into `hosts` it's saying it is missing. I inspected the network tab to verify it's not being sent with this value. I tested making the same request but with `hosts` in the body from postman and everything worked. Let me know how I can be of more help :smile:

<img width="1680" alt="Screen Shot 2019-07-01 at 10 47 16 AM" src="https://user-images.githubusercontent.com/6282473/60445728-c8354700-9bed-11e9-80e4-f44953d4f725.png">

**Comment by pantsel** [comment]
Hello @TylorS , as it is pointed out on the blue box, you will need to press enter after every host, method or protocol you type so that the value can be registered in the chip component

**Comment by TylorS** [comment]
Oh wow, that went over my head as you can tell. Thanks for pointing this out - everything is working as expected. Thank you!
