### ISSUE TITLE
Need to reset admin user

### ISSUE THREAD

**Issue by aschofie** [pantsel/konga#413]
I have a Kong / Konga installation working well, but a recent laptop meltdown caused the admin credentials to be lost.  I have full access to the postgres DBs comprising the system-- what would happen if I just deleted the konga_users administrator record?  Would that cause Konga to prompt me to create a new administrator, while preserving all other settings (ideal)?

**Comment by aschofie** [comment]
FWIW I deleted the administrator account from kona_users and was prompted to create a new administrator, whereupon I was able to login, activate the kong connection and have everything restored.

**Comment by hxw422** [comment]
Hello aschofie,
   I meet to the same problem, I forget my admin account and password.
   However, I can log into konga DB. Also, I delete admin account record from konga_users table just    like you did ,  but after restart konga service，the record show again automatically. 
   Is there any other method to reset admin account ?

**Comment by dgonzalezc** [comment]
same issue here!!!!!

**Comment by d4rkstar** [comment]
Hello,
have you tried to delete the "password" entry in konga_passports too?

You should delete the user and the secret record (the first from konga_users, the latter from konga_passports).

Regards

**Comment by dgonzalezc** [comment]
Hello,
I try clearing only the konga_users table but it didn't work

What worked for me was:
- delete konga db with root account
- launch konga in dev mode(-e "NODE_ENV=development") to recreate the needed tables like suggested in #40 

thanks for the feedback @d4rkstar

**Comment by d4rkstar** [comment]
Hello @dgonzalezc,
I tested what worked for me before writing my post.

I noticed that is not sufficient to delete the user from konga_users, because that entry is referenced from the other table konga_passports.

however, will try again later to confirm

**Comment by rpxot11** [comment]
Deleting the user from the table konga_users worked for me, but I did this with konga instance still running, and then I refreshed the site and it asked to create a new admin user.
