### ISSUE TITLE
can't create a route kong

### ISSUE THREAD

**Issue by AliShelby** [pantsel/konga#429]
HI everyone
i recently added a service with kong with this command:
curl -v -XPOST \
>   http://localhost:8001/services \
>   -H 'Content-Type: application/json' \
>   -d '{"name":"api1","retries":1,"host":"httpbin.org"}'

and it worked.
now i want to create a route to receive the response for incoming requests and i've used this command:

curl -i -XPOST \
  http://localhost:8001/routes \
  -H 'Content-Type: application/json' \
  -d '{"name":"api1-route", "protocols": ["http", "https"], "methods": ["GET"],"hosts": ["popularowl.com"], "paths": ["/api1"], "strip_path": true, "preserve_host": false, "service": {"id":"873c5cd8-26ff-4dd1-a3a4-e0c48ad72f18"} }'

BUT it gave me this instead of creating a route:
{"strategy":"postgres","message":"schema violation (name: unknown field)","name":"schema violation","fields":{"name":"unknown field"},"code":2}

and it doesn't create a route!
can anyone help please

**Comment by pantsel** [comment]
@AliShelby , what version of Kong/Konga are you using?

**Comment by AliShelby** [comment]
kong version: 0.14.1

**Comment by pantsel** [comment]
**From 0.14.0 onwards, Konga is ONLY compatible with Kong >= 1.0.0**

If you're on an older Kong version , use [this](https://github.com/pantsel/konga/tree/legacy) branch 
or `konga:legacy` from docker hub instead.

It is mentioned in the compatibility section of the README.md

**Comment by AliShelby** [comment]
I'm not using konga for kong 
i write the commands on terminaal ubuntu

**Comment by pantsel** [comment]
Ok then, maybe you got confused. 

This is not Kong's repo. 

This is Konga's one. 

You may want to ask Kong related questions there.

**Comment by AliShelby** [comment]
oh my bad
thanks
