### ISSUE TITLE
Specify ip to listen on

### ISSUE THREAD

**Issue by coldcoff** [pantsel/konga#447]
Hi!

It seems that `konga` is always listening to the configured PORT on 0.0.0.0, i. e. on *all* interfaces / *all* ips of the machine where it is started.

Could you please make the listen adress also configurable?

Thank you.

coldcoff

**Comment by narate** [comment]
hello @coldcoff 
I need that feature too, then I make pull request here https://github.com/pantsel/konga/pull/451

**Comment by pantsel** [comment]
@coldcoff , @narate 's pull req is merged to master and available on the latest version of Konga.

Cheers!
