### ISSUE TITLE
Question: use of Konga API

### ISSUE THREAD

**Issue by gigaga** [pantsel/konga#448]
Firstly, thank you very muck for Konga!
It is a wonderful tool!!

I am implementing to tool to list available services.
Currently, I can do that by using Kong REST API, unfortunately, some fields are not available in Kong but available in Konga (for example, extras data with tags and description was added).
So, rather to use Kong REST API, I'd like to use Konga REST API.
My problem is that I don't found how provided an api key in Authorization header.
From UI, I can see a bearer token but for my tool, I don't know how retrieve a valid token.

Thanks

**Comment by pantsel** [comment]
@gigaga , sorry for the late response.

You can do that by making a `POST` req to `konga-host:port/login` providing the following body
```
{
	"identifier": "username-or-email",
	"password": "your-password"
}
```

**Comment by gigaga** [comment]
Thanks a lot!
;)
