### ISSUE TITLE
Blank page after register for the first time

### ISSUE THREAD

**Issue by WaelMohsen** [pantsel/konga#455]
Dear Konga team,

I appreciate your support to help me with this problem. This is my first setup to Konga. After finishing the installation, the registration page popup to me to add an admin user. I wrote some user information and clicked on the "Register" button. However, once I did that nothing happen after that; just a blank page. Even after many starts to the Konga I have nothing; only an empty page.

If I deleted the user from the DB, the website shows the registration page again, but once I register, I face the same issue.

I don't know if there is an Eventlog file that contains any information that may help in this situation or not. If you know one, please let me know it to help investigate the problem. 

Here is my .env file info:

PORT=1337
NODE_ENV=development
KONGA_HOOK_TIMEOUT=60000
DB_ADAPTER=postgres
DB_HOST=localhost
DB_URI=postgresql://localhost:5432/konga
DB_USER=kong
KONGA_LOG_LEVEL=debug
TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb

Thanks in Advance,

**Comment by dorisnzy** [comment]
Has your problem been solved? I had the same problem

**Comment by pantsel** [comment]
@WaelMohsen ,
can you please open the browser console when you encounter that blank page?

Do you see an error `angular not defined`?

If that is the case try this from the FAQ
https://github.com/pantsel/konga#1-getting-blank-page-with-uncaught-referenceerror-angular-is-not-defined
