### ISSUE TITLE
Use kong tags to configure tags for service object

### ISSUE THREAD

**Issue by kdhttps** [pantsel/konga#465]
From kong 1.1 onwards, they are providing the tags features. Check change list here https://github.com/Kong/kong/blob/master/CHANGELOG.md#admin-api-3

IMO, we should have to remove out **KongService.js** model and update konga for kong >= 1.1

what you think? 

Note: I would like to contribute for this :)

**Comment by pantsel** [comment]
Hi @kdhttps ,

the tags feature is already integrated in the [next](https://github.com/pantsel/konga/tree/next) branch.

https://github.com/pantsel/konga/blob/next/CHANGELOG.md#0144

That branch is actually production ready and it's a matter of me finding time to make a final swipe and merge it to master.

You can check it out if like (`pantsel/konga:next` from docker hub)
