### ISSUE TITLE
Consumer pages malfunctions after install nokia/oidc plugin: "Groups" and "Accessible Routes" disappear, blank "Credentials"

### ISSUE THREAD

**Issue by bevan-li** [pantsel/konga#469]
Steps to reproduce:
1. docker compose postgresql:9.6, kong:1.2.0-centos, pantsel/konga:0.14.1 (NODE_ENV: production)
2. git clone https://github.com/harmoney-dev/kong-oidc.git /usr/local/share/lua/5.1/kong/plugins/oidc
cd /usr/local/share/lua/5.1/kong/plugins/oidc 
luarocks make *.rockspec
3. open /docker-entrypoint.sh, add "export KONG_PLUGINS=oidc"

The plugin in works well, but the Consumer pages malfunctions
Thanks

**Comment by bevan-li** [comment]
I find the the problem is when use KONG_PLUGINS environment variable, either in docker-compose or in docker-entrypoint.sh, all the built-in plugins are disappear

**Comment by bevan-li** [comment]
I figured out the issue: I need to add "bundled" keyword

**Comment by bevan-li** [comment]
close as the comments above

**Comment by vincentmarkcelino** [comment]
does kong-oidc showing in your plugin list? mine is not showing. i followed the documentation but its not working
