### ISSUE TITLE
When I register  administrator after the to jump to the page is a blank page, how do I need to solve?

### ISSUE THREAD

**Issue by dorisnzy** [pantsel/konga#470]
![image](https://user-images.githubusercontent.com/29443984/66805614-044fa600-ef58-11e9-9b3f-517122d6d357.png)

**Comment by pantsel** [comment]
@dorisnzy ,

Are you installing Konga from source?

Try this solution stated on the FAQ:

https://github.com/pantsel/konga#1-getting-blank-page-with-uncaught-referenceerror-angular-is-not-defined

**Comment by dorisnzy** [comment]
Yes, I used the source code installation and used nginx as a proxy.

**Comment by pantsel** [comment]
@dorisnzy , have you tried the above solution?

**Comment by dorisnzy** [comment]
Yes, I installed it according to readme.md

**Comment by pantsel** [comment]
@dorisnzy ,

have you tried running `npm run bower-deps` ?

**Comment by dorisnzy** [comment]
Thank you very much for your help, I can successfully log in after running npm `run bower-deps`.

**Comment by pantsel** [comment]
cheers
