### ISSUE TITLE
cannot create router 

### ISSUE THREAD

**Issue by huizluo** [pantsel/konga#484]
i haved created a service ,now i want create a router for this sevice, i entry all param,but cannot create,server return this response that "schema violation (must set one of 'methods', 'hosts', 'headers', 'paths', 'snis' when 'protocols' is 'https'"

**Comment by huizluo** [comment]
use docker images run

**Comment by Rookie-Zmy** [comment]
I get same problem! 
Have you solved?

**Comment by Rookie-Zmy** [comment]
Hi, @huizluo , I found it,   #258 . The issue has solved the problem!
