### ISSUE TITLE
ACL plugin validation bug

### ISSUE THREAD

**Issue by taranvohra** [pantsel/konga#486]
I have a defined Service which has a route. I want to add `key-auth` plugin to that Service. When I try to add Consumer ID, it says **field should be null**. If i keep it empty, it adds it for all Consumers that exist. Why is it that way? Why can't I have it for specific Consumer?

**Comment by taranvohra** [comment]
**UPDATE**
Okay, I figured I needed to add an ACL to the Service and ensure the Consumer is in the group that I want to whitelist. However whenever I keep getting this error when I try to whitelist groups in the ACL plugin.

![Screenshot 2019-10-31 at 12 14 42 PM](https://user-images.githubusercontent.com/8937991/67925067-4293c900-fbd8-11e9-8eb7-a34ccb1324e4.png)

How is it possible? I have `foo` in whitelist and nothing in blacklist. This should satisfy the validation rule however it still gives me error!

**Comment by taranvohra** [comment]
I opened DevTools and noticed even though I am providing `foo` to whitelist, the `config` object in the request is EMPTY!
![image](https://user-images.githubusercontent.com/8937991/67926308-b5527380-fbdb-11e9-8e70-882e5a40916c.png)

**Comment by alvindaiyan** [comment]
I encountered the same issue, can anyone help?

**Comment by pantsel** [comment]
Guys, did you press enter after typing the value in the whitelist? There's a chip component handling array like structures.

**Comment by taranvohra** [comment]
@pantsel yes I did. Have a re look at this screenshot. `foo` is entered (chip is there) but when I submit, I still get an error. 

![67925067-4293c900-fbd8-11e9-8eb7-a34ccb1324e4](https://user-images.githubusercontent.com/8937991/68569419-08ea7a00-0484-11ea-8984-358c96736eec.png)

**Comment by pantsel** [comment]
What version of Konga are you using?

**Comment by alvindaiyan** [comment]
I'm using the next version from Dockerhub

**Comment by taranvohra** [comment]
next version from DockerHub

**Comment by pantsel** [comment]
Fixed the bug on `next`. Doing some extra tests and moving it to prod
