### ISSUE TITLE
Can't edit consumer/api with custom user

### ISSUE THREAD

**Issue by d3rwan** [pantsel/konga#49]
Using a custom user (administrator), it's impossible to edit api/consumer. Creation and deletion are always possible. 
It seems that it's due to the absence of node_id in custom user (while it's equal to 'http://kong:8001' for default user).
As a result, the NodeService.isActiveNodeSet method rejects the returned promise

**Comment by pantsel** [comment]
@d3rwan , thanks for the feedback. I'll get to it asap!

**Comment by pantsel** [comment]
@d3rwan , If you want to get over this manually before I have a fix ready and commited, replace NodeService methods with this

<pre>
                   activeNode : function() {
                        return $localStorage.credentials.user.node
                    },
                    authorize: function authorize(needsActiveNode) {
                        if(needsActiveNode)
                            return $localStorage.credentials && $localStorage.credentials.user.node
                        return true;
                    },
                    isActiveNodeSet : function() {
                        var defer = $q.defer()

                        if($localStorage.credentials.user.node){
                            defer.resolve($localStorage.credentials.user.node.id)
                        }else{
                            $state.go('settings')
                            defer.reject("No active nodes found")

                        }
                        return defer.promise
                    }
</pre>

**Comment by pantsel** [comment]
@d3rwan , check out the latest commit

**Comment by d3rwan** [comment]
@pantsel it works ! Thanks for your responsiveness
