### ISSUE TITLE
 cannot create 'services' entities when not using a database

### ISSUE THREAD

**Issue by saharrost** [pantsel/konga#514]
Hi
When I add new service to konga an error arise :
" cannot create 'services' entities when not using a database".

**Comment by pantsel** [comment]
@saharrost , that is true. When using Kong with declarative configuration, Konga can only be used as a visual representation tool.

This is how it is intended to be.

**Comment by saharrost** [comment]
So with declarative configuration  I can not use Konga for adding services ?

**Comment by pantsel** [comment]
Correct, because then, Kongs configuration is static and cannot be changed per se.

**Comment by saharrost** [comment]
Thanks. I think I should use Kong with database

**Comment by khoale1605** [comment]
I have the same issue. So please guide me how can I create a service?

I'm following the intruction in Kong website with k8s is

kubectl apply -f https://bit.ly/k4k8s

**Comment by shenzhw** [comment]
I have the same issue too.

**Comment by PPJAISON** [comment]
I have the same issue
