### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by HefeiJoe** [pantsel/konga#516]
kubernetes，helm chart
![image](https://user-images.githubusercontent.com/27885579/70975414-d9fb9f80-20e4-11ea-9490-6c7f3f495402.png)
The host configuration for my database is not 127.0.0.1，The configuration information for the database is connectable
![image](https://user-images.githubusercontent.com/27885579/70975541-1929f080-20e5-11ea-97db-6ec0a0808cea.png)

**Comment by reoxey** [comment]
@HefeiJoe How did you solve this issue? I'm having the same issue

**Comment by reoxey** [comment]
```

Error
 ?host=kong-postgres&port=5432&schema=true&ssl=false&adapter=sails-postgresql&user=xxxx&password=xxxxx&database=konga&poolSize=10&identity=postgres

 Error: connect ECONNREFUSED 127.0.0.1:5432 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {

 errno: 'ECONNREFUSED',

 code: 'ECONNREFUSED',

 syscall: 'connect',

 address: '127.0.0.1',

 port: 5432

}
```
