### ISSUE TITLE
Broken on Kong-v0.10.x

### ISSUE THREAD

**Issue by thecantero** [pantsel/konga#52]
Checking at the SSL list is broken.

http://prntscr.com/f3wmrz

**Comment by pantsel** [comment]
@thecantero , i'll get to it asap.

**Comment by pantsel** [comment]
Hi @thecantero , the issue is addressed in the new release of Konga [v0.6.7](https://github.com/pantsel/konga/releases/tag/0.6.7).

Please confirm the fix.

Thank you for the feedback!

**Comment by thecantero** [comment]
Tested and fixed. Thanks
