### ISSUE TITLE
Kong Plugin settings with [object Object]

### ISSUE THREAD

**Issue by UNOPARATOR** [pantsel/konga#536]
The official Kong 2.0 plugin called [ACME](https://github.com/Kong/kong-plugin-acme) has some settings which are not boolean, integer or strings but whole Json objects.

> config.storage_config is a table for all posisble storage types, by default it is:
>```
>    "storage_config": {
>        "kong": {},
>        "shm": {
>            "shm_name": "kong"
>        },
>        "redis": {
>            "auth": null,
>            "port": 6379,
>            "database": 0,
>            "host": "127.0.0.1"
>        },
>        "consul": {
>            "host": "127.0.0.1",
>            "port": 8500,
>            "token": null,
>            "kv_path": "acme"
>        },
>        "vault": {
>            "host": "127.0.0.1",
>            "port": 8200,
>            "token": null,
>            "kv_path": "acme"
>        },
>    }
>```

These settings are shown as `[object Object]` in Konga plugin UI *(see below)*:
![image](https://user-images.githubusercontent.com/1214176/75548476-707e0280-5a3e-11ea-972f-1e39e7748e4a.png)

It would be nice to be able to set this kind of settings in the UI *(preferably with the default values shown)*.

**Comment by pantsel** [comment]
ACME plugin is implemented at #536. Thanks for the notice.

**Comment by UNOPARATOR** [comment]
Do you have a planned release date for the changes in the "next" branch?
