### ISSUE TITLE
[Feature Request] GraphQL Plugin Rate Limit

### ISSUE THREAD

**Issue by STRATZ-Ken** [pantsel/konga#537]
As the need/want of GraphQL continues to grow, I would love to see this plugin added 👍 

https://docs.konghq.com/hub/kong-inc/graphql-rate-limiting-advanced/

**Comment by larsnaesbye** [comment]
Isn't this a Kong Enterprise plugin? I'm not sure this can be added like that....

**Comment by STRATZ-Ken** [comment]
https://github.com/rakutentech/kong-plugin-graphql-depth-limit

Maybe something like this then?

**Comment by larsnaesbye** [comment]
Oh, now I get it. The plugins are not part of Konga, but of Kong. If you'd like an extra plugin to be added, you should install it and enable it in Kong, and then they show up in Konga :-)

**Comment by STRATZ-Ken** [comment]
Is there any documentation on this or is it automatic? (Not documentation on installing a plugin, I know that is well documented).  I would love to see these appear in the KONGA UI, esp since GraphQL recent growth.

**Comment by larsnaesbye** [comment]
When they updated Kong to 2.0.2 they enabled the ACME plugin, and now it shows up in plugins under Other. I guess other plugins will do the same.

**Comment by larsnaesbye** [comment]
It could be fun to craft one big docker-compose that installs Kong with all known plugins and enables them, and then Konga on top.

**Comment by pantsel** [comment]
@STRATZ-Ken , as @larsnaesbye said, if you install the plugin on Kong, it will be available for use in Konga as well.
