### ISSUE TITLE
http and syslog plugins not working

### ISSUE THREAD

**Issue by DewangS** [pantsel/konga#542]
I've installed HTTp and SYSLOG plugins and associated them with my routes though I can't see any options on the dashboard to view request\response and other logs. Am I missing something? The dashboard at the bottom (where there is a list of plugins) shows both of these plugins in green which I believe means they are enabled. Any idea? I am using Konga version KONGA 0.14.7

**Comment by pantsel** [comment]
You wont be able to see any related logs from those plugins in Konga. Such a feature is out of scope of the project at least for now. 

Konga is a tool for managing Kong. It is not designed to provide metrics for your infra other than those provided via Kong's admin API.
