### ISSUE TITLE
Response Rate Limiting Plugin 

### ISSUE THREAD

**Issue by aphusion** [pantsel/konga#55]
When not setting "config.header_name" for the plugin it becomes empty string in the configuration and causes the plugin to not work.  Should instead default to "X-Kong-Limit" if the string is blank.

**Comment by aphusion** [comment]
happens if you delete the pre-entered value, so not a big issue

**Comment by pantsel** [comment]
Hi @aphusion , it needs to be addressed eitherway :).
I'll get to it later today.

Thanks for the feedback!
