### ISSUE TITLE
Konga not connecting to Kong behind Load Balancer

### ISSUE THREAD

**Issue by andrerfneves** [pantsel/konga#550]
Hi there,

We're using Konga in our internal infrastructure, and it works really well when directly connecting to our server IP that's hosting the Kong node. Our current problem is that we need to run a Load Balancer in front of the Kong node to ensure Kong is highly available (AWS ALB). This is causing us problems because Konga doesn't seem to accept a Load Balancer URL as an endpoint instead of the direct IP for the Kong node -- even though both return the same information / lead to the same Kong node.

We have also tried with 1 or more than 1 Kong nodes behind the Load Balancer, but to no avail.

Are there limitations between Konga and Kong when working with Load Balancers? Does Konga only work when dealing with a single Kong instance directly (no load balancer)? Has anyone run into a similar scenario and/or have any suggestions we could try?

Thanks in advance.

**Comment by pantsel** [comment]
There are no limitations. The connection url to Kong is not limited to ip. You can define any canonical url.

**Comment by andrerfneves** [comment]
Thanks for the quick response @pantsel! We'll continue digging into our configuration to try and mitigate this issue. Just to clarify, if Konga were to connect through a Load Balancer that has 2+ Kong nodes `behind` it, it'd simply connect to one of the nodes (whichever the load balancer picks), not the 2+ nodes at once. Is that a correct understanding of the Konga connection to Kong (1 to 1)?

**Comment by pantsel** [comment]
Correct. Just have konga hit the load balanced url. For example: https://mydomain.com:8444

**Comment by andrerfneves** [comment]
Thanks @pantsel. We have been able to resolve the issue, which was indeed on our configuration side. Konga works well with an LB as you have stated. Appreciate the responses and the help.

**Comment by ZhengRongTan** [comment]
same issue .  can not access konga if konga behind nginx.
