### ISSUE TITLE
kong >=1.5.x path_handling default is v0

### ISSUE THREAD

**Issue by seifchen** [pantsel/konga#552]
kong >= 1.5.x the path_handling should be v1
but konga did not use v1 when add route
![image](https://user-images.githubusercontent.com/23326132/77633768-e7011800-6f8a-11ea-8248-e9821d691184.png)

kong version
![image](https://user-images.githubusercontent.com/23326132/77633805-f718f780-6f8a-11ea-8f9d-e543543162f8.png)

**Comment by pantsel** [comment]
Added the feature on the upcoming versions. Check the next branch.
