### ISSUE TITLE
Initial registration allows multiple admin users to be created

### ISSUE THREAD

**Issue by eburgueno** [pantsel/konga#555]
I have just started a new instance of konga, and shared the `http://konga.example.com:1337/register` URL with a colleague of mine (on a different computer). We both went ahead and registered an admin user, and to our surprise both registrations were successful. The resulting users both have admin privileges.

It is not possible to reach the `/register` path afterwards, but clearly this is a security bug. Perhaps the code should check if an admin account already exists **before submitting** the form, as well as before loading it.

**Comment by pantsel** [comment]
Yup, you're correct. Thanks for the notice. Also, a PR would be most welcome.

**Comment by pantsel** [comment]
The issue is now fixed. Cheers!cFix #555 #562
