### ISSUE TITLE
 Custom kong plugin has map type, how to input on the interface

### ISSUE THREAD

**Issue by tutorguai** [pantsel/konga#558]
Kong v2.0.1
 Custom kong plugin has map type, how to input on the interface。

**Comment by tutorguai** [comment]
and now display html input text，and commit has {"test":"expected a map"} prompt

**Comment by zfqxy** [comment]
> Kong v2.0.1
> Custom kong plugin has map type, how to input on the interface。

Hi, I have the same problem, how do you solve it? How to input on the view.
![bug.png](http://ww1.sinaimg.cn/large/6697ff0cly1gsof21lnj5j21qw13gwme.jpg)
