### ISSUE TITLE
Missing On-Off Switch for Register API

### ISSUE THREAD

**Issue by daluntw** [pantsel/konga#562]
Hi, I found a critical security issue

In code [AuthController.js#L13](https://github.com/pantsel/konga/blob/803f21fde56ef1e6ed6fce81670524dc7afaee46/api/controllers/AuthController.js#L13) register function

if register endpoint is not switchable, or auto disable after first admin created, everyone can create an admin account without authorize

### Impact

Unauthorized Access / Authentication Bypass

- CWE-305 
- CWE-306

**Comment by larsnaesbye** [comment]
Isn't this a duplicate of #555 ?

**Comment by excfergodst** [comment]
Yep, looks like we are talking about the same thing

**Comment by pantsel** [comment]
The issue is fixed. Cheers. Fix #555 #562
