### ISSUE TITLE
Headers attribute missing when configuring routes

### ISSUE THREAD

**Issue by wouthoekstra** [pantsel/konga#564]
Kong has a headers attribute in the route object configuration: https://docs.konghq.com/2.0.x/admin-api/#add-route. The first occurence in the docs for this attribute I could find is Kong 1.3: https://docs.konghq.com/1.3.x/admin-api/#route-object

This attribute is missing in the route details in Konga, which I've tested with both the latest and the next version of Konga on docker hub.

**Comment by pantsel** [comment]
Thanks for the update @wouthoekstra !

**Comment by wouthoekstra** [comment]
Wow, you're fast! :) I've pulled the update, and the headers are there. It is unfortunately not entirely working as expected; the headers attribute excepts multiple objects with arrays, which now isn't reflected in the interface.

Expected behavior (e.g.):
```
"headers": {
        "Origin": [
            "example.com",
            "anotherdomain.com"
        ],
        "AnotherHeader": [
            "headerValue1",
            "headerValue2"
        ]
    }
```

Current behavior:
`["example.com","anotherdomain.com"] 
["headerValue1","headerValue2"] 
`

**Comment by pantsel** [comment]
@wouthoekstra , please try to pull the update again. Also try clearing you browser cache because the fix was done in concurrent commits and the apps version isn't changed.

![Screenshot 2020-05-07 at 12 34 02](https://user-images.githubusercontent.com/5519873/81284938-1497b180-905f-11ea-83f4-1adf2c2cb19d.png)

**Comment by wouthoekstra** [comment]
Ah my bad, a hard refresh in my browser indeed solved it. Thx for the quick reply!
