### ISSUE TITLE
Branch NEXT

### ISSUE THREAD

**Issue by OneideLuizSchneider** [pantsel/konga#568]
Hi
I'm using the branch NEXT, and it still has one issue.
When I create the plugin ACME, and then click to edit it, we still see the fields OBJECT on the section Storage Config, as you can see in the image below.

<img width="979" alt="Screen Shot 2020-05-11 at 23 19 03" src="https://user-images.githubusercontent.com/5761239/81631373-186c6080-93de-11ea-91a2-2d019467f860.png">

**Comment by pantsel** [comment]
Hi @OneideLuizSchneider , what version do you see at the bottom?

**Comment by OneideLuizSchneider** [comment]
Hi @pantsel  version=KONGA 0.14.9.

I downloaded yesterday, I was using the KONGA 0.14.7.

**Comment by pantsel** [comment]
Thats strange, this is what i see:

![Screenshot 2020-05-14 at 22 44 41](https://user-images.githubusercontent.com/5519873/81984064-8f9b3200-9634-11ea-8b79-8658d4d9005c.png)

**Comment by OneideLuizSchneider** [comment]
Hi, I did this.
I will download the image again and then I will comment here, maybe It's cache.

**Comment by pantsel** [comment]
Yes, that might be the case as well. Try hard refreshing the page or clearing the browsers cache.

**Comment by OneideLuizSchneider** [comment]
Yes, I thing it was the cache, I downloaded again and refreshed the page many times.
thanks.
