### ISSUE TITLE
Can not access the konga

### ISSUE THREAD

**Issue by koyuhau** [pantsel/konga#57]
When start up the service, found that I and a few colleagues can access the service, but there are also some other colleagues can't access.This should have nothing to do with the browser.
Do konga have to limit access to IP or amount, or is this a bug?

**Comment by pantsel** [comment]
Hi @koyuhau , Konga has no limit access to IP. 
I will need more information on the issue since from what i understand it could be network related.

When you say "cannot access" what do you mean?  

Can't access the server?

Can all the PCs ping the server where Konga is deployed on port 1337?

**Comment by koyuhau** [comment]
"cannot access" means that there is no reaction using the browser to access port 1337.

And all the PCs can ping the server.

**Comment by pantsel** [comment]
If you open the javascript console, are there any logs?

**Comment by koyuhau** [comment]
It nothing and just say ERR_CONNECTION_REFUSED

**Comment by pantsel** [comment]
That means that the connection is rejected.
As far as i can tell this is network related.

Is there a chance that a firewall is blocking the connection to the specific port?

Try 

<pre>
# telnet {your-server-ip} 1337
</pre>

**Comment by koyuhau** [comment]
I restart the konga，there is no problem.
This problem is a bit strange, it's not the first time.Sometimes can access, the second day cannot access again.

**Comment by koyuhau** [comment]
Thank you for your help, again appear this kind of circumstance, I telnet 1337 again.
