### ISSUE TITLE
Cannot assign ACL plugin to existing API

### ISSUE THREAD

**Issue by psyhomb** [pantsel/konga#58]
`ACL` plugin cannot be assign to existing API via Konga, though I can successfully assign `Key Auth` plugin and some other plugins but when I try to do the same thing with `ACL` nothing happens, it stuck on the white loading circle that you can see on the `add plugin` button, however when I try to assign the same plugin via Kong API everything works just fine, you can then edit plugin options (whitelist, blacklist, enable/disable) via Konga WebUI with no issues, but adding a new one is definitely an issue, any solution on this problem?

**Comment by pantsel** [comment]
@psyhomb , pull the latest. If you're using the docker image, you will need to wait for a bit until it is available.

https://hub.docker.com/r/pantsel/konga/builds/

**Comment by psyhomb** [comment]
Thanks for the quick fix, it's working now!
