### ISSUE TITLE
Demo user cannot define default connection

### ISSUE THREAD

**Issue by harryparmar** [pantsel/konga#60]
When demo user logs in and tries to select connection as default, he is redirected to login screen.

**Comment by pantsel** [comment]
Only use admin users for now because normal users are not properly tested and to be honest, i havent decided yet how they should be used (permissions and stuff). :)

**Comment by harryparmar** [comment]
I think if it is not too complicated, demo user can login and have same views except they dont get to edit/create new stuff. I also left some other ideas on gitter channel.

**Comment by pantsel** [comment]
@harryparmar , cool!
I'll check it out.
