### ISSUE TITLE
Facing blank page when running as production

### ISSUE THREAD

**Issue by sbookworm** [pantsel/konga#603]
Hi team, sorry to bother you.
I downloaded the latest code, and installed followed the guide, and I found a strange thing. I configured the postgresql as the adapter. then run npm start with below configuration. It works fine
PORT=1337
#NODE_ENV=production
KONGA_HOOK_TIMEOUT=120000
DB_ADAPTER=postgres
DB_URI=postgresql://konga:passw0rd@127.0.0.1:5432/konga
KONGA_LOG_LEVEL=warn
TOKEN_SECRET=some_secret_token

when I uncomment the NODE_ENV=production
and then run npm start again. There will be a blank page for the web portal.
I am using non-root user

Besides, I have tried the command 'npm run bower-deps' too, it does not help.

could you please help to take a look? thanks

**Comment by fbaeumer** [comment]
What happens when you start your application with "npm run production"?

**Comment by sbookworm** [comment]
@fbaeumer I could see the first page of registering, then click register, then the blank page appeared.

**Comment by sbookworm** [comment]
currently, the problem can not be reproduced for days. It's strange, I did not do anything, and it works.
Maybe related to browser cache. Thank you all
