### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by TheDolo** [pantsel/konga#61]
I find my self constantly refreshing the dashboard to see updated stats in the connection box!  Any chance we could get these on a (configurable) polling time, say every 5sec?  I'd really like to see more real-time computable stats on the Kong nodes.

Thank you for your wonderful work!

**Comment by pantsel** [comment]
@TheDolo , man! I wanted to do that for some time now but it ended up at the bottom of my priority stack thinking OK,  since nobody asks for it I'll leave it for later.

Guess it's time :)
