### ISSUE TITLE
alert("Error getting initial configuration")

### ISSUE THREAD

**Issue by HuangDayu** [pantsel/konga#625]
Hello, I am using konga version 0.14.9 and angular-chart.js has been installed, but I encounter the following error, how can I solve it? Thank you.

![image](https://user-images.githubusercontent.com/23421574/96412737-250ea380-121d-11eb-9455-b33a4e46aae2.png)

```log
[root@serv221vm11 konga-0.14.9]# sudo npm install --save angular-chart.js
+ angular-chart.js@1.1.1
updated 1 package and audited 1195 packages in 6.492s

1 package is looking for funding
  run `npm fund` for details

found 390 vulnerabilities (206 low, 18 moderate, 166 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

```log
angular-chart.js?r=0.14.9:23 Uncaught Error: Chart.js library needs to be included, see http://jtblin.github.io/angular-chart.js/
    at angular-chart.js?r=0.14.9:23
    at angular-chart.js?r=0.14.9:26
(anonymous) @ angular-chart.js?r=0.14.9:23
(anonymous) @ angular-chart.js?r=0.14.9:26
```

```log
angular.js?r=0.14.9:14199 Error: [$injector:modulerr] Failed to instantiate module frontend due to:
Error: [$injector:modulerr] Failed to instantiate module frontend.dashboard due to:
Error: [$injector:modulerr] Failed to instantiate module chart.js due to:
Error: [$injector:nomod] Module 'chart.js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.11/$injector/nomod?p0=chart.js
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:68:12
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:2133:17
    at ensure (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:2057:38)
    at module (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:2131:14)
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4669:22
    at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
    at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4670:40
    at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
    at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=chart.js&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'chart.js'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dchart.js%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2133%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2057%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2131%3A14)%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4669%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A325%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4653%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4670%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A325%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4653%3A5)
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:68:12
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4692:15
    at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
    at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4670:40
    at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
    at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
    at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4670:40
    at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
    at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=frontend.dashboard&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20chart.js%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'chart.js'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dchart.js%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2133%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2057%3A38)%0A%20%20%20%20at%20module%20
```

**Comment by johnsonyep** [comment]
> Hello, I am using konga version 0.14.9 and angular-chart.js has been installed, but I encounter the following error, how can I solve it? Thank you.
> 
> ![image](https://user-images.githubusercontent.com/23421574/96412737-250ea380-121d-11eb-9455-b33a4e46aae2.png)
> 
> ```
> [root@serv221vm11 konga-0.14.9]# sudo npm install --save angular-chart.js
> + angular-chart.js@1.1.1
> updated 1 package and audited 1195 packages in 6.492s
> 
> 1 package is looking for funding
>   run `npm fund` for details
> 
> found 390 vulnerabilities (206 low, 18 moderate, 166 high)
>   run `npm audit fix` to fix them, or `npm audit` for details
> ```
> 
> ```
> angular-chart.js?r=0.14.9:23 Uncaught Error: Chart.js library needs to be included, see http://jtblin.github.io/angular-chart.js/
>     at angular-chart.js?r=0.14.9:23
>     at angular-chart.js?r=0.14.9:26
> (anonymous) @ angular-chart.js?r=0.14.9:23
> (anonymous) @ angular-chart.js?r=0.14.9:26
> ```
> 
> ```
> angular.js?r=0.14.9:14199 Error: [$injector:modulerr] Failed to instantiate module frontend due to:
> Error: [$injector:modulerr] Failed to instantiate module frontend.dashboard due to:
> Error: [$injector:modulerr] Failed to instantiate module chart.js due to:
> Error: [$injector:nomod] Module 'chart.js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
> http://errors.angularjs.org/1.5.11/$injector/nomod?p0=chart.js
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:68:12
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:2133:17
>     at ensure (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:2057:38)
>     at module (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:2131:14)
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4669:22
>     at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
>     at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4670:40
>     at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
>     at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
> http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=chart.js&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'chart.js'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dchart.js%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2133%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2057%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2131%3A14)%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4669%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A325%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4653%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4670%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A325%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A4653%3A5)
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:68:12
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4692:15
>     at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
>     at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4670:40
>     at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
>     at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
>     at http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4670:40
>     at forEach (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:325:20)
>     at loadModules (http://192.168.2.224:1337/bower_components/angular/angular.js?r=0.14.9:4653:5)
> http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=frontend.dashboard&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20chart.js%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'chart.js'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3Dchart.js%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2133%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.2.224%3A1337%2Fbower_components%2Fangular%2Fangular.js%3Fr%3D0.14.9%3A2057%3A38)%0A%20%20%20%20at%20module%20
> ```

I also have the some problem. have anyothers can fix this
