### ISSUE TITLE
Unable to edit API

### ISSUE THREAD

**Issue by mdaguete** [pantsel/konga#63]
Hello,

When I try to edit an api nothing happend. In status bar I can see the url,

`http://host:1337/#!/apis/cda7fdbd-f4d1-4b65-9d1a-9b32464e911f/edit`

but in developer console the following error is thrown 
`VM930:1 GET http://host:1337/js/app/apis/api-ssl.html 404 (Not Found)
(anonymous)	@	VM930:1
(anonymous)	@	angular.js:12265
sendReq	@	angular.js:12027
serverRequest	@	angular.js:11822
processQueue	@	angular.js:16696
(anonymous)	@	angular.js:16712
$eval	@	angular.js:17994
$digest	@	angular.js:17808
$apply	@	angular.js:18102
(anonymous)	@	angular.js:19950
completeOutstandingRequest	@	angular.js:6045
(anonymous)	@	angular.js:6324
`

I'm using latest docker image.

Regards.

**Comment by pantsel** [comment]
Hello, @mdaguete,
i can't reproduce that issue with <code>pantsel/kong:latest</code> or <code>pantsel/konga:0.7.1,</code>

You could do one thing tho. Try hard refreshing the page or disabling cache and refresh.

Those caching issues are solved on the next version.

Also you could try <code>pantsel/konga:next</code> which is on the final testing stages and has some new features along with a UI revamp.

Cheers.

**Comment by pantsel** [comment]
@mdaguete, it just came to me. What version of Kong are you using?

**Comment by mdaguete** [comment]
Hi @pantsel 

For the first reply

```
docker pull pantsel/konga:latest
latest: Pulling from pantsel/konga
Digest: sha256:7807c0977dbb02ef85e6ca022ac8ba3b767f0cb19478717d446346e66b54c9b2
Status: Image is up to date for pantsel/konga:latest
```

Kong v0.10.2

It was a caching issue and clearing it the issue was resolved.

Thanks. Regards.
