### ISSUE TITLE
ECONNREFUSED when prepare on localhost postgresql database 

### ISSUE THREAD

**Issue by ttpro1995** [pantsel/konga#655]
I have posgresql
```
CREATE USER konga; CREATE DATABASE konga OWNER konga;
ALTER USER konga WITH PASSWORD 'meowmeowmeow'; 
```

so, the connection url is 

`postgresql://konga:meowmeowmeow@localhost:5432/konga`

I also test if url correct

`psql postgresql://konga:meowmeowmeow@localhost:5432/konga`

it worked, shown

```
psql (13.1 (Ubuntu 13.1-1.pgdg18.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

konga=> 

```
Now I run konga prepare database on same machine 

`docker run --rm pantsel/konga:latest -c prepare -a postgres -u postgresql://konga:meowmeowmeow@localhost:5432/konga`

I get the ECONNREFUSED 

```
Using postgres DB Adapter.
Failed to connect to DB Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
```

So what wrong here ? What did I miss ?

**Comment by ttpro1995** [comment]
found solution, this is issue on Docker itself.

Reference to 
https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
and
https://github.com/moby/libnetwork/pull/2348

Temporary solution (not so secure): 

Make postgres accessible from public IP. Replace localhost with public ip

**Comment by 404answernotfound** [comment]
> found solution, this is issue on Docker itself. Docker app cannot access to localhost of host machine out-of-the-box. Need "special care".
> 
> Look like there is no trivial solution. Reference to: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach and [moby/libnetwork#2348](https://github.com/moby/libnetwork/pull/2348)
> 
> Temporary but fast solution (not so secure):
> 
> Make postgres accessible from public IP. Replace localhost with public ip/url.

Couldnt you bridge on networks/app-tier for them to share network?
