### ISSUE TITLE
konga seems not to be working with kong v2.2.1. Giving  schema voilation error while creating/changing any resource

### ISSUE THREAD

**Issue by ankurnykaa20** [pantsel/konga#661]
When i am creating any service/route it is giving schema violation error .In case of service it is showing host is missing even though I have mentioned the host while I am able to create/change resource with the kong admin api .Can someone please help?

![image](https://user-images.githubusercontent.com/51694154/104907798-a35d1c00-59ab-11eb-89b6-7853e56a14be.png)

**Comment by ankurnykaa20** [comment]
![image](https://user-images.githubusercontent.com/51694154/104908187-16ff2900-59ac-11eb-9ed7-364392f29500.png)

**Comment by KamranShahid** [comment]
I am facing same issue. kong version of my docker image is 2.3.3

**Comment by ankurnykaa20** [comment]
I resolved it by making connection from kong admin server on http instead of https from konga . Please try and let me know if that helped.

**Comment by ankurnykaa20** [comment]
> I am facing same issue. kong version of my docker image is 2.3.3

I resolved it by making connection from kong admin server on http instead of https from konga . Please try and let me know if that helped.

**Comment by KamranShahid** [comment]
> > I am facing same issue. kong version of my docker image is 2.3.3
> 
> I resolved it by making connection from kong admin server on http instead of https from konga . Please try and let me know if that helped.

I am already using it with http
