### ISSUE TITLE
Link to api in plugin section is broken

### ISSUE THREAD

**Issue by PauloGDPeixoto** [pantsel/konga#67]
Clicking the api id in a plugin, on the plugin section should bring the user to the edit api screen (at least that's what I'm guessing from the link), but the id is missing in the link, thus breaking it.

**Comment by pantsel** [comment]
Hi @PauloGDPeixoto , can you clear your cash and try it again? I think this is a caching issue from a previous version (if you're using the latest commit)

**Comment by PauloGDPeixoto** [comment]
I was still on 0.6.5, after pulling 0.7.1 the issue was resolved and I'm marvelled with the new features, I have a lot to explore! Sorry about the bogus ticket.

**Comment by pantsel** [comment]
You could also try the [next](https://github.com/pantsel/konga/tree/next) branch or if you're using docker
<code>run pantsel/konga:next</code>.

The version is almost ready and handles lots of things better.
