### ISSUE TITLE
Consumer key-auth setup is not generating a key when none is specified

### ISSUE THREAD

**Issue by nickarnold** [pantsel/konga#68]
Under `Consumers->Credentials->API Keys->Create API Key` there is a block of text that indicates an API Key will be auto-generated by Kong if one is not specified in the input. However, when leaving that box empty and clicking submit it becomes clear that Konga/Kong is not actually generating a key and is instead leaving the key value as the empty string.

Watching the network logs, one can see the POST to `/kong/consumers/:consumerId/key-auth` with an empty `key` value in the JSON body. The response to that request also returns an empty string for the `key` property. 

I'm running the `pantsel/konga` and `kong:0.10` docker images. Without having traced through the code yet I'm guessing that Kong 0.10 does not auto-generate a key as perhaps previous versions did? If that's the case, maybe Konga should generate a UUID whenever the user doesn't enter a value in the `key-auth` Consumer setup screen.

**Comment by pantsel** [comment]
@nickarnold, this issue started occuring in Kong v0.10.3. Thanks for noticing
