### ISSUE TITLE
Unable to edit some fields in plugin settings editors

### ISSUE THREAD

**Issue by kbdfck** [pantsel/konga#7]
IP restriction plugin:
For example, unable to edit whitelist/blacklist entries In IP restriction plugin editor. It doesn't send anything to server, and doesn't display values set manually. Seems there is no ng-model set on client side for these fields at all.
Also, If customer is selected once, it is unable to remove its uuid from customer field. If you leave it empty, it uses previous customer value.

JWT plugin:
Unable to edit URL param names, it doesn't store values from this field.

**Comment by pantsel** [comment]
Try pressing enter after every ip you wirte. There is a chip cpmponent handling array fields that is a little bit obscure. Mayve ill change it at some point.

**Comment by kbdfck** [comment]
Ok, I see, there is a chip wrapper stuff I've missed.
Thanks for your quick response, this way things work fine!
