### ISSUE TITLE
Details:SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by flowdopip** [pantsel/konga#70]
Do you have any ideia why. when start konga im getting this error Details:SyntaxError: Unexpected token ...

**Comment by pantsel** [comment]
@flowdopip if you have installed konga from source, try running bower install manualy. Sometimes bower dependencies may not have been installed.

**Comment by flowdopip** [comment]
doesn´t fix :(

**Comment by pantsel** [comment]
Can you please describe what are you doing step by step and post the exact error here?

**Comment by flowdopip** [comment]
![image](https://user-images.githubusercontent.com/5880313/26919997-7a4d3c9c-4c2f-11e7-972d-2644bc6f0f79.png)

**Comment by pantsel** [comment]
@flowdopip , try running the app with the --harmony flag

<code>node --harmony app.js</code>

**Comment by flowdopip** [comment]
thanks! solved

**Comment by amazon10** [comment]
Hi flowdopip, how you solved the problem?
