### ISSUE TITLE
Can't edit/remove upstreams (Konga 0.7.3)

### ISSUE THREAD

**Issue by PauloGDPeixoto** [pantsel/konga#71]
It seems that there is no option to delete upstreams and targets in konga 0.7.3. Editing an upstream is also impossible, as the "Submit changes" button seems to always be disabled.

**Comment by pantsel** [comment]
@PauloGDPeixoto, upstreams or target could not be edited or removed on Kong 0.10.1, thats why Konga doesn't have this functionality. You can do so in version 0.10.3 for sure, so this is something that will be implemented in Konga as well.

**Comment by pantsel** [comment]
@PauloGDPeixoto, I've enabled those features in the [next](https://github.com/pantsel/konga/tree/next) branch. If you're using docker you can <code>pull pantsel/konga next</code>.
