### ISSUE TITLE
Konga 0.7.3: Blank api keys

### ISSUE THREAD

**Issue by PauloGDPeixoto** [pantsel/konga#73]
I'm currently using Konga 0.7.3 and today I tried doing something I haven't done in a while: generate a new random api key. I did as usual, submitted a blank form for kong to generate a random api key, but the result is a blank api key.
If I input something in the key field, it saves the api key correctly.

**Comment by PauloGDPeixoto** [comment]
I don't know if this is the same issue, but I also tried creating a new consumer and I had to fill both the name and custom-id (I usually only fill the name) as it wouldn't let me insert another consumer with a blank custom-id.

**Comment by PauloGDPeixoto** [comment]
I updated to Konga 0.8.0 and the api key issue disappeared, but the consumer custom-id issue persists.

**Comment by pantsel** [comment]
@PauloGDPeixoto , thanks for the feedback! I'll fix it and get back to you.

**Comment by pantsel** [comment]
@PauloGDPeixoto , i did a test on Kong v0.10.3 and created a consumer witout specifying a <code>custom_id</code> field.

The response was
<pre>
{
    "username": "test1",
    "created_at": 1497986369000,
    "id": "72ddd0a1-d65b-4462-96ea-75d8848db98d"
}
</pre>

So it seems that Kong does not autogenerate a <code>custom_id</code> if not specified.

**Comment by PauloGDPeixoto** [comment]
I re-tested and it seems to be working fine. Must have been some browser cache. Sorry about the bogus issue and thank you for your great work :)
