### ISSUE TITLE
Konga V0.8.0 not connecting with kong after update.

### ISSUE THREAD

**Issue by hectorag** [pantsel/konga#74]
I have a configuration working on my setup:

Konga <-> Kong 

Using Postgres DB for both of them.

Suddenly after a docker image update Konga stop connecting with Kong. In the connection page the status say "Last know status as **Healthy**" But when I tried to open the dashboard I got an error, showing in the logs:

`/app/api/policies/dynamicNode.js:13 [Policy.dynamicNode() called] undefined`

I rollback to version 0.7.1 and everything looks good. Konga is connecting successfully to kong.

**Comment by pantsel** [comment]
Try logging out, refreshing the page and logging back in just in case something is cached.

**Comment by pantsel** [comment]
I'm going to assume that this issue is fix since there was no replay for 16 days. If that is not the case feel free to open it again.
