### ISSUE TITLE
What does the connections mean ?

### ISSUE THREAD

**Issue by artemus717** [pantsel/konga#76]
![image](https://user-images.githubusercontent.com/16465173/27873964-6e097e2a-61e0-11e7-9a6d-1335f4567c38.png)

**Comment by pantsel** [comment]
Hi @artemus717.

The connections panel, refers to metrics about the nginx HTTP/S server

[https://getkong.org/docs/0.10.x/admin-api/#retrieve-node-status](https://getkong.org/docs/0.10.x/admin-api/#retrieve-node-status)
