### ISSUE TITLE
Kong loopback API configuration : strip_request_path no longer works

### ISSUE THREAD

**Issue by rjpalermo1** [pantsel/konga#78]
On the welcome screen you link to a Gelato doc for details on a loop-back API.

`https://docs.gelato.io/guides/advanced-kong-integration`

I just found out that their advice for strip_request_path is not available in Kong 0.10, so their cURL fails:

```
curl -X POST http://localhost:8001/apis   -d "name=admin-loop-back"   -d "request_path=/admin-loop-back"   -d "upstream_url=http://localhost:8001"   -d  "strip_request_path=true"

{"request_path":"request_path is an unknown field","strip_request_path":"strip_request_path is an unknown field"}
```

Changes are now 'strip_uri' and field name is `uris`

```
curl -X POST http://localhost:8001/apis   -d "name=admin-loop-back"   -d "uris=/admin-loop-back"   -d "upstream_url=http://localhost:8001"   -d  "strip_uri=true"
```

**Comment by pantsel** [comment]
@rjpalermo1 ,
Yes, it seems that they can't even keep up with themselves :) - Joking -.

I'll just change the title and keep this issue open as a reference to other users.

Thanks for the feddback!

**Comment by rjpalermo1** [comment]
Here is the related reference in Kong docs:

https://getkong.org/docs/0.10.x/secure-admin-api/#kong-api-loopback

**Comment by pantsel** [comment]
Neat, i will put that link instead. Thanks!

**Comment by pantsel** [comment]
Issue fixed with the latest push.

**Comment by coopr** [comment]
You may instead choose to link to https://getkong.org/docs/latest/secure-admin-api/#kong-api-loopback - that'll make it more likely the link destination stays valid as newer versions of Kong are released. 

Note that this trick works with all versioned pages on getkong.org - simply replace the version number in the URL with `latest`.

**Comment by pantsel** [comment]
@coopr ,
thanks for the info!
