### ISSUE TITLE
New form-api-011.html for Kong v0.11 release

### ISSUE THREAD

**Issue by thucnc** [pantsel/konga#80]
KONG API will release next version 0.11 soon. Actually, it has the 0.11RC already, so please add new form to add new api for this version. 
Thanks.

**Comment by edwardjrp** [comment]
@here Any news on upgrading. Im using it with yesterday's 0.11.0 stable release and most things works except editing an api entry. plugins editing and other things work.

**Comment by pantsel** [comment]
@edwardjrp , @thucnc ,
I'm going to work on the 0.11.* integration tommorrow probably.

Cheers

**Comment by pantsel** [comment]
Check out v0.8.3 release.
