### ISSUE TITLE
Wacking my CPU 

### ISSUE THREAD

**Issue by just1689** [pantsel/konga#81]
Good day,

Running Konga in Docker Swarm against Kong.

Docker version: 17.06.0-ce
Kong version: 0.10.3
Konga version: 0.8.1

Issue:

Deployed Konga to the first node in our swarm and it is consuming between 27% and 35% of the CPU.
This is the case when no one is using it or has even logged in.
Is this normal?

VM spec:

Azure S1 Standard
CPU: 2 vCPU
RAM: 3.5 GB

**Comment by pantsel** [comment]
Hi @just1689 .
Are you running Konga in production mode by setting the env var <code>NODE_ENV=production</code>?

If not, you should be experiencing high CPU usage because of all the tasks running in the background. 
p.e file watchers.

**Comment by just1689** [comment]
Thank you for your reply @pantsel. You are correct, it was running in development mode.

I've now set NODE_ENV=production as you have suggested. It worked perfectly.

Thank you for your support and speedy reply.
