### ISSUE TITLE
Konga new installation 

### ISSUE THREAD

**Issue by anupam4881** [pantsel/konga#82]
Dear Team,

We are facing issue with Konga fresh installation, we follow up all required step to run but at last, we are getting a blank page. 
need your help as we found this good as per feedback. 

---------------------------------------------------------------------------
[root@psld-ggn-176 node_modules]# pwd
/opt/node-v6.11.1-linux-x64/lib/node_modules
[root@psld-ggn-176 node_modules]# node --version
v6.11.1
[root@psld-ggn-176 node_modules]# npm --version
3.10.10
[root@psld-ggn-176 node_modules]# ls
@angular  bower  gulp  konga  npm  sails
[root@psld-ggn-176 node_modules]# 

did changes like local_example.js to local.js   and database mysql with new emply database created with name  konga_database. 

I started app first like. below.  showing started over port 1338 
[root@psld-ggn-176 bin]# pwd
/opt/node-v6.11.1-linux-x64/lib/node_modules/konga/bin
[root@psld-ggn-176 bin]# npm start  "http-server -a 192.168.0.124 -p 1338"

> kongadmin@0.8.1 start /opt/node-v6.11.1-linux-x64/lib/node_modules/konga
> node --harmony app.js "http-server -a 192.168.0.124 -p 1338"

Tables created in database. 

but with IP:1338  konga is showing a blank page same with also with prod command ( npm run production   "http-server -a 192.168.0.124 ").

Need you help to run and check new functionality. 

Regards
Anupam Narayan

**Comment by pantsel** [comment]
Hello @anupam4881 ,

Check this issue #79.

Probably the bower deps didn't get installed automatically.

Try to run
<pre>$ bower --allow-root install</pre>
at projects root dir.

**Comment by anupam4881** [comment]
Yes Thanks now it is working.
