### ISSUE TITLE
Unable to apply multiple plugins for Rate Limiting

### ISSUE THREAD

**Issue by Devin-Grant** [pantsel/konga#83]
The web client (Konga) only allows admins to add one rate-limiting.  However, Kong supports assigning multiple entries to customers and apis (as globally).

Btw, this is a problem for other plugins as well. 

-Devin

**Comment by pantsel** [comment]
Hi @Devin-Grant , you're right!

I fixed that with the latest commit. If you like check it out and confirm the fix.

Thanks for the feedback!
