### ISSUE TITLE
Request Transformer plugin values are not stored

### ISSUE THREAD

**Issue by sebastianroesch** [pantsel/konga#85]
Hi,

when I set Request Transformer values in the UI, the are not being stored.

When I for example add _c:1_ to _add querystring_, the resulting JSON in the raw view is empty:

`
{
  "api_id": "6ff27660-ae38-4b2a-a1f9-fb81ea1800ed",
  "id": "60065601-acdf-431c-8904-cd6a058657c0",
  "created_at": 1501755677077,
  "enabled": true,
  "name": "request-transformer",
  "config": {
    "remove": {
      "body": {},
      "querystring": {},
      "headers": {}
    },
    "rename": {
      "querystring": {},
      "body": {},
      "headers": {}
    },
    "add": {
      "querystring": {},
      "body": {},
      "headers": {}
    },
    "replace": {
      "body": {},
      "querystring": {},
      "headers": {}
    },
    "append": {
      "body": {},
      "querystring": {},
      "headers": {}
    }
  }
}
`

**Comment by pantsel** [comment]
Hi @sebastianroesch , you need to press <code>enter</code> after every value you write so that the chip component can accept it.

Check issue #48

**Comment by sebastianroesch** [comment]
Okay, thanks, that worked, sorry for the duplicate!
