### ISSUE TITLE
Can't delete a node.

### ISSUE THREAD

**Issue by thecantero** [pantsel/konga#88]
I can't delete a node.

http://prntscr.com/gb3u5f

**Comment by pantsel** [comment]
Hi @thecantero ,
can the node be deleted using the raw Kong API (with postman)?

Apart from that, the cluster object is removed entirely in Kong 0.11.x .

Quoting [Kong's CHANGELOG](https://github.com/Mashape/kong/blob/master/CHANGELOG.md)

> As a result of the Serf removal, Kong is now entirely stateless, and as such, the /cluster endpoint has disappeared.

So, I don't know whether or not  it makes sense to fix a deprecated feature.

**Comment by thecantero** [comment]
That's fine, We're still at Kong-v0.10.x at the moment. I'll keep you posted if there's anything I could add.

Thanks

**Comment by pantsel** [comment]
Cheers and thanks for the contribution man!

**Comment by thecantero** [comment]
I've already shifted to Kong-v0.11.0 and it's working fine now. Closing this.
