### ISSUE TITLE
Method Not Allowed when trying to fetch upstreams active targets

### ISSUE THREAD

**Issue by cfajardo** [pantsel/konga#89]
With the latest konga 0.83 version with kong 0.11 api integration

When i want to edit an upstream i have the following error message : Method Not Allowed with the following request

The method not allowed comes from this endpoint :

```
http://kong:8001/upstreams/844c8956-dd38-40a4-979c-21d8582d5a78/targets/active
```

Doen't work :
```sh
curl http://kong:8001/upstreams/844c8956-dd38-40a4-979c-21d8582d5a78/targets/active -X GET
```

After some investigation you should add a `/` at the end of your request like this :
```
http://kong:8001/upstreams/844c8956-dd38-40a4-979c-21d8582d5a78/targets/active/
```

Works :
```sh
curl http://kong:8001/upstreams/844c8956-dd38-40a4-979c-21d8582d5a78/targets/active/ -X GET
```

I've not checked if there are other errors like this one.

Have a nice day.

**Comment by pantsel** [comment]
Hi, @cfajardo ,
According to [Kong's docs](https://getkong.org/docs/0.11.x/admin-api/#list-active-targets),
this endpoint is <pre>GET: /upstreams/{name or id}/targets/active</pre> without the trailing slash.

Konga complies with the documentation so, it seems that this is an issue to be raised at Kong's repo, not here.
It's probably a bug which they will likely be fixing, so in my opinion we should wait and see.

Cheers.

**Comment by cfajardo** [comment]
You're absolutely right. This issue has already been reported and merged 4 month ago. This is a regression.

**Comment by cfajardo** [comment]
I've reported the issue : [https://github.com/Mashape/kong/issues/2840](https://github.com/Mashape/kong/issues/2840)

**Comment by pantsel** [comment]
Closing this issue because apparently it has been [addressed by  Mashape](https://github.com/Mashape/kong/commit/e49cd360693e44e8d3842f62ba92d5c367c3052a).
