### ISSUE TITLE
Properly handle Pagination

### ISSUE THREAD

**Issue by mazubieta** [pantsel/konga#9]
Hey there, thanks for this project.  The UI is very clean and enjoyable to work with.  I've noticed that you do not properly handle pagination when retrieving consumers and apis.  I've patched it locally, but I'm not much of a javascript developer, so likely it's not idiomatic.  I'll send a PR, but if you want to solve it your way that's cool too.

**Comment by pantsel** [comment]
@mazubieta 

I'm glad you find Konga helpful. Do submit that PR and I will make the required adjustments

**Comment by pantsel** [comment]
Ok, you already did 👍
