### ISSUE TITLE
Unable to create a new user

### ISSUE THREAD

**Issue by jamelseagraves** [pantsel/konga#90]
I am running the latest konga Docker image as well as kong version 0.10.3. I am able to update the existing konga admin and demo users in the dashboard, which is great. But when I select Create User, enter all the information into the form, and click the Submit User button, nothing happens. The screen doesn't change except for the very brief appearance of a loading wheel on the left side of the Submit User button.

Additionally, if I input no user information into the form and click the Submit User button, the same happens as described above: no response except for the quick flash of the loading wheel. I would expect that in this case I should see error messages appear as I did not populate the required fields.

Any ideas why the Submit Button click event is not triggering the appropriate responses?

Thanks!

**Comment by pantsel** [comment]
Hi @jamelseagraves and sorry for the late response. I was on vacation :).

What version of Konga are you using?

Everything here seems to work fine with version 0.8.3. Check out the  [demo instance]( http://46.101.119.106) as well. A new user can be created normally.

If you're still having this issue when trying to create a new user,  open the browser's javascript console and post the errors here.

**Comment by jamelseagraves** [comment]
No problem @pantsel. Thanks for the reply.

I am using version 0.8.3 for my instance. Not sure what could be the issue as everything else seems to work fine. Here are the errors from the js console:

```
POST https://[my ip address]/auth/signup 403 (Forbidden)
(anonymous)	@	angular.js?r=0.8.3:12265
sendReq	@	angular.js?r=0.8.3:12027
serverRequest	@	angular.js?r=0.8.3:11822
processQueue	@	angular.js?r=0.8.3:16696
(anonymous)	@	angular.js?r=0.8.3:16712
$eval	@	angular.js?r=0.8.3:17994
$digest	@	angular.js?r=0.8.3:17808
$apply	@	angular.js?r=0.8.3:18102
(anonymous)	@	angular.js?r=0.8.3:26597
dispatch	@	jquery.js?r=0.8.3:4430
elemData.handle	@	jquery.js?r=0.8.3:4116
```

```
{data: "forbidden", status: 403, config: {…}, statusText: "Forbidden", headers: ƒ}
(anonymous)	@	angular.js?r=0.8.3:14199
(anonymous)	@	user-create-controller.js?r=0.8.3:43
processQueue	@	angular.js?r=0.8.3:16696
(anonymous)	@	angular.js?r=0.8.3:16712
$eval	@	angular.js?r=0.8.3:17994
$digest	@	angular.js?r=0.8.3:17808
$apply	@	angular.js?r=0.8.3:18102
done	@	angular.js?r=0.8.3:12082
completeRequest	@	angular.js?r=0.8.3:12291
requestLoaded	@	angular.js?r=0.8.3:12219
XMLHttpRequest.send (async)		
(anonymous)	@	angular.js?r=0.8.3:12265
sendReq	@	angular.js?r=0.8.3:12027
serverRequest	@	angular.js?r=0.8.3:11822
processQueue	@	angular.js?r=0.8.3:16696
(anonymous)	@	angular.js?r=0.8.3:16712
$eval	@	angular.js?r=0.8.3:17994
$digest	@	angular.js?r=0.8.3:17808
$apply	@	angular.js?r=0.8.3:18102
(anonymous)	@	angular.js?r=0.8.3:26597
dispatch	@	jquery.js?r=0.8.3:4430
elemData.handle	@	jquery.js?r=0.8.3:4116
```

**Comment by pantsel** [comment]
You're getting a 403 forbidden response for some reason. Can you please expand `config` in this line and post it again?

<pre>{data: "forbidden", status: 403, config: {…}, statusText: "Forbidden", headers: ƒ}</pre>

**Comment by jamelseagraves** [comment]
Here is the config object broken out:
```
config:
	cached: false
	data:
		active: true
		admin: false
		email: "test@test.bs"
		firstName: "testy"
		lastName: "testerton"
		passports: {password: "testsecret", protocol: "local"}
		password_confirmation: "testsecret"
		token: "eyJhbGciOiJIUzI1NiJ9.MQ.Lu-KcR4aCeuT9hi1K474zV3s4VaopLDCcf4nZvH6DQo"
		username: "test"
		__proto__: Object
	headers: {Accept: "application/json, text/plain, */*", Content-Type: "application/json;charset=utf-8", authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.MQ.Lu-KcR4aCeuT9hi1K474zV3s4VaopLDCcf4nZvH6DQo"}
	method: "POST"
	paramSerializer: ƒ ngParamSerializer(params)
	transformRequest: [ƒ]
	transformResponse: [ƒ]
	url: "auth/signup"
	__proto__: Object
	data: "forbidden"
	headers: ƒ (name)
	status: 403
	statusText: "Forbidden"
```

**Comment by azumafuji** [comment]
I was just going to open a ticket but found this.  If you have the setting "Allow users to sign up." disabled, (i.e. the signup tab on the login screen is not visibile) then you cannot add new users though any means. If you enable signups you can add users.  This is definitiely a bug. The creatUser function calls signup and and signup requires `needsSignupEnabled : true`.

**Comment by pantsel** [comment]
@azumafuji .
Great! Thanks for the pointer! I'll get to it asap.

**Comment by jamelseagraves** [comment]
Thanks @azumafuji! Good catch.
