### ISSUE TITLE
not able to restore snapshot

### ISSUE THREAD

**Issue by hoaivan** [pantsel/konga#95]
It just failed. Im on Konga 0.8.3 and Kong API 0.11. Target Konga is blank without any api, plugins nor consumer

**Comment by poseidonqiu** [comment]
I have the same problem. Target Konga is blank without anything.

**Comment by pantsel** [comment]
@hoaivan , @poseidonqiu try again with the latest releases

**Comment by pantsel** [comment]
Closing this due to long time innactivity. I'm assuming this issue is fixed.
Feel free to reopen if that's not the case.
