### ISSUE TITLE
Notifications to Slack

### ISSUE THREAD

**Issue by kamsz** [pantsel/konga#96]
It'd be awesome to have a possibility to configure notifications to Slack.

**Comment by pantsel** [comment]
@kamsz , yes!
That would be awesome. Il'see what i can do.

**Comment by pantsel** [comment]
@kamsz , the next version of Konga is coming soon and slack notifications are implemented as you suggested.

It would be awesome if you want to test it and provide some feedback before the next version is officialy released.

You can test it by building Konga from the [next branch](https://github.com/pantsel/konga/tree/next)
or
if you're using docker, by pulling <code>pantsel/konga:next</code>.

Cheers and thanks again for the contribution.

**Comment by pantsel** [comment]
Implemented on [v0.8.8](https://github.com/pantsel/konga/releases/tag/0.8.8)
