### ISSUE TITLE
npm 5.4.2

### ISSUE THREAD

**Issue by Niradnik** [pantsel/konga#97]
Hi all,
since the release of the npm 5.4.2 I have trouble rebuilding the konga's docker official image I get:
To run an app using `node app.js`, you usually need to have a version of `sails` installed in the same directory as your app.
downgrading to npm 5.4.1 does not fix the issue
Any ideas for a fix?
BTW thanks for the amazing job you guys are doing with konga!!
Cheers !

**Comment by pantsel** [comment]
Hi @Niradnik ,
have you tried to install sails globally?
<pre>npm i -g sails</pre>

**Comment by pantsel** [comment]
@Niradnik , there seems to be an issue with npm > 5.4.0.
Either you downgrade to 5.4.0, or use the official docker image.
Cheers!
