### ISSUE TITLE
Many notices in docker logs

### ISSUE THREAD

**Issue by smalot** [pantsel/konga#99]
Hi all,

Client pull is currently feeding my logs with the following details :

````
kong-konga        | KongProxyController http://kong:8001/status
kong-konga        | req.method GET
kong-konga        | req.url 
kong-konga        | KongProxyController http://kong:8001
kong-konga        | req.method GET
kong-konga        | /app/api/policies/dynamicNode.js:13 [Policy.dynamicNode() called] undefined
kong-konga        | /app/api/policies/dynamicNode.js:13 [Policy.dynamicNode() called] undefined
````
How can I remove those simple notices ?

Thanks

**Comment by smalot** [comment]
Can you remove the line 13 in the file "api/policies/dynamicNode.js" ?
It's just debug notification

**Comment by pantsel** [comment]
@smalot ,
you could try running Konga in production mode.
Then the debug logs will then be suppressed.

**Comment by pantsel** [comment]
Closing this for now.
